### ISSUE TITLE
Support .vue single-file components

### ISSUE THREAD

**Issue by garyo** [TypeStrong/typedoc#1030]
I'm using Vue with typescript. Vue has single-file components which include HTML, CSS, and typescript. It would be great if typedoc could extract the <script lang="ts">...</script> sections from a `.vue` file and produce docs for those.

**Comment by aciccarello** [comment]
@garyo Thanks for the suggestion. Typedoc mostly works off of TypeScript so you would need something that extracts the typescript files before passing them to typedoc. This sounds like a good idea for a vue/webpack plugin but probably won't be part of this library.

**Comment by t-eckert** [comment]
This is something I was wanting today too. Typedoc is an amazing project. It's helped me to grow TypeScript adoption on my team. Thank you!

**Comment by mnlipp** [comment]
I know, it's old, it's closed. But it is the top match when searching for "typedoc vue", so maybe this helps if somebody is looking for a solution (like I was).

Here's my workaround:
* Maintain the typescript section of the vue in an [extra file](https://github.com/mnlipp/jgrapes-webconsole/tree/master/aash-vue-components/src/components/tablist). (I'm doing this anyway because Eclipse doesn't have a (free) editor for .vue-files.)
* Now you can run typedoc on the source directory, but this results in rather ugly output, Therefore...
* Create an index file for typedoc that imports/exports the [typescript parts](https://github.com/mnlipp/jgrapes-webconsole/blob/master/aash-vue-components/src/tsdoc-index.ts) (instead of the vue-module). Of coures, the big drawback is that you have to maintain this file manually.
* Have a [nice documentation](https://mnlipp.github.io/jgrapes/aashdoc/index.html).

**Comment by easonyu51** [comment]
> I know, it's old, it's closed. But it is the top match when searching for "typedoc vue", so maybe this helps if somebody is looking for a solution (like I was).
> 
> Here's my workaround:
> 
> * Maintain the typescript section of the vue in an [extra file](https://github.com/mnlipp/jgrapes-webconsole/tree/vue2-ts-test/aash-vue-components/src/components/tablist). (I'm doing this anyway because Eclipse doesn't have a (free) editor for .vue-files.)
> * Now you can run typedoc on the source directory, but this results in rather ugly output, Therefore...
> * Create an index file for typedoc that imports/exports the [typescript parts](https://github.com/mnlipp/jgrapes-webconsole/blob/vue2-ts-test/aash-vue-components/src/tsdoc-index.ts) (instead of the vue-module). Of course, the big drawback is that you have to maintain this file manually.

thanks

**Comment by abichinger** [comment]
This is still the top match for "typedoc vue", so I'm going to share my setup using [vite-plugin-dts](https://www.npmjs.com/package/vite-plugin-dts)

1. First add the vite plugin [vite-plugin-dts](https://www.npmjs.com/package/vite-plugin-dts) to generate the declarations:

```typescript
// vite.config.ts
// ...
import dts from 'vite-plugin-dts'
// ...
export default defineConfig({
  plugins: [
    vue(),
    dts({
      tsconfigPath: './tsconfig.app.json',
      rollupTypes: true,
      entryRoot: 'src',
    }),
  // ...
})
```

2. Create two `tsconfig` files. The first one is for vite, the second one is for typedoc

```json5
// tsconfig.app.json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "declarationMap": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

```json5
// tsconfig.typedoc.json
{
  "extends": "./tsconfig.app.json",
  "include": ["dist/index.d.ts"],
}
```

3. Create a config file for typedoc:

```json5
// typedoc.json
{
    "$schema": "https://typedoc.org/schema.json",
    "entryPoints": ["dist/index.d.ts"],
    "tsconfig": "tsconfig.typedoc.json",
}
```

4. Run `npx typedoc --options typedoc.json`
5. Done 🎉
