### ISSUE TITLE
Optional function parameter is displayed in a wrong way

### ISSUE THREAD

**Issue by Lodin** [TypeStrong/typedoc#1063]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

The original signature in the typescript file is the following:
```typescript
export function property(guard?: (value: unknown) => boolean): PropertyDecorator;
```

## Expected Behavior

The parameter callback signature should be displayed somewhere as it is displayed if the parameter is not optional. Also, `undefined` should not be displayed since the question mark `?` is already says that the parameter is optional.
<img src="https://user-images.githubusercontent.com/8037479/60429757-7350fb00-9c04-11e9-861e-4f0bc178d84e.png" width="350px" alt=""/>

## Actual Behavior

It is displayed as the following:
<img src="https://user-images.githubusercontent.com/8037479/60429546-f32a9580-9c03-11e9-95eb-979ba7e8cfd1.png" width="450px" alt=""/>

## Steps to reproduce the bug

**typedoc.json**
```json
{
  "exclude": ["**/+(__tests__|lib|node_modules)/**"],
  "excludeNotExported": true,
  "excludePrivate": true,
  "ignoreCompilerErrors": true,
  "includeDeclarations": true,
  "mode": "modules",
  "out":"./docs/api"
}
```
**Command**
```bash
$ typedoc --tsconfig ../../tsconfig.json packages
```
## Environment
  - Typedoc version: 0.14.2
  - Node.js version: 12.5.0
  - OS: Windows 10 1809

**Comment by Gerrit0** [comment]
I see two issues here:

1. The function not being properly displayed if it is part of a union (this most likely has the same root cause as #1020)
1. `undefined` being included in the displayed type if `?` is specified.

The first problem is definitely an issue.

When outputting declaration files, TypeScript will transform `(a?: number) => any` to `(a?: number | undefined) => any`. TypeDoc preserves this behavior in the documentation. There is an open issue (https://github.com/microsoft/TypeScript/issues/13195) to change this, but for now it is the standard. It seems reasonable to drop `| undefined` when there is a `?`, and should be fairly easy to implement if you'd like to give it a shot.

**Comment by Lodin** [comment]
@Gerrit0, thanks for the answer. Yeah, you're right, I'm talking mostly about the first issue. Let's close it as a duplicate.
