### ISSUE TITLE
have doc coverage

### ISSUE THREAD

**Issue by c0ncentus** [TypeStrong/typedoc#1067]
## Problem
https://compodoc.app/ (documentation coverage)

## Suggested Solution
fileCommented (match "@" maybe)      /          all files

**Comment by Gerrit0** [comment]
I was sure this had been brought up before, but I can't seem to find the issue....

This would be a neat feature to have, but just matching on `@` won't be very helpful. Ideally this feature should report doc comments / documented members for each file. (Even better check for `@param` & such)

I think it should be fairly straightforward, it would probably be best to implement it as a plugin first so that it can be disabled to avoid a performance hit for those not interested in the information it reports.

**Comment by c0ncentus** [comment]
just one thing : just typing doc coverage nodejs on google : it's a shame. why they do doc cov on angular project and not for typescript ? 👎 

For my big project doc coverage is highly valuable , see which file dont have doc for me : it save me ....

Imagine, you have 10K of code and 100? files of angular or react project or whatever ... and you want doc the application, you just run coverage and see what file missed...

I keep looking for this plug in , when thats available keep me notify please 👍, that's awesome 🥇

**Comment by Gerrit0** [comment]
Closing this as it should really be implemented as a plugin first, and should probably remain as a plugin so that we avoid the performance hit of calculating this. If you (or anyone) implements this, please post here to promote it :)
