### ISSUE TITLE
Project AST on mardown on index doc ?

### ISSUE THREAD

**Issue by c0ncentus** [TypeStrong/typedoc#1090]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem
No Project directory AST like:
.
+-- _config.yml
+-- _drafts
|   +-- begin-with-the-crazy-ideas.textile
|   +-- on-simplicity-in-technology.markdown
+-- _includes
|   +-- footer.html
|   +-- header.html
+-- _layouts
|   +-- default.html
|   +-- post.html
+-- _posts
|   +-- 2007-10-29-why-every-programmer-should-play-nethack.textile
|   +-- 2009-04-26-barcamp-boston-4-roundup.textile
+-- _data
|   +-- members.yml
+-- _site
+-- index.html

## Suggested Solution
It will be nice to put material design on folder and specefic files like https://www.npmjs.com/package/markserv maybe it will more user friendly

thank you :)

**Comment by Gerrit0** [comment]
It sounds like you want TypeDoc to manage your whole Jekyll site instead of just outputting a folder of HTML. This isn't its goal.

If you want to set up TypeDoc documentation as a part of the site, you can see https://github.com/TypeStrong/typedoc-site for how we do it.

---

Also, a directory tree isn't an AST.

**Comment by aciccarello** [comment]
@Gerrit0 is correct. TypeDoc is designed to generate a folder of static assets. If you are are describing a different issue please clarify. Thanks!
