### ISSUE TITLE
Typedoc does not include props from an interface when Omit is used

### ISSUE THREAD

**Issue by sylvesteraswin** [TypeStrong/typedoc#1094]
In the `extendedTypes` of `Props2` I get something similar to the below, but there is no `id: 88` in the generated JSON.

```json
"extendedTypes": [{
	"type": "reflection",
	"declaration": {
		"id": 88,
		"name": "__type",
		"kind": 65536,
		"kindString": "Type literal",
		"flags": {},
		"sources": [{
			"fileName": "fileName",
			"line": 14,
			"character": 43
		}]
	}
}],
```

- [ ] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

I get only `c:number` as props in `Props2`.

## Actual Behavior
`Props2` to have `a: string`, `b: string` and `c: number` as its interface. 

## Steps to reproduce the bug

```tsx
export interface Prop1 {
 a: string;
 b: string;
 c: string;
}

export interface Prop2 extends Omit<Prop1, "c"> {
 c: number;
}
```

```node
typedoc --out typedoc ./file.tsx --theme minimal --mode modules
```

## Environment
  - Typedoc version: 0.15.0
  - Node.js version: v11.15.0
  - OS: MacOS 10.14.6

**Comment by sylvesteraswin** [comment]
@aciccarello what are you thoughts on this bug?

**Comment by Gerrit0** [comment]
This is a weird bug... There appears to be a couple issues:

1. Extending from a type literal instead of an interface / class doesn't work - I'm guessing the theme assumes that `extends` will only occur with a type reference, which `Omit<Prop1, 'c'>` is not. Fixing this should at least allow "Type literal" to appear in the hierarchy section of the docs.
1. Type literals which appear only in `extend` clauses are incorrectly converted - it is missing information about the type, not sure why this is. Unfortunately type aliases are rather like C's macros. They are resolved incredibly early in the compilation process and are difficult to detect & extract information about.

**Comment by vkefallinos** [comment]
https://github.com/vkefallinos/typedoc/commit/ef812b111e4f6f45e8aaf1f51e62313d2b5265ab
I did a rough implementation to add Omit handling. It works but this code can't be merged by any means.

**Comment by MasterKale** [comment]
I figured I'd chime in with my experience with this issue.

I have a series of classes that `extends Omit<>` interfaces in the `dom` TypeScript library:

```ts
export interface PublicKeyCredentialUserEntityJSON extends Omit <
PublicKeyCredentialUserEntity, 'id'
> {
  id: Base64URLString;
}
```

Here's `PublicKeyCredentialUserEntity` in **node_modules/typescript/lib/lib.dom.d.ts**:

```ts
interface PublicKeyCredentialUserEntity extends PublicKeyCredentialEntity {
    displayName: string;
    id: BufferSource;
}
```

[The resulting documentation for this interface](https://docs.simplewebauthn.dev/interfaces/_simplewebauthn_typescript_types.publickeycredentialuserentityjson.html) fails to list any information about `PublicKeyCredentialUserEntity`, instead showing an empty object:

<img width="424" alt="Screen Shot 2020-07-22 at 12 04 48 PM" src="https://user-images.githubusercontent.com/5166470/88217651-b5841a80-cc13-11ea-80b2-328ebc798bea.png">

## Environment

- Typedoc version: 0.17.0-3 (because of https://github.com/TypeStrong/typedoc/pull/1184)
- Node.js version: v12.18.0
- OS: MacOS 10.15.5

**Comment by codycuellar** [comment]
I get the exact same output as @MasterKale but using Pick, also on 0.17.0-3. 

While I know next to nothing about the internal code of typedoc, I have noticed (I believe is in the theme stage) that if you extend an interface which is not exported, the theme has nothing to link inherited members from and instead list them inherited from itself. For instance:

```typescript
interface Foo {
    one: number;
    two: number;
}

export interface Bar extends Foo {
    three: string;
}
```

Typedoc creates a bar.html page for the Bar interface, but not for Foo which isn't exported. The HTML displays the inherited property `one`, but says it is inherited from Bar itself which is clearly incorrect, but is understandable why it's doing that since there's no HTML file to link Foo.one.

<img width="809" alt="Screen Shot 2020-10-29 at 10 31 47 AM" src="https://user-images.githubusercontent.com/30381480/97595711-f7221f80-19d1-11eb-8205-5a49f27f8a15.png">

Regarding the `Pick` and `Omit` issue, my best guess is that since `Bar extends Pick<Foo, 'one'>`effectively generates an anonymous object that isn't kept track of during the plugin reflection resolving stage, it never even adds the properties to the objects that get passed off to the theme.

However, it gets more interesting when you get the same result if inheriting from an exported `type`. Types don't get their own pages, but they should be kept track of in the reflection resolving stages, so while the inheritance tree is understandable, it's very confusing why we're not even seeing the inherited members.

```typescript
interface Foo {
    one: number;
    two: number;
}

export type FooPicked = Pick<Foo, 'one'>;
export interface Bar extends FooPicked {
    three: string;
}
```

<img width="986" alt="Screen Shot 2020-10-29 at 10 44 10 AM" src="https://user-images.githubusercontent.com/30381480/97597587-fbe7d300-19d3-11eb-8f35-a4eeef846433.png">

**Comment by Gerrit0** [comment]
The library mode support for inheritance is being tracked in #1386, I'll be looking at that next week, and hopefully end up with something that produces reasonable results. I'm pretty sure TypeDoc's inheritance support was written before you could inherit from types, so it was never considered.

**Comment by Gerrit0** [comment]
This works properly in 0.20 - took a bit more than a week.. but worth the time spent understanding it all.

![image](https://user-images.githubusercontent.com/19329837/100523316-e00b5480-316c-11eb-83f5-646dc1ac679e.png)
