### ISSUE TITLE
Option/theme to show all overloads at once

### ISSUE THREAD

**Issue by jeremymeng** [TypeStrong/typedoc#1100]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

There were issues related to discoverability of docs for overloads. But this one is slightly different.

## Problem

The current behavior using default theme is that doc is only shown for the first overload.  It is hard for new users to discover that they need to click on the other overloads to get docs for them. Also some time it is desirable to have all the docs showing in order to compare the differences.

## Suggested Solution

Either add an option to show them them. Or document how to achieve that by customizing the theme styles.

**Comment by Gerrit0** [comment]
Unfortunately just changing the styles isn't enough to do this. The overload groups are created by [Signature.ts](https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/assets/js/src/typedoc/components/Signature.ts), so to remove them you would have to remove that file from the build and probably also merge the changes in https://github.com/TypeStrong/typedoc-default-themes/pull/49, or something similar. I believe that PR breaks the dropdown functionality currently in place, but I'd like to get the fix for non-js users merged before the next release.
