### ISSUE TITLE
Ignore a whole module in the generated doc (regression?)

### ISSUE THREAD

**Issue by Dzenly** [TypeStrong/typedoc#1113]
Probably regress in:
https://github.com/TypeStrong/typedoc/issues/842

I have a TS file with one exported function.

Such header does not exclude file from documentation:
```
/**
 * @hidden
 * @ignore
 * @internal
 */

/**
 * dummy comment.
 */
```

But if I use 
```
/**
 * @hidden
 * @ignore
 * @internal
 */
```

as header and then

```
/**
 * @ignore
 */
```
before my exported function, the file is excluded from documentation.

Typedoc version: 0.15.0
Typescript version: 3.5.3.
Ubuntu 19, x64.

**Comment by Gerrit0** [comment]
Took me a few tries to reproduce:

1. Running `typedoc --out docs src/` correctly hides the exported function
1. Running `typedoc --out docs src/ --mode modules` correctly hides the exported function
1. Running `typedoc --out docs src/ --mode file` does _not_ hide the exported function, so this appears to be a bug just in that mode...

---

It appears that this is the case because in `file` mode we don't actually create a declaration for each file, and thus modifiers on the file don't get applied to the children.

https://github.com/TypeStrong/typedoc/blob/695d996e2dae1b716800213339acc828331dc098/src/lib/converter/nodes/block.ts#L71-L79

This is.. difficult to fix. The `file` mode seems to be intended for projects that export everything through a single module, so the nodes *shouldn't* be included under modules when displayed in the documentation, but we need them to be converted under a module so that they pick up the `hidden` tags.

I'm not sure how this ought to be fixed. Converting the nodes under a scope and then moving them is the obvious solution, but "moving" reflections isn't something that we've done before, and I have no idea how prone to breaking it would be.

**Comment by Dzenly** [comment]
Just in case - my cmd line is:
`typedoc ./types --out docs --includeDeclarations --excludeExternals --excludeNotExported --readme typedoc-readme.md`

So i don't use `--mode` option.

**Comment by Gerrit0** [comment]
In that case, the mode defaults to `modules`, so this shouldn't be happening.

Just to make sure, TypeDoc doesn't necessarily recognize the first comment in a file as the file comment. File comments are only recognized if there is another doc comment between it and any statements. See #1080 for details. Do you have an "extra" comment to ensure TypeDoc recognizes the module comment?

**Comment by Dzenly** [comment]
Thank is why I use:
```
/**
 * dummy comment.
 */
```
After the first commit.

**Comment by Gerrit0** [comment]
Could you provide a repo I can look at to see what is different? I can't seem to reproduce the issue in `modules` mode.

**Comment by Dzenly** [comment]
https://github.com/Dzenly/tia

File to test:
https://github.com/Dzenly/tia/blob/master/src/engine/runner.ts

Now i use @ignore for export and file is excluded.

`npm i && npm run d`

`npm run d` will build the project and run `create-typedocs.sh`
`create-typedocs.sh` will generate documentation in `docs` directory and start google-chrome-stable with generated documentation opened.

**Comment by Gerrit0** [comment]
Here's what I did:

1. Forked + Cloned tia
1. `npm add typedoc` - you appear to be using a global install, not sure what version, so I installed the latest, doesn't need to be in dependencies, but I forgot to add the dev flag
1. `npm i`
1. Edited `src/engines/runner.ts` as below:
```diff
index 4678d58..c4b54c6 100644
--- a/src/engine/runner.ts
+++ b/src/engine/runner.ts
@@ -1,9 +1,8 @@
 /**
  * @hidden
- * @ignore
- * @internal
  */

+/** */
 import * as fs from 'fs';
 import * as path from 'path';
 import * as _ from 'lodash';
@@ -550,9 +549,6 @@ function extractDiffedPaths(testOrDirInfo: TestInfo, result: string[], suiteRoot
   }
 }

-/**
- * @ignore
- */
 // Returns subject for email.
 export async function runTestSuites() {
   fileUtils.safeUnlink(gT.rootLog);
```

1. `npm run d`
1. Confirmed that `runner` is not in the file list in the generated docs
1. Pushed my changes so you can review: https://github.com/Gerrit0/tia

I noticed that in `typedoc.js` you use `module.export` instead of `module.exports` - so TypeDoc isn't loading any settings from it.

**Comment by Dzenly** [comment]
Wow, thank you very much!
I also confirm that now this 'runner' not in my list for such patch (even with incorrect typedoc.js).
Probably it was some browser cache issue, I will take it into account in future. Sorry for false alarm.

**Comment by chpio** [comment]
This seems still to not work.

I have

```ts
/**
 * @module
 * @internal
 */
```

at the top of my file. Mode is not set. In the generated output the module is shown with a "Internal" annotation, so it seem to be read correctly. I execute typedoc with the excludeInternal arg: `typedoc --excludeInternal` and have "excludeInternal" set to true in my typedoc.json file.

But it still is output.
