### ISSUE TITLE
Document plugin API

### ISSUE THREAD

**Issue by FranklinYu** [TypeStrong/typedoc#1132]
I see that there were several typedoc plugins mentioned in ReadMe. Is the plugin API documented somewhere? Or new plugin authors are supposed to look at existing plugins to get an idea?

**Comment by Gerrit0** [comment]
Unfortunately the best I can offer you right now is to look at existing plugins. The exposed plugin api needs some serious consideration. Right now almost every plugin uses APIs that we don't export directly from the root instance, which is less than ideal, but unfortunately necessary due to the `@Component` architecture that is used. #521 is tracking making a guide, but I've been putting it off until we get around to removing that decorator.

**Comment by FranklinYu** [comment]
@Gerrit0 Thanks for the pointer. I would follow that issue instead so we have less open issue hanging around.
