### ISSUE TITLE
Error: Could not create output directory

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#1167]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Actual Behavior

I randomly become this error message independently if the directory already exists or not.
Each time when running typedoc again it succeeds.
```
Error: Could not create output directory D:\MyDev\ljs_app\trunk\periscope\doc
Error: Documentation could not be generated due to the errors above.
```

## Steps to reproduce the bug

in `D:\MyDev\ljs_app\trunk\periscope` run `npx typedoc --out doc/ src/`

## Environment
  - Typedoc version: 0.16.2
  - Node.js version: 12.13.1
  - OS: Windows 8

**Comment by Gerrit0** [comment]
This is, unfortunately, unactionable without a reproduction... Does the output directory already exist when it is failing? Do you have `--disableOutputCheck` set? (Might cause this, I don't think it will fix it)

**Comment by Gerrit0** [comment]
Looking a bit into this, I don't see anything obviously wrong with what TypeDoc is doing... 

https://github.com/TypeStrong/typedoc/blob/3faa547971be3a82619c7f5f0f0f92f6a3d51552/src/lib/output/renderer.ts#L264-L271

**Comment by doberkofler** [comment]
Unfortunately I was not able to find a pattern on when the error happens except for the fact that whenever it happens, the next invocation works as expected. Would you recommend removing the directory before running typedoc?

**Comment by Gerrit0** [comment]
That really shouldn't be necessary... but if it fixes the problem for you it doesn't hurt anything.

Unfortunately "next invocation works" doesn't tell me enough to know what the problem is. I ran a few tests with removing / making directories many times and was unable to get it to error. (Without running multiple programs that modified the same directory at the same time of course)

**Comment by hamirmahal** [comment]
I came across a similar issue in another project. This might be somewhat related; if this is adding unnecessary clutter, I can delete this comment.

I was trying to output TypeDoc's HTML documentation to a `/typedoc` directory, and the command
`npx typedoc --out`**`/typedoc`** wasn't working.

When I changed this to
`npx typedoc --out`**`./typedoc`**, with a `.` in front of the `/`, TypeDoc was able to output the HTML documentation successfully.

This doesn't sound like the issue @doberkofler was having, but since this issue was one of the top results that appeared when I searched something along the lines of `Error: Could not create output directory /typedoc
Error: Documentation could not be generated due to the errors above.`, I figured this might help future people who encounter similar issues. Hope this helps whoever ends up reading it.
