### ISSUE TITLE
Not to append package version to the package name in generated json files

### ISSUE THREAD

**Issue by antifree** [TypeStrong/typedoc#1175]
- [ x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem
Typedoc appends version to package name in json file:
```
{
	"id": 0,
	"name": "testlib - v1.0.0",
	"kind": 0,
	"flags": {},
	..................
}
```
It is not comfortable for me when I need to make some logic based on the package name.
Tested with v 15.8. 
## Suggested Solution
```
{
	"id": 0,
	"name": "testlib",
        "version": "1.0.0"
	"kind": 0,
	"flags": {},
	..................
}
```

**Comment by Gerrit0** [comment]
You can set the package name when generating docs with `--name`

That said, it seems reasonable to split this up, and combine it in the themes...

**Comment by Gerrit0** [comment]
After trying out splitting up the name, I don't think that's the correct solution. Since it changes whenever the containing project's version changes, and cannot (or at least I don't think it makes sense to) be overridden.

I'll instead change including the version in the name to be opt in, according to the new `--includeVersion` flag. This restores the previous behavior while still allowing users to easily include the version if they want it.

**Comment by antifree** [comment]
Thank you!
