### ISSUE TITLE
Upper case section links not work on generated html

### ISSUE THREAD

**Issue by tajpouria** [TypeStrong/typedoc#1182]
Upper case segment links not work on generated HTML doc e.g. in the following example all links work except `ObjectStores` because it contains capital S.
```md
  - [ init ](#init)
  - [ ObjectStores](#objectStores)
  - [ put ](#put)
  - [ get ](#get)
  - [ delete ](#delete)
  - [ keys ](#keys)
  - [ values ](#values)
  - [ entries ](#entries)
```

## Environment
  - Typedoc version: 0.16.6
  - Node.js version: 12.13.0
  - OS: Window 10 Enterprise

**Comment by Gerrit0** [comment]
I'm not sure I understand the problem. All the links seem to be created with the targets you specified...

**Comment by tajpouria** [comment]
Check this out:
https://elegant-engelbart-ce0e2f.netlify.com/

**Comment by Gerrit0** [comment]
Thanks for the reproduction!

Rewriting all URLs to be lowercase isn't a good idea since they may be case sensitive... While the generated headings are lower cased, parsing all links contained in the markdown would be incredibly error prone.

Further, nobody else does this. It would be very unintuitive behavior. [#UPPERlower](#UPPERlower) <-- links to `#UPPERlower`, not `#upperlower`

**Comment by aztack** [comment]
Maybe links in the markdown should preserve the cases: 
https://github.com/TypeStrong/typedoc/issues/1295#issuecomment-636430635
![image](https://user-images.githubusercontent.com/782871/83346105-3d545380-a34c-11ea-8fcc-cdc2ac6b477b.png)
