### ISSUE TITLE
Unexported variables are not removed 

### ISSUE THREAD

**Issue by njh7799** [TypeStrong/typedoc#1195]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

### Not exported variables are not removed 

Here's my code.
```json
// typedoc.json
{
  "name": "Orion-facebook",
  "inputFiles": ["./src"],
  "mode": "file",
  "out": "docs",
  "excludeNotExported": true,
  "excludePrivate": true
}
```

```ts
// my code
...
const getPageData = async (date: string, from: string) => {
  return await ...;
};

const findRow = ($, to: string) => {
  const row = ...;
  return row;
};

const findCurrencyRate = ($, row) => {
  let currencyRate;
  ...
  return currencyRate;
};

const getCurrencyRate = async (date: string, from: string, to: string) => {
  const response = await getPageData(date, from);
  const html = response.data;
  const $ = cheerio.load(html);
  const row = findRow($, to);
  const currencyRate = findCurrencyRate($, row);
  return currencyRate;
};

const getNothing = async () => {};

export default getCurrencyRate;

```
I thought only `getCurrencyRate` would be generated at doc files since I'd set excludeNotExported to be true. However, the result was shown as below. The other non exported variables are not removed.  

## Actual Behavior

![image](https://user-images.githubusercontent.com/40619551/73326653-4c3fd200-4296-11ea-98f7-1b630d09a4ea.png)

## Environment
  - Typedoc version:0.16.9
  - Node.js version:12.14.0
  - OS:mac

**Comment by xshkut** [comment]
I have the same issue. As temporary workaround you can tag your functions as @internal like 
```
/**@internal */
const findRow = ($, to: string) => {
const row = ...;  
return row;  
};
```
Also it works well with `--mode modules`, but it can affect your classes (change them to external modules and wrap them in double quotes)

**Comment by Gerrit0** [comment]
With `--mode file` this is expected behavior.

File mode tells TypeDoc that your source files should be treated as global script files, all declarations in them are implicitly exported.

You might be interested in the upcoming library mode, #1184, where TypeDoc builds documentation for only those declarations exported from the input file. You can try it out by installing `typedoc@next` and changing your typedoc.json file to be:

```ts
{
  "name": "Orion-facebook",
  "inputFiles": ["./src/index.ts"], // Note that this specifies a single file, since otherwise all files are treated as entry points.
  "mode": "library",
  "out": "docs",
  "excludeNotExported": true, // Doesn't do anything in library mode
  "excludePrivate": true
}
```

**Comment by hugomrdias** [comment]
@Gerrit0 didn't help
<img width="1258" alt="Screenshot 2020-03-30 at 10 53 06" src="https://user-images.githubusercontent.com/314190/77900346-d516c200-7275-11ea-8382-b28129d3be7a.png">

Managed to remove the require with `excludeNotDocumented` but that is not ideal.

From the PR you mentioned seems like another approach i tried before, generate declaration with tsc and feed typedoc the declarations and not the source. This works up to a point because i loose almost all the JSDocs comments not related to types, things like examples, param descriptions etc. 

Also with typedoc@next i get

```
Warning: File /Users/hugomrdias/code/pl/js-ipfs-utils/src/temp-dir.js is not a module and cannot be converted in library mode
Warning: File /Users/hugomrdias/code/pl/js-ipfs-utils/src/env.js is not a module and cannot be converted in library mode
```
 and docs are empty.
