### ISSUE TITLE
Include typedefs in typedocs

### ISSUE THREAD

**Issue by benmccann** [TypeStrong/typedoc#1214]
- [X] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

We declare some types using typedefs. You can see several examples of methods using this typedef in the same file. Example typedef:
https://github.com/chartjs/Chart.js/blob/0d6c05cca00813b0fb93396ce7b37b637f2e6833/src/core/core.scale.js#L11

However, method parameters in the Typedocs using this typedef appear as `any` (in this case I'd expect it to appear as `Tick`). 

## Suggested Solution

Include typedefs as types in the generated documentation

**Comment by Gerrit0** [comment]
Its seems reasonable to me to support this. I think there should be a special case for typedefs of type `object`/`Object` to be instead converted as interfaces since they can contain [`@prop` / `@property`](http://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#typedef-callback-and-param) tags to more fully describe the object.

Couple notes when implementing:
1. These types are implicitly exported, they cannot *not* be exported.
1. We should also support `@callback`

**Comment by benmccann** [comment]
> I think there should be a special case for typedefs of type object/Object to be instead converted as interfaces since they can contain @prop / @property tags to more fully describe the object.

That makes sense to me. In fact we had `@interface` historically, but when we migrated to TypeScript we found that it didn't support that tag, so we added a `@typedef` and now have both:

https://github.com/chartjs/Chart.js/blob/0d6c05cca00813b0fb93396ce7b37b637f2e6833/src/core/core.plugins.js#L183

**Comment by Gerrit0** [comment]
Well... I took another look at this, and turns out it wasn't nearly as painful to support as I thought! 0.20.6 works with it :)
