### ISSUE TITLE
Application#convert silently fails in misleading way

### ISSUE THREAD

**Issue by LJNeon** [TypeStrong/typedoc#1233]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior

When `app.convert(app.expandInputFiles(["../invalid/path/here"]))` is provided an invalid file/directory path it will throw an error or otherwise indicate failure.
## Actual Behavior

It silently fails and calling `app.generateJson()` returns 
```js
{ id: 0, name: '', kind: 0, flags: {} }
```

## Steps to reproduce the bug

Here's a small script to reproduce the error:
```js
const {Application} = require("typedoc");
const app = new Application();
app.bootstrap();
const project = app.convert(app.expandInputFiles(["../fake/lol/index.d.ts"]));
if(project != null)
  app.generateJson(project, "./data.json");
```
## Environment
  - Typedoc version: 0.17.0 or next (both have this)
  - Node.js version: 13.11.0
  - OS: Windows 10

**Comment by Gerrit0** [comment]
Thanks for digging into this! Yea this is an issue...

Seems like a fairly simple fix, we just need to check if we are processing an input file here and throw if the file doesn't exist. (Will also require a modification to cli.ts to catch said error and log instead of crashing)

https://github.com/TypeStrong/typedoc/blob/master/src/lib/application.ts#L285

**Comment by Gerrit0** [comment]
I knew there was an issue for this! #1404 was somewhat caused by the same issue. 0.20 includes a fix (currently `typedoc@beta`)
