### ISSUE TITLE
Internal Modules displayed as External Modules

### ISSUE THREAD

**Issue by FlippieCoetser** [TypeStrong/typedoc#124]
Right side navigation lists modules correctly. Main body lists all modules as External modules. See below screen shot.

![image](https://cloud.githubusercontent.com/assets/3672126/8890308/fa381970-32fc-11e5-8357-e241d3deaafb.png)

**Comment by sebastian-lenz** [comment]
Hi, thank you for your message. Looks like this a naming confusion.

The separation of code belonging to your project ("Internals") and vendor / lib code ("Externals") only appears in the right side navigation and not within the content - this is intentional. You configure this two groups using the <code>--externalPattern</code> option, they are not code related.

Within the left side the caption "External modules" means "CommonJS / AMD modules", the addition "External" was necessary as TypeScript also has "modules" which are basically object literals. These two will be renamed in the near future and will show up as "modules" and "namespaces", see #109.

However I'm not happy with the titles in the right side navigation, maybe we should remove "Internals" altogether and rename "Externals" to something like "Vendors" or "Libs"?

**Comment by aciccarello** [comment]
I like the idea of naming the "Externals" to "Libs"

**Comment by evil-shrike** [comment]
I'd suggest using "Dependencies" and remove "internal" (or "Internals") at all - they are not internals they are just the lib.

**Comment by balupton** [comment]
Ran into this today, and spent an hour trying different `externalPattern` combinations to no avail, so I figure that this is the issue.

Is this a theme issue, or a core issue?

**Comment by aciccarello** [comment]
Internal/external is a core distinction. You may want to look at #903 or the [internal-external plugin](https://github.com/christopherthielen/typedoc-plugin-internal-external). You can also ask questions on [gitter](https://gitter.im/TypeStrong/typedoc) if that is more helpful.

**Comment by aciccarello** [comment]
If you are using a `jsconfig.json` file TypeDoc will not look at it so you will need to pass those file/directories to typedoc explicitly. Only `tsconfig.json` files are read.
