### ISSUE TITLE
Use json file for index search

### ISSUE THREAD

**Issue by sgrishchenko** [TypeStrong/typedoc#1251]
- [x] I have checked [issues with enhancement label](https://github.com/TypeStrong/typedoc/labels/enhancement) and found no duplicates

## Problem

Now `typedoc-default-themes` package use `serach.js` file for index search providing. `eval` function is called to parse data for search. I think, this is potential vulnerability.

## Suggested Solution

I think, it will be more safe to use JSON format for search data passing.

**Comment by Gerrit0** [comment]
>  I think, this is potential vulnerability.

Not in this case. We are only sending JSON data. Sure, someone could put extra stuff in there via a plugin, but at that point they already have code running on someone's machine via node... which is much worse that on a site. Since documentation hosts can modify files before publishing anyways, there isn't a vulnerability here.

I do like the switch to json though.

**Comment by Gerrit0** [comment]
Resolved by #1252, I hope to have time for a release tonight :)

**Comment by Gerrit0** [comment]
Released in 0.17.4 :)
