### ISSUE TITLE
Make search index more deterministic

### ISSUE THREAD

**Issue by blutorange** [TypeStrong/typedoc#1260]
## Search Terms

search index, github pages, diff, git

## Problem

There's a minor issue with the search index as it is generated right now: the git diff between two generated search indices is almost always the entire file, which can be a few MB. That's not ideal for people who are hosting the documentation as a github page (such as we're planning to do here: primefaces/primefaces#5767). It would be nice if the search index could be generated in a way that small changes to a library only result in small changes to search index.

## Suggested Solution

Slightly change how the search index is created:
* Add line breaks when generating the search index (pretty print JSON with indent=1)
* Currently the ID of the search entry is an incrementing number starting at 0. Instead of that, create an MD5 hash over the data of the search index (kind, name, url, classes, parent) and use that as the ID  of the search entry (making sure to check for a collision)
* Change `typedoc.search.data` from an array to an object, with the ID as the key (see below)
* Make a few minor adjustments to the Search component so that it works with the slightly changed data structure

I quickly tried this locally and it seems to work fine - if you're OK with this change I might be able to create a PR?

<details>
<summary>Click to view</summary>

```javascript
var typedoc = typedoc || ({});
typedoc.search = typedoc.search || ({});
typedoc.search.data = {
"kinds": {
"2": "Namespace",
"4": "Enumeration",
"16": "Enumeration member",
"32": "Variable",
"64": "Function",
"128": "Class",
"256": "Interface",
"512": "Constructor",
"1024": "Property",
"2048": "Method",
"65536": "Type literal",
"4194304": "Type alias"
},
"rows": {
299824150205436: {
// This ID entry may not be need anymore, as the key is the ID
"id": "299824150205436",
"kind": 65536,
"name": "__type",
"url": "interfaces/moment.localespecification.html#meridiem.__type-1",
"classes": "tsd-kind-type-literal tsd-parent-kind-property",
"parent": "moment.LocaleSpecification.meridiem"
},
1632234115275334: {
// This ID entry may not be need anymore, as the key is the ID
"id": "1632234115275334",
"kind": 65536,
"name": "__type",
"url": "interfaces/moment.localespecification.html#ispm.__type",
"classes": "tsd-kind-type-literal tsd-parent-kind-property",
"parent": "moment.LocaleSpecification.isPM"
}
// ...
}}
```

</details>

**Comment by Gerrit0** [comment]
> the git diff between two generated search indices is almost always the entire file, which can be a few MB.

I'm pretty sure this isn't quite right.

`git diff` displays changes by line, so the diff there looks really large. However, lines are a human concept, there's no need for git to use them in the internal representation of the index. (And while I haven't read the git source, I can virtually guarantee it doesn't! You can store binary files in git, which likely don't have lines at all.)

That said, I'm not opposed to outputting prettified JSON, search.json isn't intended for human use, but GZIP will take care of the slight increase in output size... However, I don't think this will much help your original concern. In the latest release, search.js was changed to search.json - and instead of outputting the original data to build the search index on the client, we create the index when generating docs.

This change enables a much better experience on the client, especially on low end devices, but does increase the file size with even more data that isn't useful to humans. We could probably optimize this file (I don't think `id` is needed at all, we can just use `url` as the `ref`), but that hasn't been done yet.

**Comment by blutorange** [comment]
Hmm, I think you are right. I did some more experiments and the docs seem compress really well.

The new search.json also has the index property for the lunr search, which takes up around 60-80% of the total lines (when formatted) and appears to change frequently. Removing the IDs would probably not do much.

Seems to me it's fine as it right now, so I'll close this, but thanks for your time : )
