### ISSUE TITLE
Function overload comments aren't working

### ISSUE THREAD

**Issue by jtenner** [TypeStrong/typedoc#1262]
## Search terms
Function, Overload, Class, method

## Expected Behavior
Each overload should be commented appropriately.

## Actual Behavior

Please check out this method here linked on my github page for an example of the bug.

https://jtenner.github.io/libtelnet-ts/classes/telnet.html#on

Every other `on()` function overload seems to be empty and it's reporting the wrong comments for each one.

## Steps to reproduce the bug

Do something like this:

```ts
export class TheClass {
  /** This is "one" */
  on(input: "one"): void;
  /** This is "two" */
  on(input: "two"): void;
  /** This is "three" */
  on(input: "three"): void;
  /** Generic */
  on(input: string): void;
}
```

## Environment
- Typedoc version: ^0.17.3
- TypeScript version: 3.9.0-beta
- Node.js version: v12.9.1
- OS: ubuntu on windows

If perhaps I was given guidance as a beginner dev on this project, I would be happy to submit a pull request and help fix the problem.

**Comment by Gerrit0** [comment]
I wish I could point you to where this was happening, but I don't know myself! There are unfortunately several parts of the code responsible for dealing with comments, and I haven't a clue which one of them is to blame for this.

**Comment by Gerrit0** [comment]
Looks like this issue is in the themes. If I view source, the content is there in the DOM.

There was some refactoring there recently - @sgrishchenko helped out with it and might have an idea of what's going on here. It's really weird how it works for the first few overloads then starts skipping some. (Why on earth does clicking on "negotiate" show "sb"?!)

I'm not seeing the issue in the code that does this - it's at https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/assets/js/src/typedoc/components/Signature.ts if you want to take a look.

**Comment by Gerrit0** [comment]
I guess it isn't quite that weird, it does break on all even signatures, which makes more sense than working for the first few. Still not sure what the problem is though.

**Comment by jtenner** [comment]
I wish I could help!

**Comment by Gerrit0** [comment]
Oh, well, in hindsight that's obvious. Querying for `.tsd-description` doesn't work when the description contains a description.

**Comment by Gerrit0** [comment]
If you delete package-lock.json (or yarn.lock) and reinstall, you should pick up 0.10.1 which has a patch for this :)

**Comment by jtenner** [comment]
Thanks!
