### ISSUE TITLE
Option to remove prefix underscores in filenames

### ISSUE THREAD

**Issue by Drarig29** [TypeStrong/typedoc#1269]
## Problem
I'm using GitLab Wiki to host my TypeDoc documentation, which I render to markdown, thanks to the plugin.

The problem is quite the same as [for this issue](https://github.com/TypeStrong/typedoc/issues/648), however the page doesn't return a 404 error but it's simply shown as raw markdown code instead of an actual render.

There is no way of configuring GitLab wiki to solve this problem, so maybe you could fix the problem at its root...

## Suggested Solution
Maybe you could then add an option to remove underscores from the start of documentation files' names.

**Comment by Gerrit0** [comment]
Workaround for now: Use https://www.npmjs.com/package/typedoc-plugin-external-module-name to rename each module.

The underscore shows up because TypeDoc uses TypeScript's names for modules, which includes `"` around filenames, and we then normalize filenames to remove special characters, resulting in filenames leading with `_`.

This should go away with library mode.
