### ISSUE TITLE
`declare module` parsed as `namespace`

### ISSUE THREAD

**Issue by arnog** [TypeStrong/typedoc#1284]
This input:
```typescript
declare module "m" {
  export function f();
}
```

generates this JSON output:
```json
{
	"id": 0,
	"name": "",
	"kind": 0,
	"flags": {},
	"originalName": "",
	"children": [
		{
			"id": 1,
			"name": "\"m\"",
			"kind": 2,
			"kindString": "Namespace",
			"flags": {
				"isExported": true
			},
			"children": [
				{
					"id": 2,
					"name": "f",
					"kind": 64,
					"kindString": "Function",
					"flags": {
						"isExported": true
					},
					"signatures": [
						{
							"id": 3,
							"name": "f",
							"kind": 4096,
							"kindString": "Call signature",
							"flags": {
								"isExported": true
							},
							"type": {
								"type": "intrinsic",
								"name": "any"
							}
						}
					],
				}
			],
			"groups": [
				{
					"title": "Functions",
					"kind": 64,
					"children": [
						2
					]
				}
			],
		}
	],
	"groups": [
		{
			"title": "Namespaces",
			"kind": 2,
			"children": [
				1
			]
		}
	]
}
```

I was expecting reflection with id = 1 to be of kind = 1 (module), not of kind = 2 (namespace)

**Comment by Gerrit0** [comment]
Looks like this is because in [the AST](https://ts-ast-viewer.com/#code/CYUwxgNghgTiAEBbA9sArhBAiRX4G8AoeeEADwAdkYAXeAMzQDswaBLZJhgCgEoBuQgF9ChJlEQgAzhShgEAMWTICxEvGFA), this creates a `ModuleDeclaration` node, which is the same node type created by namespaces.

Should be a pretty simple fix to switch the `kind` argument to `createDeclaration` if the name of the node is a `StringLiteral` - https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/nodes/module.ts

**Comment by Gerrit0** [comment]
v0.17.7 released with this :)

**Comment by arnog** [comment]
Awesome. Thank you!
