### ISSUE TITLE
TypeDoc @event

### ISSUE THREAD

**Issue by DayColor** [TypeStrong/typedoc#1285]
I've seen that TypeDoc can document the `@event` annotation, though it doesn't seem to act the same way JsDoc's `@event` annotation does.
Can I please get some clarification as to how it functions, and how could I document `EventEmitter` events?
Thanks

**Comment by Gerrit0** [comment]
TypeDoc's `@event` currently just changes the reported kind of a property. It's used like this:

The class gets a property for each event, which contains documentation and the `@event` tag

https://github.com/TypeStrong/typedoc/blob/bc20444c6b92f6d5946875a066f277346a7e437b/src/lib/output/events.ts#L40-L44

This will then be rendered as an event:

![image](https://user-images.githubusercontent.com/19329837/80430648-72343d00-88ac-11ea-8c33-755fab0d6a1d.png)

This is something, but unfortunately isn't great. Since we're eventually going to adopt TSDoc I've raised this issue there as well.

**Comment by DayColor** [comment]
Alright got it now.
I just have to say that it was a hard process finding information about this specific annotation online and how it works with TypeDoc, so I would recommend adding an example to the documentation under the @event annotation
https://typedoc.org/guides/doccomments/#event

Thanks!

**Comment by aaclayton** [comment]
It would be nice to be able to document events purely with documentation without having to actually create a property or function on the prototype class which contains them. For example, it would be good to be able to do this:

```js
/** 
 * An event that fires when something happens.
 * @event beginRender
 */
```

Instead of needing to create an actual property i.e.:
```js
/** 
 * An event that fires when something happens.
 * @event beginRender
 */
static beginRender;
```

**Comment by kungfooman** [comment]
> It would be nice to be able to document events purely with documentation without having to actually create a property or function on the prototype class which contains them. For example, it would be good to be able to do this:

Yea, you read my mind... why can't we just stick to an old standard here... I've seen many issues about this by now. Is there maybe a typedoc plugin, considering that typedoc maintainers don't want this feature?
