### ISSUE TITLE
Validation function for string declaration options

### ISSUE THREAD

**Issue by krisztianb** [TypeStrong/typedoc#1316]
## Search Terms
plugin string declaration option

## Problem
If a plugin has a string parameter it is pretty common that the provided value of this parameter has to be of a specific form. For example in [this plugin](https://github.com/krisztianb/typedoc-umlclass) there are several options to define a color value in this form `<transparent|#RGBHEX>`.

It would be nice if the plugin didn't have to validate the option values itself. Instead it could define a validation logic when declaring the option and typedoc would do the validation. After all we already have min and max values for number declaration options.

## Suggested Solution
Two solutions spring to my mind for this:

1. Define an optional regular expression with the string declaration option which is used in the convert function to validate the provided value.
2. Define a validation function with the string declaration option which is called by typedoc. The function could return just a boolean or a possible error message.

**Comment by Gerrit0** [comment]
> Define an optional regular expression with the string declaration option which is used in the convert function to validate the provided value.

This won't work very well for users, creating error messages from regular expressions can only really be done for extremely simple cases.

> Define a validation function with the string declaration option which is called by typedoc. The function could return just a boolean or a possible error message.

Returning a boolean isn't very user friendly since we're again stuck with trying to generate an error message "the option {name} doesn't pass validation" isn't useful to users. Returning `string | undefined` would work, but I think it might be better to have the validation function throw an error, following the pattern established by `convert`.

This seems like something that it would be reasonable to want to extend to other option types. Only even numbers, arrays which contain only unique elements...

**Comment by krisztianb** [comment]
Didn't think about the Error throwing solution. Sound like a good idea to me. I can do this as soon as I find some time for it.
