### ISSUE TITLE
`readonly T[]` is exported as `keyof T[]`

### ISSUE THREAD

**Issue by yume-chan** [TypeStrong/typedoc#1336]
## Search terms

readonly, keyof

## Expected Behavior

For the following code:
```ts
export const a: readonly string[] = [];
```

typedoc should export:

```
a: readonly string[] = []
```

## Actual Behavior

typedoc exports:

```
a: keyof string[] = []
```

![image](https://user-images.githubusercontent.com/1330321/86726337-0c5af300-c05d-11ea-9244-d322e487f550.png)

## Environment
- Typedoc version: 0.17.8
- TypeScript version: 3.9.6
- Node.js version: 14.4.0
- OS: macOS 10.15.4

**Comment by Gerrit0** [comment]
This really confused me for a bit because I distinctly remember fixing exactly this bug... and thought I did it ~6 months ago. Turns out it is fixed on the wip library mode branch, but not on master... https://github.com/TypeStrong/typedoc/blob/library-mode/src/lib/converter/type-nodes.ts#L148-L160

It should be fairly simple to update the converter for type operator types on master to handle this properly, PR welcome if you want to give it a shot.

**Comment by yume-chan** [comment]
@Gerrit0 Is there an ETA of the library mode branch? We are testing different documentation generation options, but we don't need it immediately.

**Comment by Gerrit0** [comment]
I wish! The checklist at https://github.com/TypeStrong/typedoc/pull/1184#issuecomment-650809143 is the closest thing I can point you towards there. I seem to be able to do 1-2 medium, or 1 large and 1 small tasks per weekend... which indicates it will be at least a month, probably closer to two.
