### ISSUE TITLE
How can I describe the interface in my code?

### ISSUE THREAD

**Issue by Tiny-Fendy** [TypeStrong/typedoc#1340]
For example:

``` javascript
/**
*
*/
interface Params {
  a: string
}
/**
* @param params
*/
const func = (params: Params) => {}
```
![image](https://user-images.githubusercontent.com/8954107/89185723-48866280-d5cd-11ea-9f2a-b05e8580ccc3.png)

Now, what can I do to show the property in Params on the doc.

**Comment by krisztianb** [comment]
That should be easy:

````typescript
/**
 * Describe Params here.
 */
interface Params {
  /** Describe "a" here. */
  a: string
}
````

As a side note. You should not use an interface here, because `Params` does not seem to be an interface. It only describes properties and not how the thing can be used. Use a type instead:

````typescript
type Params = {
  a: string
}
````

A lot of people make this mistake. You can read more on this [here](https://pawelgrzybek.com/typescript-interface-vs-type/).

**Comment by Gerrit0** [comment]
Something is really weird here. I copied your interface into a brand new project, and ran it with `npx typedoc index.ts`, and I see the property in the docs. Are you using `--excludeNotDocumented`?

![image](https://user-images.githubusercontent.com/19329837/89721921-2bbca700-d9a0-11ea-9c98-ad615f92ee24.png)
