### ISSUE TITLE
Support for rest in objects (...obj)

### ISSUE THREAD

**Issue by deltadex7** [TypeStrong/typedoc#1372]
## Search Terms

ES6, rest object, rest value, syntax, reference

## Problem

I often use ES6 rest values syntax in my code to avoid repeating the same values that are related to an existing object. I have noticed that when I use ES6 rest syntax on an object, TypeDoc (0.19.2) doesn't generate definitions for the object using it. For example, in one of [my repos](/deltadex7/quadfall-node-core), I use this syntax in one of [my files](deltadex7/quadfall-node-core/blob/master/src/uplinkcfg.ts#L92):

```ts
export const PuyoTsuClassicConfig: IUplinkConfig = {
  ...PuyoTsuConfig,
  dumpBehaviorOnHidden: "classic",
}

export const PuyoTsuConfig: IUplinkConfig = {
  rows: 12,
  columns: 6,
  dumpBehaviorOnHidden: "modern",
  /** and so on and so forth */
}
```

The result of the doc generated is this:

![typedoc image](https://user-images.githubusercontent.com/54788149/94885471-d33aef00-04a2-11eb-9b87-d2a6105f7146.png)

## Suggested Solution

My suggestion is to also generate the definitions that was given with rest parameters. For example above, it should also show up the values for `rows` and `columns`. Or at the most least, give a reference of the rest values to the object it referred to.

**Comment by Gerrit0** [comment]
This is probably going to mostly be a wontfix - 0.20's behavior changed, so we no longer rely so much on nodes. The following:

```ts
export const PuyoTsuConfig = {
  rows: 12,
  columns: 6,
  dumpBehaviorOnHidden: "modern",
}
export const PuyoTsuClassicConfig = {
  ...PuyoTsuConfig,
  dumpBehaviorOnHidden: "classic",
}
```

Converts to this in the 0.20 beta - we do have each member, but since properties are converted as properties now, they don't each get their own box.

![image](https://user-images.githubusercontent.com/19329837/100490377-3a0e0a80-30d8-11eb-8a3d-d13cca086a81.png)
