### ISSUE TITLE
All fields missing in type documentations when the types inherit from generic types

### ISSUE THREAD

**Issue by rondonjon** [TypeStrong/typedoc#1377]
## Search terms

Type, Generics

## Expected Behavior

The following type should appear with (at least its own) fields and annotations in the generated documentation.

```
export type A = B<{
  /** foo bar */
  extension: string;
}>;
``` 

## Actual Behavior

No fields in the documentation at all.

**Comment by Gerrit0** [comment]
This is expected behavior. There is no generic way to determine how types should appear in the documentation, and it gets exponentially harder as soon as type aliases are introduced. What if `B` was defined as follows?

```ts
type B<T> = any
// or like this?
type B<T> = keyof T extends keyof {} ? T : never
```

There's no good way to statically analyze types and figure out if someone is trying to define an object type, it is theoretically possible to recognize a *tiny subset* of the possible patterns and support them... but that's the best we can do.

**Comment by rondonjon** [comment]
Hi @Gerrit0,

understood. Nevertheless I am wondering if there might be a pragmatic solution somewhere inbetween “no documentation at all“ and “statically analyze“?

Would it be possible to replicate the type definition just “as is” from the source code, i.e. referring to your example: including this evaluation?

**Comment by Gerrit0** [comment]
> Would it be possible to replicate the type definition just “as is” from the source code, i.e. referring to your example: including this evaluation?

I like this idea! There's no way to do it right now, but it might solve one of the main problems I have with TypeDoc output - mainly that I can get the same information faster by just reading the declaration file.

It would be nice to be able to implement this as a plugin, but the current theme architecture makes that pretty much impossible without the plugin also doing horrible things to make it render...
