### ISSUE TITLE
Optional properties in class constructor are not marked as optional

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [TypeStrong/typedoc#1390]
First off, thank you for building a static documentation generator for typescript! I wonder why Microsoft did not include any…

## Expected Behavior

When running typedocs over a class with optional propperties in the constructor, I'd expect them to be marked as optional

## Actual Behavior

Marked as required

## Steps to reproduce the bug

Given:
```
class MyClass {

  /**
  * @constructor
  * @param foo - some description
  */
  constructor({ foo = 'bar' }: { foo?: string }) {
    ...
  }

}
```

The Typedocs output is

```
# constructor

    new MyClass(__namedParameters: { foo: string }): MyClass

     >   Defined in MyClass.ts:87

## Parameters
        __namedParameters: { foo: string }

           - foo: string

            some description
```

I'd expect it to be marked as optional somewhere. I.e. `- foo?: string`

## Environment

-   Typedoc version: `"typedoc": "^0.19.2",`
-   TypeScript version: `"typescript": "^4.0.5"`

**Comment by Gerrit0** [comment]
Hey, a bug I fixed!... just isn't released yet. Has been fixed in 0.20.0-beta.7, prior versions of TypeDoc incorrectly used `{ foo = 'bar' }` to get the type of the parameter, which results in the behavior you're seeing.

Microsoft did eventually build a documentation generator too, but it falls very heavily into the enterprise realm, more complex than many projects need. https://api-extractor.com/pages/setup/generating_docs/

**Comment by ThibaultJanBeyer** [comment]
Thanks @Gerrit0 for the quick answer. That is great news! Then I guess this particular issue can be closed and I'll wait for 0.20

**Comment by ThibaultJanBeyer** [comment]
Do you have the link to your code changes/pr for reference by any chance @Gerrit0 ? Thank!

**Comment by Gerrit0** [comment]
It was done as a part of 6ff7fcd1d2cc14eeae1f16399e15d8cb7d7f2346, which unfortunately is a rather large commit... the relevant bit for this issue is https://github.com/TypeStrong/typedoc/commit/6ff7fcd1d2cc14eeae1f16399e15d8cb7d7f2346#diff-51535ac984a75610be6795b8314bb457ad5e85562940fcb928e2d64b3a5cf42c
