### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by klevison** [TypeStrong/typedoc#1404]
After update TypeDoc to version `0.20.0-beta.16` I'm facing with a blank page. Can anyone help-me?
![](https://user-images.githubusercontent.com/583230/100410265-f0c4a900-304c-11eb-9805-d0b30c02e168.png)

**Comment by Gerrit0** [comment]
Paths in typedoc are relative to your working directory - I suspect typedoc might have still found your tsconfig because of magic that the compiler does to look for it, but can't say for sure. However, it definitely didn't find index.ts. I thought there was a bug + a fix to warn about that... but I checked the source and it's not there. I just added the check + pushed... CI will publish a new version shortly - 0.20.0-beta.17 that will warn about missing entry points.
