### ISSUE TITLE
Add metadata info to type conversion warnings

### ISSUE THREAD

**Issue by marcofugaro** [TypeStrong/typedoc#1427]
## Search Terms

type conversion, warning, failed to convert type -1

## Problem

While generating the docs, these warnings appear:

<img src="https://user-images.githubusercontent.com/7217420/103285799-5f47ae80-49df-11eb-947a-25a69edebd30.png" width="450" />

I don't know what they're referring to.

## Suggested Solution

It would be more useful to show some context information, for example the source file where that type is present.

--------

PS congrats on the release! 🎉

**Comment by Gerrit0** [comment]
There is enough info there for me to pinpoint the bug :) That one is fixed in 0.20.2 now, releasing shortly.

When typedoc fails to convert a type node, we can (and do) print the file name and line number, but with types there is generally not a specific file/line associated with the issue... I've added a bit more logging, so that it at least prints out the reflection hierarchy that it is converting the type for.

Thanks! Release seems to be pretty good so far, no valid "everything is broken" bugs yet!
