### ISSUE TITLE
Different types when subclassing a template class implementation

### ISSUE THREAD

**Issue by krisztianb** [TypeStrong/typedoc#1441]
## Search terms

template class, type arguments, type parameters, inheritance, extends

## Expected Behavior

Types should be the same in the template class implementation (the super class) and the extending class (the sub class).

## Actual Behavior

Documenting the code below using TypeDoc produces different types for the template class implementation (the super class) and the extending class (the sub class) for the same "unionAB" property.

The difference can be seen in this class diagram generated using the typedoc-umlclass plugin:

![class-diagram](http://www.plantuml.com/plantuml/svg/nP8nJyCm48Nt_8fJfoBQeHrH5BLXHaKq4lCvFeWhnuxi2r94-UzScgJAKCG6dkpl_DuxdxoBZ87RsYQLqGHKDzn1JLnv7UVepP0LKbgC4HQ5G8jC1KMcS6pLOy-t2_XCGDOz8i83kBPM54Po2EgAu0nUdQZaeQPKNvgJrXdlzhdGoC6uTn7SLEOOwUdIxBB1WFLcIbZ1vRoTRE_4wiCRFSYEZ6pAGVXgk2gwXfxx-oIlYUb-1NcsRCHCTeruv5Vvr-q9f5Fga9RzoI1U2BLtjXl3ipaQ-_YtAVqwd_IyNl_yZv8TEIsVyXi0)

Also `Readonly<A | B>` is documented as `Readonly<A> | Readonly<B>`. I'm not sure if this is a bug or intentional behavior.

## Steps to reproduce the bug

Example module:

```typescript
export class TemplateTester<A, B = object> {
    public aaa: A;
    public bbb: B;
    public aOrb: A | B;
    public unionAB: string | A | Readonly<A | B>

    public BaseMethod(param1: A, param2: B): void {}
    public StaticMethodWithTypeParameters<A, B>(p1: A, p2: B): void {}
}

export class TemplateTesterSubClass2 extends TemplateTester<number> {
}
```

## Environment

-   Typedoc version: 0.20.7
-   TypeScript version: 4.1.3
-   Node.js version: 12.13.0
-   OS: Windows 10

**Comment by Gerrit0** [comment]
I think this one has expected behavior - the difference between the sub class and base class is expected since TypeDoc asks TS for the property type, and documents based on that. Tossing this into [a playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgSwPZwIICEA8qA0V0B8UAvFAM7ABOCcA5lAD5SqNQBKEAhgCYoA2IbK0IAoUJCgAFSkjAlYiFBkxwArgFsARhEp4kmgFYQAxsCIB6c+So16TNVp2t9R0yKA) and hovering over `Prop` shows `string | number | object`

```ts
type UnionAB<A, B> = string | A | Readonly<A | B>
type Prop = UnionAB<number, object>
```

The `Readonly<A | B>` change is certainly strange - but again consistent with what TS does. `Readonly` is a homomorphic mapped type, so TS will implicitly distribute the union (TIL...). Hovering over `unionAB` in `TemplateTester` shows the same type as TypeDoc converts... so I'm pretty sure both of these are working as intended.

**Comment by krisztianb** [comment]
Thanks for looking into this. I'm pretty sure that it was not like this when I generated the docs using TypeDoc 0.19.2 but will have a look.

**Comment by Gerrit0** [comment]
I can guarantee it wasn't - in 0.19, instead of using the compiler's checker TypeDoc did its own type parameter replacement. This worked (mostly...) but really shouldn't be the job of the documentation generator, so in 0.20 I made it start using the compiler.

**Comment by krisztianb** [comment]
Ok, so in 0.20 you don't necessarily get the type that you annotated but the one the compiler infers. If this is the intended behavior I'm closing this issue. Thanks for your explanation.
