### ISSUE TITLE
output filename contains folder name.

### ISSUE THREAD

**Issue by ldttmt** [TypeStrong/typedoc#1510]
We are trying to update from typedoc 0.19 to 0.20.x but encountered an issue that the output filename contains the folder name. For example, previously, an output would be docs/classes/fileA.html but now it is docs/classes/_folderB_fileA.html (the path to file A is src/B/A.ts).
Is this a new behavior in 0.20.x? If so, is there option to set it back like before?

**Comment by Gerrit0** [comment]
It sounds like you used to use `"mode": "file"`, with `"inputFiles": ["src"]` and when upgrading just replaced `inputFiles` with `entryPoints`, without specifying the entry point file. This is generally not the ideal use of 0.20+. You should instead give TypeDoc your entry point, and it will document your exports, without nesting everything within modules.

This will result in file names similar to the old ones, since the file names are determined by traversing the hierarchy within the converted project.

**Comment by DeividVeloso** [comment]
@Gerrit0 could you past here the configuration example to keep the behavior like `mode=file` using the new version 0.20, please?

**Comment by Gerrit0** [comment]
That will depend on your project. Assuming you have some library-like project, you'll want something like this:

```json
{
  "inputFiles": ["src/index.ts"]
}
```

If you're generating docs for an application, not a library (why? idk... people do this), then you might need a plugin. [typedoc-plugin-merge-modules](https://www.npmjs.com/package/typedoc-plugin-merge-modules) will get rid of all modules, and place the elements within the project root.
