### ISSUE TITLE
Generic type implementation documentation

### ISSUE THREAD

**Issue by thebestnom** [TypeStrong/typedoc#1513]
## Search Terms

generic

## Problem

Currently if we have a complex generic type that I need to document an instance of I need to create an Interface that extends the implementation 

## Suggested Solution

Auto document the generic implementation (or at least document type)

example
```ts
export interface A {
  a: number
}
export type MapTo<T, New> = {
    [P in keyof T]: New
};
export interface Test1 {
  a: MapTo<A, string> // will not create documentation and will be very hard to read
}

export interface Workaround extends MapTo<A, string> {}  //this will create a full documentation with a: string

export interface Test2 {
  a: Workaround // way easier to read
}

export type SuggestedWorkaround = MapTo<A, string> // not ideal
```

**Comment by Gerrit0** [comment]
This is probably going to be a wontfix. TypeDoc's current behavior correctly emulates TypeScript's intellisense output.

![image](https://user-images.githubusercontent.com/19329837/108611120-965f8e00-7398-11eb-9317-72d3e27bac01.png)

People generally don't like to hear this... but if you want tools to be able to easily analyze your code, writing it so that another developer who is looking at the source code can easily determine what the result is is a good idea.

TypeDoc relies completely on the type checker to determine how to document things - the `SuggestedWorkaround` *might* be possible if we add a special case to the type alias converter for non-generic aliases, but it's still not going to produce results as good as if you wrote the type you wanted in the first place.

**Comment by thebestnom** [comment]
I wish I could, the code generate type from a config from another library (https://github.com/neo4j-contrib/neovis.js/blob/2.0.0/index.d.ts if you are interested 😅) 
the suggested is ok, because all I actually do in the type is to extend it.. (and it going to hurt more on recursive mapped..)

**Comment by thebestnom** [comment]
Also do you think I moght be able to achive this by creating a plugin (without the workaround?)?

**Comment by Gerrit0** [comment]
You could, but it's going to be painful. You'd need to listen to [EVENT_CREATE_DECLARATION](https://typedoc.org/api/classes/converter.html#event_create_declaration), check if the `type` property of the created declaration is set and meets some criteria to be replaced, and then examine the type yourself and create a reflection which documents the values as you need it... would probably end up looking something [like the interface converter](https://github.com/TypeStrong/typedoc/blob/v0.20.26/src/lib/converter/symbols.ts#L437-L509)

**Comment by thebestnom** [comment]
Thank you! 
I still think the workaround should be implemented if you have the time, and if I had time I would still try to make the plugin

**Comment by Gerrit0** [comment]
I'm going to close this in favor of #1519 - I do plan on doing what I outlined there eventually, but it might not happen for a few months... depends on how much free time I have.
