### ISSUE TITLE
Default exports should retain their name

### ISSUE THREAD

**Issue by JasonHK** [TypeStrong/typedoc#1521]
## Search Terms

default exports

## Problem

Currently, the name of default exports will be removed and renamed to `default`, which could cause confusion like the screenshot below.

![2021-02-28_00001](https://user-images.githubusercontent.com/4410086/109409287-8ebd6c00-79cc-11eb-8798-e3b7c717fbe0.png)

The `default` of `payload is default` is NOT the default export of this module.

## Suggested Solution

If the default export is named (like `function named() {...}`, `class Named {...}`, `const named = ...`, etc.), TypeDoc should retain its name  and add a `default` badge to indicate it's a default export. Any types that referencing it should use the original name as well, and not `default`.

**Comment by Gerrit0** [comment]
I am fairly strongly against this - docs should reflect what is actually exported, not what names are used locally to refer to the exports.

However, most people who run into the issue of to many symbols named `default` are giving TypeDoc a directory to document rather than a single entry point. If you use the TypeDoc command I just sent a PR for, I think you'll find that the docs are far more to your liking.

If this still isn't good enough, you *could* do the name change with a plugin.

**Comment by JasonHK** [comment]
> I am fairly strongly against this - docs should reflect what is actually exported, not what names are used locally to refer to the exports.
> 
> However, most people who run into the issue of to many symbols named `default` are giving TypeDoc a directory to document rather than a single entry point. If you use the TypeDoc command I just sent a PR for, I think you'll find that the docs are far more to your liking.
> 
> If this still isn't good enough, you _could_ do the name change with a plugin.

@Gerrit0 What if it's the reverse? Similar to the screenshot below:

![2021-03-02_00005](https://user-images.githubusercontent.com/4410086/109601042-2c45a680-7b59-11eb-8209-f37d85efe30e.png)

**Comment by felipecrs** [comment]
This is more like a bug introduced by the newer versions. Before, the proper field name was used rather than `default`.

Example:

```typescript
export default class SaveImage extends Command 
```

With TypeDoc 0.19:

![image](https://user-images.githubusercontent.com/29582865/110040475-a88ae600-7d21-11eb-939a-f5c41589be7c.png)

With TypeDoc 0.20:

![image](https://user-images.githubusercontent.com/29582865/110040588-d40dd080-7d21-11eb-9f5c-50c907e7648f.png)

**Comment by Gerrit0** [comment]
> @Gerrit0 What if it's the reverse? Similar to the screenshot below:

I guess I'd be *okay* with this... would rather have it be a plugin, but there isn't a good way of doing that right now. It should be possible (and fairly easy) to do with a plugin in 0.22, since that's being planned with extensibility built into the themes.

> This is more like a bug introduced by the newer versions. Before, the proper field name was used rather than default.

Only if you consider a generating documentation that accurately reflects your code to be a bug! 0.19 and earlier included an incredible amount of hackiness in order to get results that produced decent docs... 0.20's approach is far superior once you understand how it works. I think your question in #1526 should help with that.

**Comment by felipecrs** [comment]
So, there is no way to work around it for now, and the best option is to wait for TypeDoc 0.22 and then create a plugin for that?

**Comment by Gerrit0** [comment]
> So, there is no way to work around it for now, and the best option is to wait for TypeDoc 0.22 and then create a plugin for that?

You could create a plugin today - it just won't integrate as cleanly into the architecture. This will rename default exports using their local name, if available, but it doesn't provide any indication that the value was a default export.

```js
// TypeDoc 0.20.x, CC0
const { Converter } = require("typedoc")

exports.load = function({ application }) {
        application.converter.on(Converter.EVENT_CREATE_DECLARATION, (_context, reflection, node) => {
                if (!node || !node.name || reflection.name !== "default") return;

                reflection.name = node.name.getText();
        });
};
```

**Comment by felipecrs** [comment]
@Gerrit0 thank you SO much. It's a plugin now: https://github.com/felipecrs/typedoc-plugin-rename-defaults

**Comment by claviska** [comment]
I found this thread debugging another issue that the plugin doesn't appear to solve. Consider two classes:

```ts
// menu.ts
import { event, EventEmitter } from './decorators';

export default class Menu {
  @event() select: EventEmitter<MenuItem>
}

// menu-item.ts
export default class MenuItem {
  // ...
}
```

The `select` property on `Menu` has no mention of `EventEmitter` in its type arguments. Instead, the name shows up only as `default` and I haven't found a way to solve for that yet. 😕

**Comment by brandonmpetty** [comment]
@Gerrit0 - I don't know the specifics, but the fact that this requires a plugin seems unusual.
Since most of my classes and interfaces are default, it makes the generated docs very painful to look at.
... to the point that this cannot be what anyone would want or expect.  I am attaching a screenshot to highlight that point.

Instead of a plugin that has to be maintained by someone in the community, wouldn't it be better to add an optional parameter to "fix" this?  Ideally it would have the class / interface name like one would expect, but perhaps also display a visible flag / badge / whatever in the documentation that denotes it is technically "default" under the hood.

![image](https://user-images.githubusercontent.com/25997477/128616384-97bebead-3167-42be-80c6-d3ae38999cff.png)

**Comment by Gerrit0** [comment]
You're seeing a bunch of `default` exports because you are giving TypeDoc a directory to document. You probably don't want to do that. TypeDoc's primary use case is generating documentation for libraries, and is meant to be given the library's entry point to document. Even if the library uses default exports primarily internally, the top level of a library will then give those awfully named "default" exports a real name. TypeDoc will follow any re-exports in order to document your API surface.

**Comment by felipecrs** [comment]
BTW, `typedoc-plugin-rename-defaults` v0.2.0 was released with support for TypeDoc 0.21.x.

**Comment by Jax-p** [comment]
> You're seeing a bunch of `default` exports because you are giving TypeDoc a directory to document. You probably don't want to do that. TypeDoc's primary use case is generating documentation for libraries, and is meant to be given the library's entry point to document. Even if the library uses default exports primarily internally, the top level of a library will then give those awfully named "default" exports a real name. TypeDoc will follow any re-exports in order to document your API surface.

Can you explain that, please? If I enter only one file as an entry point, TypeDoc ignores the rest (does not follow imports) and generates documentation only with README.

----

## Example

I have some entry `whatever.ts` file:
```
import MyDocumentedClass from "./core/MyDocumentedClass";
import AnotherDocumentedClass from "./core/AnotherDocumentedClass";
new MyDocumentedClass();
new AnotherDocumentedClass();
```
If I run `npx typedoc whatever.ts` it results into the **empty documentation** which contains only readme content. I didn't follow imports. Didn't documented anything.

If i run `npx typedoc ./core/*.ts` everything is documented (that's fine!) but **everything is `default`**.

----

What am I doing wrong? Why it doesn't follow imports?

**Comment by Gerrit0** [comment]
TypeDoc follows **exports**, because that's what's visible to your users. Imports are an implementation detail. From the outside, there's no difference between these:

```ts
import { actuallyDoIt } from "./helpers"
export function doThings(a, b) {
  return actuallyDoIt(a, b)
}

// ---------

import { actuallyDoIt as someRandomThingToAvoidConflicts } from "./helpers"
export function doThings(a, b) {
  return someRandomThingToAvoidConflicts(a, b)
}
```

**Comment by Simonaester** [comment]
How can I use the plugin in a config file? I'm using docusaurus-plugin-typedoc

**Comment by Gerrit0** [comment]
```json
{
  "plugin": ["path/to/plugin.js"]
}
```

Note: paths in config files are relative to the config file

**Comment by ArnieGA** [comment]
> @Gerrit0 thank you SO MUCH. It's a plugin now: https://github.com/felipecrs/typedoc-plugin-rename-defaults

@felipecrs Thank YOU so much for taking the initiative.
