### ISSUE TITLE
Add an option to drop the .html suffix from links

### ISSUE THREAD

**Issue by thislooksfun** [TypeStrong/typedoc#1533]
## Search Terms

option, html, suffix, extension

## Problem

Currently all the links from one part of the documentation to another use .html extensions. This is great as a default because it will work anywhere, but when publishing it via a service like GitHub Pages the .html extension is redundant.

## Suggested Solution

I suggest adding an option that will drop the .html extension from all the internal links when building the site.

**Comment by Gerrit0** [comment]
This is tricky... right now we don't differentiate between creating urls to write the file, and creating urls to link between pages.

I guess for 0.20 and lower, this could be done with a tweak to the `relativeURL` handlebars helper - https://github.com/TypeStrong/typedoc/blob/1d5d1cb33d460d87fc09f0578ea9f51c60e44990/src/lib/output/plugins/MarkedPlugin.ts#L97-L99

In 0.21, I plan to make a change that will break this... but doing it there isn't horrible either. My first inclination is that I'd like this to be a plugin rather than in TypeDoc proper.

**Comment by thislooksfun** [comment]
Yeah I was thinking it would work well as a plugin except that leaving them in is great for local development since they are required for navigating around when using `file://` and I don't know of a way to selectively enable/disable a plugin.

**Comment by Gerrit0** [comment]
You can use the `--plugin` option to select which plugins are loaded, or even add an option in the plugin itself to disable it

**Comment by thislooksfun** [comment]
...didn't even think of that last option. Yeah that would make sense.

In the interest of future-proofing, what do you plan to change that would cause the use of `relativeURL` to break?

**Comment by Gerrit0** [comment]
I'm dropping handlebars in favor of JSX, so handlebars helpers won't be able to mess with things anymore... I guess doing this later, and just doing a string replace before the files are written to disk would be more future proof, assuming I keep that event (I guess I could... wasn't planning on it initially, but if a published plugin is using it, I'm more likely to keep it working)

I'm going to try to have a initial beta (or at least code pushed for local experimentation) this weekend.

**Comment by Gerrit0** [comment]
> I'm going to try to have a initial beta (or at least code pushed for local experimentation) this weekend.

Looking unlikely. I need to start another status issue... spent entirely too much time trying to fix a bug.
