### ISSUE TITLE
Help with getting started with React / JSX

### ISSUE THREAD

**Issue by osequi** [TypeStrong/typedoc#1539]
Hello everyone,

I would like to create a documentation site with React. The existing themes are not usable because they are built on Handlebars. Instead I need something similar for JSX.

Therefore I've started to use the API. However the first line of code results in lots of errors: 

```ts
// src/index.ts
import { Application } from "typedoc";
```

```bash
tsc src/index.ts && node src/index.js
```

And the result is:

```bash
$ tsc src/index.ts && node src/index.js
node_modules/typedoc/dist/lib/converter/plugins/CategoryPlugin.d.ts:52:51 - error TS2583: Cannot find name 'Set'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2015' or later.

52     static getCategories(reflection: Reflection): Set<string>;
                                                     ~~~

node_modules/typedoc/dist/lib/utils/array.d.ts:35:40 - error TS2304: Cannot find name 'Iterable'.

35 export declare function unique<T>(arr: Iterable<T> | undefined): T[];
                                          ~~~~~~~~

node_modules/typedoc/dist/lib/utils/array.d.ts:48:39 - error TS2304: Cannot find name 'Iterable'.

48 export declare function zip<T extends Iterable<any>[]>(...args: T): Iterable<{
                                         ~~~~~~~~

node_modules/typedoc/dist/lib/utils/array.d.ts:48:69 - error TS2304: Cannot find name 'Iterable'.

48 export declare function zip<T extends Iterable<any>[]>(...args: T): Iterable<{
                                                                       ~~~~~~~~

node_modules/typedoc/dist/lib/utils/array.d.ts:49:34 - error TS2304: Cannot find name 'Iterable'.

49     [K in keyof T]: T[K] extends Iterable<infer U> ? U : T[K];
                                    ~~~~~~~~

node_modules/typedoc/dist/lib/utils/options/declaration.d.ts:172:10 - error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2015' or later.

172     map: Map<string, T> | Record<string | number, T>;
             ~~~


Found 6 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My question is where I can find an example to learn from? I've searched all Github for a non-Handlebars theme without success. I couldn't also found an example for API usage with Typescript.

Any hints are welcome :)
Thank you.

**Comment by osequi** [comment]
Additional note:

Before heading to the API I've started with generating a JSON and parsing it in a arbitrary way, without using the API. This was proven to be a tedious work. Ideally it would be better to parse the JSON with the API, to get a code similar to a theme.

**Comment by Gerrit0** [comment]
> tsc src/index.ts 

When you do this, tsc ignores any config files. This means that it will use a default target and lib which are *old*, like, pre-ES6 old. If you just run `tsc` instead it will pick up your tsconfig. You should target at least ES2018 to work with TypeDoc.

> My question is where I can find an example to learn from?

As far as I know, nobody's done this. The closest example is probably typedoc-plugin-markdown, but the don't render HTML, so it still isn't very close.

> API usage with Typescript

See https://typedoc.org/guides/installation/#node-module for a starter. Completely replacing the renderer will probably require some digging into the source code to understand how it currently works though...

> Ideally it would be better to parse the JSON

Sounds like you want #910, it's on my list to do eventually...

---

Incidentally, one of the things I'm working right now is rebuilding the themes to get rid of handlebars and use JSX instead. I haven't pushed that code yet, partially because I'm still experimenting with tweaks to the themes, and partially because I keep procrastinating on it since I don't really enjoy frontend work...

**Comment by osequi** [comment]
Great news! 

> Incidentally, one of the things I'm working right now is rebuilding the themes to get rid of handlebars and use JSX instead

I guess I'll wait for you to push the JSX themes :)

> See https://typedoc.org/guides/installation/#node-module for a starter.

But this also looks promising. It looks far better than my hand-made JSON parser solution.

> because I keep procrastinating on it since I don't really enjoy frontend work...

I'll get back to you when finishing my current project to see if I can help you out. Perhaps in a few weeks / a month. I love front-end work :D
