### ISSUE TITLE
How to avoid default export to be separately listed from namespace?

### ISSUE THREAD

**Issue by flyon** [TypeStrong/typedoc#1545]
Pretty much all of my files have a single default export of a class.
Therefor I pretty much not need / want the extra "namespace"

It causes a lot of double naming when searching:
![image](https://user-images.githubusercontent.com/341567/111968907-a358d400-8b34-11eb-9ab5-d419b7ea8457.png)

And it creates a lot of empty namespace index files:
![image](https://user-images.githubusercontent.com/341567/111968497-2b8aa980-8b34-11eb-9618-b68fb144ef46.png)

At first there was a lot of mentions of 'default', which wasn't ideal, so I now I'm using `typedoc-plugin-rename-defaults` .. which made things more clear, but now there is the double names.

My question is: Is there any way to remove the namespace so that there is just one "entry" per file for the default exported class?

**Comment by flyon** [comment]
I'm trying to figure out how you're generating the documentation of this library itself. Because besides the default exports, your code setup is very similar, and the end result of the typedoc API is what I'm trying to achieve. `examples` folder however points to outdated comments, and in the source code I don't see any references to what is internal vs external for example. Can you point me to where I can find the typedoc configuration in this repository that generates the typedoc API documentation itself?

**Comment by flyon** [comment]
Ok, to answer my own question. It seems removing default exports and changing everything to normal exports gives me the desired result in the output, and removes the namespaces. It will be quite a rewrite, but I'm open to this being the better solution. 

If you're reading this @Gerrit0 I was your mention somewhere that you fullheartedly support moving away from default exports.

For future readers coming here with similar issues, can you offer any thoughts why you think that's a good idea in general?

**Comment by krisztianb** [comment]
If you google for "why not use default exports" you are going to find some ideas why it is better not to use them. 😉

**Comment by Gerrit0** [comment]
There's a couple things here:

1. Entry point vs namespace vs file based documentation
2. Default vs named exports

The first is more important. TypeDoc before version 0.20 contained two modes, `file` and `modules`. `file` mode was originally intended for legacy JS projects which lived in the global scope while `modules` mode was intended for projects that used namespaces. <sup>1</sup> Recently built TypeScript projects tend to use ES modules, which either of these modes could *kind of* support, but neither did well. The `modules` mode evolved slightly over time to better support ES modules, but never did a really good job of it.

TypeDoc 0.20's goal was to fix this by adding first class support for projects using ES modules. This resulted in switching to what I like to call "entry point" based documentation.<sup>2</sup> In entry point based documentation, the documentation tool creates documentation for your entry point(s), using the names that consumers of your package will import.

Practically, this means that most TypeDoc user's config should contain a single file as the entry point. TypeDoc's documentation is generated with `typedoc src/index.ts`. <sup>3</sup> This is a change from pre-0.20 config files which would have to specify every file that TypeDoc should consider for documentation.<sup>4</sup>

Default exports really only become a problem for documentation when you have multiple entry point, since then you'll end up with a bunch of modules that have exports with the same name. Assuming you have a top level entry point that exports your default exports under the canonical name, and use that to generate documentation, TypeDoc won't care if you used default or named exports.

Outside of documentation, I still don't like default exports. I mostly agree with [Basarat's reasons](https://basarat.gitbook.io/typescript/main-1/defaultisbad), with the addition that the meaning of a default export is different depending on your compiler settings, the compiler settings of whoever is importing your code, and what module type they are running Node with... writing a post about this has been on my list for a while.

**Footnotes:**
<sup>1</sup> It was called `modules` because that's what [TypeScript before 1.5](https://www.typescriptlang.org/docs/handbook/namespaces.html) called them, and most of TypeDoc was written then, though that's slowly changing...
<sup>2</sup> During development, I was calling this "library mode", but I think "entry point" is a better name since it makes it obvious what the documentation tool is meant to do.
<sup>3</sup> Plus some other options that aren't relevant here. The config file used is [here](https://github.com/TypeStrong/typedoc-site/blob/master/typedoc.json), which is used by the GitHub action [here](https://github.com/TypeStrong/typedoc-site/blob/41d9dffede83aa7058559b0229e31c4d2ed430ed/.github/workflows/publish.yml#L30-L40)
<sup>4</sup> I tried to communicate this in the [0.20 release notes](https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0)... but I still get enough questions about it that I must not have done a very good job, or some people just don't read release notes.

**Comment by Gerrit0** [comment]
For your specific issue, and for users who are generating documentation for an application rather than a library, you might want to use [typedoc-plugin-merge-modules](https://www.npmjs.com/package/typedoc-plugin-merge-modules), which will get rid of modules if you have a ton of entry points.
