### ISSUE TITLE
defaultValue: "..."?

### ISSUE THREAD

**Issue by kraftwer1** [TypeStrong/typedoc#1552]
I'm using the JSON feature of TypeDoc.
After upgrading from 0.19.1 to 0.20.33, there are many "..." in the generated JSON.

For example, when running TypeDoc on this code...

```typescript
/**
 * Test
 */
public data: string[] = []
```

...I'm getting this:

```json
{
  "name": "data",
  "defaultValue": "...",
  ...
}
```

## Expected Behavior

In 0.19.1, it used to be correct:

```json
{
  "name": "data",
  "defaultValue": "[]",
  ...
}
```

## EDIT
The `"defaultValue: "..."` also appears in following situations:

```typescript
public foo: () => void = () => ""
```

```typescript
public foo: number = this.bar
// this.bar is another public property of the class (with default of 1).
// TypeDoc 0.19.1 wrote "this.bar" as a hardcoded string, but 1 as number is correct IMHO.
```

## Environment

-   Typedoc version: 0.20.33
-   TypeScript version: 4.0.2
-   Node.js version: 14.11.0
-   OS: macOS Catalina

**Comment by Gerrit0** [comment]
This is expected behavior - TypeDoc will only display initializers if it deems them simple enough to not cause catastrophically bad behavior. See #1288 for an example. Also see #1393 for an example plugin which overrides this behavior for object literals, and can be easily extended for other initializer types.
