### ISSUE TITLE
Bring back --includeDeclarations

### ISSUE THREAD

**Issue by dada513** [TypeStrong/typedoc#1558]
## Search Terms

includeDeclarations, declaration files

## Problem

version v20.0.0 has removed the --includeDeclarations option.
This removed the ability of generating doc of a javascript project that has d.ts files

## Suggested Solution

-

**Comment by Gerrit0** [comment]
TypeDoc can document declaration files - as long as they are included in your TypeScript project setup. What does your setup look like that you're having issues documenting? --includeDeclarations is no longer necessary, because TypeDoc no longer does filtering based on if the file is a declaration file or not.

**Comment by dada513** [comment]
> TypeDoc can document declaration files - as long as they are included in your TypeScript project setup. What does your setup look like that you're having issues documenting? --includeDeclarations is no longer necessary, because TypeDoc no longer does filtering based on if the file is a declaration file or not.

My current project is pure JS (no typescript) with manually made type definitions. Before I was able to make a type doc out of it

**Comment by Gerrit0** [comment]
And you should be able to now, so long as you have a tsconfig/jsconfig that specifies your source files.

**Comment by dada513** [comment]
I'll try that
