### ISSUE TITLE
class export is called export=

### ISSUE THREAD

**Issue by bwbjustin** [TypeStrong/typedoc#1572]
## Search terms
export, export=

## Expected Behavior
The class would be correctly named (In this case, `Licenses`)

## Actual Behavior
The class is called `export=`

## Steps to reproduce the bug
https://github.com/bwbjustin/bwbjustin.github.io
https://github.com/bwbjustin/github-licenses

## Environment

-   Typedoc version: 0.20.35
-   TypeScript version: 4.2.4
-   Node.js version: 14.16.0
-   OS: Windows 10

**Comment by bwbjustin** [comment]
How is this not a bug? What behavior causes this?

**Comment by Gerrit0** [comment]
(I was looking for a canonical issue, but apparently don't really have one...)

This is expected behavior. `export = Licenses` does not create an export named `Licenses`, `export class Licenses` would, or `export { Licenses }` would. `export =` creates a module whose export is the value.

If I read docs for a modern library and see that `Licenses` is exported, then I expect to do `import { Licenses } from "github-licenses"`.

I provided an [example plugin](https://github.com/TypeStrong/typedoc/issues/1521#issuecomment-791971444) for renaming default exports, I suspect something very similar could be done here.

---

Sidenote: Why is this a class? It's all static methods... Why not just export a bunch of functions using ES module exports?

**Comment by bwbjustin** [comment]
Ok, on that.

**Comment by felipecrs** [comment]
This is now handled by version 0.3.0 of `typedoc-plugin-rename-defaults` thanks to @bwbjustin.
