### ISSUE TITLE
How do you document events?

### ISSUE THREAD

**Issue by photonstorm** [TypeStrong/typedoc#1573]
Using 0.20.35 currently and wondering how to document events? Both the event itself and the fact that a method fires them.

In JSDoc I can use `@fires EventName` to indicate an event is fired by a function. This tag isn't ignored by TypeDoc, but it isn't supported fully either and no matter what I put after it, it just renders as plain text (instead of a link to the event).

I noticed there is an `@event` tag in TypeDoc, but I cannot see how you'd use it to describe the actual event properties. I tried creating a `typedef` specifically for the event:

```js
     * @typedef {object} ProgressEvent - Progress Event.
     * @property {string} paymentPointer - Your payment account URL. The same value is used as the content in your <meta> tag.
     * @property {string} requestId - This value is identical to the session ID/monetization ID (UUID v4) generated by the user agent (see Flow).
     * @property {string} amount - The destination amount received as specified in the Interledger protocol (ILP) packet.
     * @property {string} assetCode - The code (typically three characters) identifying the amount's unit. A unit, for example, could be a currency (USD, XRP).
     * @property {number} assetScale - The number of places past the decimal for the amount. For example, if you have USD with an asset scale of two, then the minimum divisible unit is cents.
     * @property {string} receipt - base64-encoded STREAM receipt issued by the Web Monetization receiver to the Web Monetization provider as proof of the total amount received in the stream.
     * @property {number} totalAmount - the sum of what has been received with the current paymentPointer, if the paymentPointer is changed this amount will be reset
```

But then how would you link that to the `@event` tag? I've tried all combinations I can think of, but it renders something like this (with all the types lost):

![image](https://user-images.githubusercontent.com/164476/115262099-223d2e80-a12c-11eb-8ceb-1cf54a21c895.png)

I've also tried using an Interface, but again I cannot see how to link this to the event itself.

Any help would be appreciated!

**Comment by Gerrit0** [comment]
The only thing that the `@event` tag does today is change the `kind` property in the reflection so that the icon changes to the lightning bolt and those properties show up under another heading... which is admittedly not very useful.

The way to create links is with the `@link` tag, like you did, but there's an important consideration. TypeDoc can only link to the specified interface if it is also exported and therefore included in the documentation. I suspect that's why your link isn't working.

The `@property` and `@typedef` tags are only supported if documenting JS files, if you are writing TypeScript, an interface is the way to go.

**Comment by sedghi** [comment]
I'm also looking for ways to indicate the event that is actually fired by the function. Is there any update on this from last year? can't we just have @fire like JSDOC?

**Comment by fire** [comment]
Hi.
