### ISSUE TITLE
Include not exported

### ISSUE THREAD

**Issue by euberdeveloper** [TypeStrong/typedoc#1577]
## Search Terms

include-not-exported

## Problem

I have a libray such as this: https://github.com/euberdeveloper/byteify

I have two docs sites:
- The first is for users of the lib: https://byteify.euber.dev
- The second for who maintains it, so everything, not exported things, should be included in this site https://byteify-dev.euber.dev/

You can see that in the root folder I am using two different typdoc config files, one for the lib version and the other for the dev.

If you look at this file: https://github.com/euberdeveloper/byteify/blob/main/source/modules/deserialize.ts
There is a function `deserializeInteger` that is not present in the Dev documentation, while I want it to be.

## Suggested Solution

Add an option `includeNotExported`

**Comment by Gerrit0** [comment]
This isn't something I'm going to include in TypeDoc. It can be done with a plugin - typedoc-plugin-not-exported has one method of doing it, which limits it somewhat. You could easily modify it to do everything.

**Comment by euberdeveloper** [comment]
Ok thank you, I'll try it. Can I ask you why you will not include this functionality?

**Comment by Gerrit0** [comment]
I don't want to include this in TypeDoc because I think it goes against what documentation should do. Docs are meant for users of some library/application to know what functions are available to them. Items which aren't exported are... not available. A developer who is working on that file will have that file open, and so will already know what is available to them in that narrow context.
