### ISSUE TITLE
How to generate docs for extend modules?

### ISSUE THREAD

**Issue by TheFBplus** [TypeStrong/typedoc#1590]
I am writing a project to extend third-party packages like this:
```ts
declare module 'thirdPartyModule' {
    export interface thirdPartyClass {
             extendFunction():void;
    }
}
```
By this way I can extend the thirdPartyClass in thirdPartyModule.
I want to render my extendFunction,how can I achieve that?

**Comment by krisztianb** [comment]
What have you tried so far? What problems are you facing?

I haven't tried to document a project that does this with TypeDoc yet. But it would make sense not to include this in the generated documentation of TypeDoc, since that export is not part of what is exposed to the end user through your module. It's just an extension of another module you are using.

**Comment by TheFBplus** [comment]
@krisztianb Oh,I see...so the typedoc is not meant to do that?there is a situation that I only want to generate my extend functions,how can I achieve that?
I tried to solve this problem by exposing the interface and write like this:
```ts
export interface IThirdPartyClass {
    extendFunction():void;
}

declare module 'thirdPartyModule' {
    export interface thirdPartyClass extends IThirdPartyClass{}
}
```
And the typedoc can generate the interface correctlly.I don't know if there is any better solution?

**Comment by krisztianb** [comment]
Everything you want to have documented needs to be exported from one of your entry points. So if you want the types of another module clickable you will need to add an aditional entry point to the file that exports those types.
