### ISSUE TITLE
Can't get `--exclude` to work

### ISSUE THREAD

**Issue by paxperscientiam** [TypeStrong/typedoc#1592]
Hello,

I've tried several incantations, but I simply can't get the the `--exclude` option to work on the commandline or using the node API.

I have source folder `'./src'` with certain child folders that I'd like to ignore.

So, I've tried the following:
* `typedoc --includes './src' --exclude 'src/stylesheet/__tests__' --entryPoints src/core/fusebox.ts`
* `typedoc --out docs src --exclude **/*__*/** --exclude **/*.test.tsx`
* `typedoc --exclude "**/__tests__/**" ./src`
* `typedoc --exclude "**/__tests__/**" ./src/core/fusebox.ts`

None of these ignore the the \_\_tests\_\_ directories. What am I doing wrong?

Thanks.

**Comment by Gerrit0** [comment]
When you say "ignore" what do you mean exactly? Are you re-exporting stuff in __tests__ from src/core/fusebox.ts?

In 0.20, exclude only filters entry points, so it will only do something in your second and third examples. In 0.21, this is changing so that it also filters values that are re-exported but originate in an excluded file.

**Comment by paxperscientiam** [comment]
Hi, thanks for responding. I'm running into issues with typedoc because it's trying to analyze directories that I don't want it to (EG test code). Perhaps it would be ideal for that code not to be under /src, but I don't have control of that. At any rate, there is plenty of old code in "/src/__tests__" that conflicts with the current incarnation of the repo.

The repo i'm working on is [fuse-box/fuse-box](https://github.com/fuse-box/fuse-box/tree/f68623538837d5801c11bc56a40fba7820dfac46/src)

The previous link points to the /src folder. I need to somehow get typedoc to ignore analyze "/src/__tests__" and "/src/integrations".

EG:
![Screen Shot 2021-06-03 at 6 15 34 PM](https://user-images.githubusercontent.com/7539871/120718696-b32b5780-c497-11eb-94ac-b882d9d25024.png)

**Comment by Gerrit0** [comment]
Ah, so it's not that TypeDoc isn't not documenting those files, but that compiler errors in them are preventing docs from building.

This is expected behavior. If there are type errors, then TS doesn't always conform to its published API contracts, resulting in crashes. To fix it, you should use the [`exclude`](https://www.typescriptlang.org/tsconfig#exclude) option for TypeScript to exclude those files from compilation. You can either do this in your standard tsconfig, or create a tsconfig for TypeDoc and that excludes those files and use that instead.

**Comment by paxperscientiam** [comment]
Perfect, that works. I wound up going with a secondary tsconfig file that expands on the base on.
```JSON
{
  "extends": "./tsconfig",
  "exclude": [
    "node_modules",
    "src/**/__tests__",
    "src/compiler/playground",
    "playground",
    "dist"
  ],
  "typedocOptions": {
    "entryPoints": [
      "src/index.ts"
    ],
    "out": "docs/api"
  }
}
```

Thank you.
