### ISSUE TITLE
Comparison between api-extractor, react-docgen-typescript

### ISSUE THREAD

**Issue by tony** [TypeStrong/typedoc#1595]
Both of these look like good projects, have you considered collaborating together / joining forces? Any philosophical differences? Overlapping?

https://api-extractor.com/

https://github.com/styleguidist/react-docgen-typescript

**Comment by Gerrit0** [comment]
TypeDoc is somewhat different from both of these, we have worked with the API Extractor team somewhat via the TSDoc repo - <https://github.com/microsoft/tsdoc>.

API Extractor is more than just documentation. It also tries to help developers be better about what they export. The main philosophy difference between it and TypeDoc is that TypeDoc tries to do just one job - documentation. API Extractor can do more than one job since it has the benefit of having a team of people at Microsoft supporting it, where TypeDoc is a hobby project.

I've never heard of react-docgen-typescript. It looks kind of similar to TypeDoc, but far more focused on react projects, where TypeDoc tries to be a more general purpose tool.
