### ISSUE TITLE
Including unit test code in the documentation of an entity

### ISSUE THREAD

**Issue by rauschma** [TypeStrong/typedoc#1638]
## Problem

When documenting, e.g., a function, it’s useful to include examples. These examples often already exist elsewhere: in unit tests. It would be nice if TypeDoc could extract such code and show it in the documentation.

## Suggested Solution

File `my-proj/ts/test/usage_test.ts` (for `mocha --ui qunit`):

```ts
import * as assert from 'assert/strict';
import { map, toArray } from '../src/functions.js';

test('Using map()', () => {
  assert.deepEqual(
    toArray(map(x => x + x, ['a', 'b', 'c'])),
    ['aa', 'bb', 'cc']
  );
});
```

The doc comment would be (optional: quoting the file path):

```ts
/**
 * @unit_test_code ts/test/usage_test.ts 'Using map()'
 */
function* map<T, U>(mapperFn: (x: T) => U, iterable: Iterable<T>): Iterable<U> {
  for (const x of iterable) {
    yield mapperFn(x);
  }
}
```

(There are probably better names that `@unit_test_code`.)

In the documentation for `map()`, we’d see the following example code:

```ts
assert.deepEqual(
  toArray(map(x => x + x, ['a', 'b', 'c'])),
  ['aa', 'bb', 'cc']
);
```

**Comment by Gerrit0** [comment]
I think this is an ideal use case for a plugin - test frameworks vary wildly, doing this in a generic way would be overly complex.

**Comment by Gerrit0** [comment]
I spent an hour and a half looking at actually implementing this today... at least for one test framework... and was really surprised that apparently *nobody* thinks that listing all available tests is an important feature. Jest is the closest I found, but it's `--listTests` option just prints out test files, it doesn't list the actual tests.

This, unfortunately, means that implementing this feature is going to require doing a lot of string matching, which isn't really something I'm interested in building, so I'm going to close this issue. If someone creates this, please feel free to leave a comment so that others can find your plugin!
