### ISSUE TITLE
Template repository for new theme development

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/typedoc#1642]
## Search Terms

theme

## Problem

Creating a new theme might be unnecessarily intimidating

## Suggested Solution

Create a github template repository to assist in creating new themes
Can contain the necessary theme subclasses, an assets folder with some sample CSS augments, etc
Can also be preconfigured for theme testing via #1640 

npm can install directly from git, so if someone wants their own theme, all they need to do is:
copy the template repo using github's UI
customize
`npm install` from their github repo and configure typedoc

**Comment by Gerrit0** [comment]
This isn't going to quite be a 0.22 thing. I still want to do it, but want to wait until I'm completely happy with the rendering API, and that's not quite there yet. In order to get there, I need to make it much easier to override simple things, or inject some markup, without writing a bunch of code...

**Comment by Gerrit0** [comment]
I guess I never left a comment here, this exists now. https://github.com/Gerrit0/typedoc-custom-theme-demo
