### ISSUE TITLE
New errors and warning after upgrading to 022.2

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#1685]
## Search terms

0.22.2 errors warnings 

## Question

After upgrading for 0.21 to 0.22.2, I got the error `Error: Unable to find any entry points. Make sure TypeDoc can find your tsconfig` when trying the generate my documentation using the following configuration file:

```json
{
	"entryPoints": [
		"./src/components",
		"./src/data",
		"./src/framework"
	],
	"out": "doc",
	"exclude": [
		"**/*.js",
		"node_modules"
	],
	"excludeExternals": true,
	"hideGenerator": true
}
```

II've read the change log but did not find any breaking change that should affect me, but after playing around with the configuration options, I discovered that adding the option `"entryPointStrategy": "expand"` resolves the error but now generates a ton of warnings like the following:

```bash
Warning: PlainObjectType, defined at src/global_types/plainobjecttype.d.ts:1, is referenced by components/las_mod_positions/form.formDataType but not included in the documentation.
...
```

I'm quite sure I've missed something and would love to get some help in understanding what I'm doing wrong.
My setup is quite simple: 
- all TypeScript sources are in the `./src` directory
- the sources in `./src/components`, `./src/data` and `./src/framework` are the reusable modules that should be documented
- the remaining sources in `./src` are the application modules that do not need to be documented

Thank you!

**Comment by Gerrit0** [comment]
> I've read the change log but did not find any breaking change that should affect me, but after playing around with the configuration options, 

Oops! I completely forgot to include a note on that in the breaking changes section, updated the release now to point it out. Thanks!

> Warning: PlainObjectType, defined at src/global_types/plainobjecttype.d.ts:1, is referenced by components/las_mod_positions/form.formDataType but not included in the documentation.

This warning is letting you know that you do something like this:

```ts
// plainobjectype.d.ts
type PlainObjectType = Record<string, unknown>

// components/las_mod_positions.ts
export interface form {
  formDataType: PlainObjectType
}
```

This will work, TypeDoc will still generate documentation for `form`, but the documentation will only contain the name `PlainObjectType`, not a link to the full documentation for it. Since the documentation is incomplete, TypeDoc warns about it.

Since this may be intentional, there is a new option, `intentionallyNotExported` to suppress warnings on a case by case basis. Given that you said you have a lot of these, I should probably look at including a flag to suppress all of these warnings at once...

https://github.com/TypeStrong/typedoc/blob/1e25a737f9b21148fb7863a5f526dee498444e75/.config/typedoc.json#L1-L11

**Comment by doberkofler** [comment]
Thank you for your quick feedback. The new configuration settings are very helpful but a lot of warnings seem not to be caused by not included sources but rather look like a false positive. I create a new #1687 to keep thinks separated.
