### ISSUE TITLE
XXXX, defined at XXXXX.ts:5, is referenced by XXX but not included in the documentation.

### ISSUE THREAD

**Issue by thib3113** [TypeStrong/typedoc#1694]
## Search terms

"XXXX, defined at XXXXX.ts:5, is referenced by XXX but not included in the documentation."

## Question

I have the warning : 
```
Warning: IController, defined at src\IController.ts:5, is referenced by Controller but not included in the documentation.
```
The file Controller is here : https://github.com/thib3113/unifi-client/blob/main/src/Controller.ts 

And I doesn't understand why ... 
The interface is correctly exported (not default), correctly imported in Controller ... And finally seems to be included in documentation : https://thib3113.github.io/unifi-client/interfaces/IController.html . ( the documentation page of the Controller : https://thib3113.github.io/unifi-client/classes/Controller.html ) .

**Comment by Gerrit0** [comment]
I fully thought this was a bug for a few minutes!

You do have an export called `IController`, but it isn't the `IController` which `Controller` implements.

The `IController` that is documented is defined at [src/WebSockets/Interfaces.ts:104](https://github.com/thib3113/unifi-client/blob/b871d4a/src/WebSockets/Interfaces.ts#L104)
The `IController` that the `Controller` class is referencing is defined at [src/IController.ts:6](https://github.com/thib3113/unifi-client/blob/b871d4a/src/IController.ts#L6)

I'm not sure what the proper fix for this one is going to be for your library, if you export the `IController` from `src/IController`, then you'll get a different warning due to [`ISystemEvent.apps`](https://thib3113.github.io/unifi-client/interfaces/ISystemEvent.html#apps), which references the other IController

**Comment by thib3113** [comment]
ohhhhh .... I'm sorry for this ... 

I search for a long time without understanding ... Thank you .

For the solution, I've my idea :)

**Comment by carltian** [comment]
> ohhhhh .... I'm sorry for this ...
> 
> I search for a long time without understanding ... Thank you .
> 
> For the solution, I've my idea :)

hi, i have the same problem now, how do u solve it ? thanks

**Comment by carltian** [comment]
did u use implements to solve it ?

**Comment by thib3113** [comment]
@carltian in my case, I have two interfaces with the same name, and only one is exported at the root level ... So I rename one of the two, and export the two ...
