### ISSUE TITLE
regression: broken support for custom themes

### ISSUE THREAD

**Issue by vladmandic** [TypeStrong/typedoc#1701]
typedoc version: `typedoc` 0.22.3  
other versions: `typescript` 4.4.3 with `node` 16.5.0 on `ubuntu` 21.04 inside `wsl2` on `windows 11`

`typedoc --theme custom test.js`

throws error:

```text
Error: The theme 'custom' is not defined. The available themes are: default
Error: Documentation could not be generated due to the errors above.
```

same when  using `typedoc` via api and setting `td.options.theme` (which is a type: string, so not much else to do there)

this used to work before latest update

**Comment by Gerrit0** [comment]
> HTML output is now rendered with JSX instead of Handlebars, closes #1631.
This change provides major performance benefits, reducing rendering time by up to 10x for several benchmarked projects.
It also allows themes to be easily type checked, preventing mistakes when creating custom themes.
Removing Handlebars also fixed memory leaks when --watch was specified due to Handlebar's caching mechanism.
This change breaks all existing custom themes, so a theme created for v0.21 or earlier will not work in v0.22.
See internal-docs/custom-themes.md for documentation on how to create a custom theme in v0.22.

https://github.com/TypeStrong/typedoc/releases/tag/v0.22.0

**Comment by vladmandic** [comment]
that's fair - but cli output should be noting that input param is not pointing to a valid theme

**Comment by Gerrit0** [comment]
> Error: The theme 'custom' is not defined. The available themes are: default

It does, you even included it in your original post!

**Comment by vladmandic** [comment]
this is anything but clear

> Error: The theme 'custom' is not defined

but ok, closing as by-design
