### ISSUE TITLE
Set dark mode by default

### ISSUE THREAD

**Issue by issadarkthing** [TypeStrong/typedoc#1707]
## Search Terms
Theme

## Problem
Force default theme color instead of using os preferences. Sometimes os preference does not work well on linux and it will show light mode by default. Also, if user changed to dark mode on the index page, the every other pages does not get affected.

**Comment by Gerrit0** [comment]
> Sometimes os preference does not work well on linux

This sounds like a problem with your browser. Websites are supposed to be platform agnostic... if we can't rely on browsers to do the right thing, then we have to guess... and there will always be some people who are upset that the guess wasn't what they wanted. On Firefox, you can set dark mode as your preference explicitly so that you don't rely on the OS: https://stackoverflow.com/a/56757527/7186598

> Also, if user changed to dark mode on the index page, the every other pages does not get affected.

This would be a bug, but I can't seem to reproduce it, at least for real websites. If you're opening up the documentation with `file://`, then Firefox at least will treat each new directory as a new "site" and there is no way to save the theme across other pages. See https://bugzilla.mozilla.org/show_bug.cgi?id=507361 for discussion.

If you start a local server for browsing docs rather than relying on `file://`, localStorage will be saved as expected, `npx http-server ./docs`

**Comment by issadarkthing** [comment]
> If you start a local server for browsing docs rather than relying on file://, localStorage will be saved as expected, npx http-server ./docs

Yeah, I tried running on server and it does work. Thank you for taking your time to look into this issue. Have a nice day :)
