### ISSUE TITLE
TypeDoc not respecting entryPoints, inspects all files

### ISSUE THREAD

**Issue by pat-son** [TypeStrong/typedoc#1708]
I have a project with a React component package and a documentation app to demo those components. The documentation app depends on the component package, but the component package does not depend on the documentation app.

I want to use TypeDoc to generate documentation for just the React components, so I used the `entryPoints` option with only the path to the index file of the react library.

## Expected Behavior

I expected TypeDoc to only look at the React code

## Actual Behavior

TypeDoc looks at all the code, including the documentation app code

## Steps to reproduce the bug

I'm using lerna to manage the monorepo, not sure if that's somehow involved.

## Environment

-   Typedoc version: 0.22.4
-   TypeScript version: 4.0.7
-   Node.js version: 14.17.6
-   OS: Windows 10

**Comment by Gerrit0** [comment]
Usually when someone reports something like this it's because they have compiler errors that they think TypeDoc shouldn't see because of entry points - that's not how entry points works.

TypeDoc works by loading your tsconfig, then calling out to TypeScript to create a program with all of the same information that `tsc` has. Thus, if `tsc --noEmit` reports an error, so will TypeDoc. If you want to limit what TypeDoc sees, you can create a tsconfig which just includes those files and point TypeDoc to use that with `--tsconfig`. If TypeDoc still sees files you don't expect, you can debug why those files are being included by running `tsc --project tsconfig.typedoc.json --explainFiles`
