### ISSUE TITLE
@typeParam is broken for type aliases

### ISSUE THREAD

**Issue by nex3** [TypeStrong/typedoc#1733]
## Expected Behavior

I would expect to be able to document a type parameter on a type alias like so:

```ts
/**
 * @typeParam A Some documentation.
 */
export type Foo<A> = A;
```

## Actual Behavior

The documentation shows up in a tagged section rather than under the type parameter:

![image](https://user-images.githubusercontent.com/188/136473932-c9a3e02d-a4ab-412c-8ded-f08363c0f210.png)

## Steps to reproduce the bug

Just run `npx typedoc test.ts` on the above code.

## Environment

-   Typedoc version: 0.22.4
-   TypeScript version: 4.3.5
-   Node.js version: 16.10.0
-   OS: Linux

**Comment by Gerrit0** [comment]
Aww shoot, I broke this nearly 2 years ago now, you're the first to notice. The root cause of this is TypeDoc not treating comments as a first-class citizen where they are created when a reflection is created... instead doing it on a "created" event. This works most of the time, but not in this case, because the reflection was finalized (which is when comments are attached) after type parameters were created, but the `@typeParam` handling expects the comment to be there  when the type parameter is created.

The right solution to this is to do comments on reflection construction (actually, before, but even that would be an improvement. I plan to do this with 0.23), but for now a fix is just to swap the order of finalization and type parameter construction.
