### ISSUE TITLE
Any guidance on how to use TypeDoc to document React components?

### ISSUE THREAD

**Issue by pat-son** [TypeStrong/typedoc#1735]
## Question

Is there an option or plugin to make output for documenting React components more attractive? Right now, TypeDoc just recognizes them as Functions that return an Element, and it doesn't handle the props as well as I'd like. Components that use higher-order components are even harder to parse.

We had explored using react-docgen for this, but it doesn't work with props that are interfaces, and would rather just use TypeDoc since it can handle our interfaces and non-component functions as well.

**Comment by pat-son** [comment]
He's a more specific example of the issue I have with what happens by default:

Here's a dummy component that uses MobX's `Observer` HOC:

```tsx
import React from 'react';
import { observer } from "mobx-react-lite";

export interface ObserverProps {
    /**
     * Item to observe
     */
    item: any;
}

/**
 * This is a component that observes.
 */
export const Observer = observer(({ item }: ObserverProps) => {
    return (
        <div>
            {item.test}
        </div>
    );
});
```

and here's the resulting JSON for the component:

```json
{
	"id": 16,
	"name": "Observer",
	"kind": 32,
	"kindString": "Variable",
	"flags": {},
	"comment": {
		"shortText": "This is a component that observes.",
		"tags": [
			{
				"tag": "component",
				"text": "\n"
			}
		]
	},
	"sources": [
		{
			"fileName": "src/observer.tsx",
			"line": 16,
			"character": 13
		}
	],
	"type": {
		"type": "intersection",
		"types": [
			{
				"type": "reflection",
				"declaration": {
					"id": 17,
					"name": "__type",
					"kind": 65536,
					"kindString": "Type literal",
					"flags": {},
					"signatures": [
						{
							"id": 18,
							"name": "__type",
							"kind": 4096,
							"kindString": "Call signature",
							"flags": {},
							"parameters": [
								{
									"id": 19,
									"name": "__namedParameters",
									"kind": 32768,
									"kindString": "Parameter",
									"flags": {},
									"type": {
										"type": "reference",
										"id": 14,
										"name": "ObserverProps"
									}
								}
							],
							"type": {
								"type": "reference",
								"name": "Element"
							}
						}
					]
				}
			},
			{
				"type": "reflection",
				"declaration": {
					"id": 20,
					"name": "__type",
					"kind": 65536,
					"kindString": "Type literal",
					"flags": {},
					"children": [
						{
							"id": 21,
							"name": "displayName",
							"kind": 1024,
							"kindString": "Property",
							"flags": {
								"isExternal": true
							},
							"sources": [
								{
									"fileName": "node_modules/mobx-react-lite/dist/observer.d.ts",
									"line": 12,
									"character": 4
								}
							],
							"type": {
								"type": "intrinsic",
								"name": "string"
							}
						}
					],
					"groups": [
						{
							"title": "Properties",
							"kind": 1024,
							"children": [
								21
							]
						}
					]
				}
			}
		]
	},
	"defaultValue": "..."
},
```

And here's what the HTML ends up looking like:

![image](https://user-images.githubusercontent.com/8462638/137025084-5967f34a-8a6b-4636-826e-8c52a56461c1.png)

Basically, is there a plugin that can show a prop table inline for a component, and better recognize components as Components, instead of Functions and Variables?

**Comment by Gerrit0** [comment]
I'm not aware of any plugins which do the kind of thing you're looking for.... I thought I vaguely remembered one, but failed to find it, maybe it was so many versions ago that it's totally dead now. TypeDoc looks considerably different internally today than it did a year ago.

Your `Observer` component doesn't show up as a function because of the extra property (`& { displayName: string }`), there's currently no way to override this and tell TypeDoc to ignore it...  but I'm not necessarily opposed to adding a `@function` tag that does this.... 

Whether or not to inline interface documentation is something that's come up a few times, and I've yet to find a good answer for it. If I write `function foo(x: HTMLElement)`, I certainly don't want all 50+ properties spelled out there.... I guess adding a `@inline` tag (on the interface? the function?) could allow this, but it really feels inelegant.

Components *are* functions. If you want to display them separately from other functions, you can use the `@category` tag ([docs](https://typedoc.org/guides/doccomments/#%40category))
