### ISSUE TITLE
[Regression] Documentation for destructured object properties is not picked up.

### ISSUE THREAD

**Issue by canonic-epicure** [TypeStrong/typedoc#1770]
## Search terms

object destructuring, object properties

## Description

This used to work in 0.17, but now it does not. For this setup, where the `Sym1` and `Sym2` a descructured properties of the object, the docs for them are not "picked up"
```
const api = () : {
    Sym1 : () => number,
    Sym2 : () => boolean
} => {
    return null
}

/**
 * Important constant
 */
export const {
    /**
     * Docs for Sym1
     */
    Sym1,

    /**
     * Docs for Sym2
     */
    Sym2
} = api()
```
Result is: ![image](https://user-images.githubusercontent.com/72431/139453948-d9d2a413-f3de-419c-81f9-265c07f6492f.png)

And if you run the command line as: `npx typedoc index.ts --excludeNotDocumented`, the result is empty:
![image](https://user-images.githubusercontent.com/72431/139454268-ea5634af-ed1b-4ac0-8771-fc37e15d9340.png)

## Reproduce
To reproduce:

* Clone this repo: https://github.com/canonic-epicure/typedoc-repro-1756
* npm i && npx typedoc index.ts --out docs
* Check the content of the docs/index.html

**Comment by Gerrit0** [comment]
I think I'm going to punt this one to 0.23 as well, since fixing it without making a significant breaking API change involves a ridiculous amount of hackery. There's a couple additional problems here, with the one making this immediately difficult to fix being that TypeDoc's checks for "has a comment" isn't consistent with whether or not TypeDoc will actually find a comment.

**Comment by canonic-epicure** [comment]
Ok, cool, no rush, since its possible to workaround this one.  It worked in 0.17, I guess need to check what approach was used there.

**Comment by canonic-epicure** [comment]
I see. Worth pining with a test.
