### ISSUE TITLE
Class member null type is not included

### ISSUE THREAD

**Issue by truonguyen1** [TypeStrong/typedoc#1781]
## Search terms

Null type

## Expected Behavior

class member's null type should be generated in the doc. 

## Actual Behavior

Class member's null type is not generated.
![image](https://user-images.githubusercontent.com/4377694/140339539-2647def6-63a6-43f2-aba6-1613ccc558c9.png)
![image](https://user-images.githubusercontent.com/4377694/140339701-8f331791-9b92-4c60-ac53-d045b859d392.png)

It works fine for non class member
![image](https://user-images.githubusercontent.com/4377694/140341486-8abcd775-f023-4071-ad4c-b2c34f4f0f66.png)
![image](https://user-images.githubusercontent.com/4377694/140342031-0eee1d6f-f55e-407e-b375-207aca8970a0.png)

## Environment

-   Typedoc version: 0.22.7
-   TypeScript version: 4.4.4
-   Node.js version:
-   OS:

**Comment by Gerrit0** [comment]
In your tsconfig.json, you have `strictNullChecks` either set to `false`, or not set at all. When this option is set, TypeScript treats all `X | null | undefined` as equivalent to `X`, and so does TypeDoc, in most places because to get the type of variables, it asks the compiler what the type is.

Type aliases do not (currently...) get this treatment because it results in more intuitive documentation in many cases, for example:

```ts
type Foo = `a${"b" | "c" | "d" | "e"}${"f" | "g" | "h" | "i"}`
```

When constructing this type, TypeScript eagerly resolves the template literal type to a union, `"abf" | "abg" | "abh" | ...`, which is much less useful in the documentation than the more concise form written by a programmer.

**Comment by gnourtn** [comment]
thank you, this is what im looking for. Setting stickNullChecks to true fixed the issue
