### ISSUE TITLE
O Brother, Where Theme Thou?

### ISSUE THREAD

**Issue by vitaly-t** [TypeStrong/typedoc#1811]
In the past, I have done a number of projects with the `minimal` theme.

The latest version tells us it no longer ships with that theme. And browsing through the myriad of other themes, it seems that they are all no longer compatible with the latest `typedoc`.

The first thought that comes to mind - how did this happen that years of community contributions has been thrown under the train just like that?

On a more selfish note, I just want the `minimal` theme back. Where can I find one that works with the latest library? Documentation doesn't tell us so. It's almost like it doesn't care anymore what happened to all the themes that developers got used to.

**Comment by Gerrit0** [comment]
The previous theme architecture has a multitude of problems. Not least among them being built in Handlebars with several layers of indirection, which completely removes any possibility of type checking templates. Switching to JSX from Handlebars also improved rendering speed by ~10x. A copy-paste job of moving them to JSX so that we had type checking revealed around half a dozen bugs in the default theme. 

The minimal theme was much *much* worse. If it wasn't going to be another 40+ hours to make it work, I'd have spent the time to make it work. (I'd say again, but based on the Git history it had been at least half broken for 2+ years so...) I spent around 8 hours trying to fix all the issues with it before deciding to get rid of it rather than continue shipping known broken code.

TypeDoc is an open source project unaffiliated with any company or collective that pays for its development. It gets attention if and when I or others have free time... with that in mind, I have received exactly one complaint since about the minimal theme going away - this one.

It would theoretically be possible for someone to write a wrapping theme which called into (some) old handlebars themes, and is something I briefly considered, but eventually decided against it due to how much time I have to give. I'm not aware of any minimal themes that support 0.22 today.

**Comment by vitaly-t** [comment]
> I'm not aware of any minimal themes that support 0.22 today.

That last line just killed me.

Not to be a nuisance, but do you know at least usable theme out there, resembling at least remotely the `minimal` theme, so one can download it freely and start using right away? I really have searched, and cannot find anything, it's like the whole typedoc system up and perished. Everything that's available doesn't work with the new typedoc.

**Comment by Gerrit0** [comment]
If I did, I would have mentioned it in my first reply.

I think a reason that there aren't a lot of themes for 0.22 is that a lot of the reasons to make a custom theme went away.
- Custom CSS to tweak one thing? There's an option for that now `--customCss`
- Need to inject a script to perform additional processing on load (e.g. mermaid rendering, new options in a the theme dropdown, or even adding extra content to the start of the page) you can do that with [hooks](https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md#hooks-v0228). Plugins, no longer need to create a custom theme to do this, so they don't have to force you to use some custom theme to use them.

I wouldn't say the ecosystem is dead. The autogenerated list of plugins at https://typedoc.org/guides/plugins/ has more supporting version 0.22 than 0.21 or 0.20. (Note: The themes page list is also automatically generated, but support for a tag to show up there is very new, so themes might be listed under plugins)

The minimal theme was heavily based on the default theme. I'd start there if rebuilding it. Even the page you linked shows that the minimal theme was broken... even though it avoided some broken parts by virtue of being a fairly small and straightforward project.
1. On mobile, the navigation pull out is utterly broken. On the home page it takes you to an index, other pages it does nothing.
2. Multiple pages were created - the documentation for the minimal theme said that it created a single HTML page intended to be easily shipped. Granted, this has been broken since I started working on typedoc, so it might be expected for you, but it wasn't intentional.
