### ISSUE TITLE
Comments for members of anonymous return types are not emitted

### ISSUE THREAD

**Issue by jugglingcats** [TypeStrong/typedoc#1821]
## Search terms

anonymous return types

## Expected Behavior

Sorry if this has been covered before but it's hard to search on!

Ideally typedoc should emit comments for anonymous return types, for example:

```
/** Comments in return type should be emitted */
export function testme1() {
  return {
    /** The foo (should be emitted) */
    foo: "42",
    /** The bar (should be emitted) */
    bar: 42
  };
}
```

## Actual Behavior

These comments are not emitted. Anonymous types as parameters are correctly emitted.

## Steps to reproduce the bug

https://codesandbox.io/s/typedoc-anonymous-return-types-4df51?file=/src/test.ts

## Environment

```
    "typedoc": "0.22.10",
    "typescript": "4.1.3"
```

**Comment by Gerrit0** [comment]
I think this is a new one, though related to a few other "comment discovery" issues - unfortunately fixing this is going to be annoying... because to fix it we really need to start using `symbol.getDocumentationComment`... which is usually fine, until someone uses declaration merging or `@inheritdoc`, and then it doesn't play "nicely"... at least according to how TSDoc says it ought to work... the temptation to say "TSDoc isn't important" is very strong right now... 

Alternatively, a fix could be to re-implement the ~1000 lines of code necessary to duplicate how the compiler does comment discovery, stripping out the `inheritdoc` bits... which will work until something changes in the compiler.

**Comment by Gerrit0** [comment]
![image](https://user-images.githubusercontent.com/19329837/175833138-06a10431-c61c-4dc6-b29e-334520fce5a2.png)

TypeDoc 0.23
