### ISSUE TITLE
File/module level support for doc comments

### ISSUE THREAD

**Issue by brandones** [TypeStrong/typedoc#1822]
## Search Terms

comment parsing

## Problem

I have a large library with many modules. Currently, if I want to mark everything exported by a certain module with a `category` or as `hidden` or `internal`, I need to add a comment for that above every function and type. This is impractical.

## Suggested Solution

I'd like to be able to just add a docstring at the top of the file which sets the `category`, `hidden`, `ignore`, or `internal`.

**Comment by Gerrit0** [comment]
TypeDoc does support module level documentation via either `@module` or `@packageDocumentation`: [docs](https://typedoc.org/guides/doccomments/#files).

Tags like `@category` won't be inherited to all children within the module, however. `@category` only applies to the reflection that the comment is on. It wouldn't be good to apply `@category` to each member of a class if the class is marked with a category, for example.

**Comment by brandones** [comment]
> Tags like @category won't be inherited to all children within the module, however. @category only applies to the reflection that the comment is on.

Yes, that is how it presently works. What I'm saying is that there *should be* a way to mark everything a file with a category, or as internal.

To paint the picture a little more: I generate an API for a package called `@openmrs/esm-framework`, which aggregates about 10 different lower-level packages. Each of those packages have some number of modules of functions, interfaces, etc. Many of them have some modules in which all of the _dozens_ of functions, interfaces, etc are not part of the public API—they should all be marked as internal. I do not want to create and maintain hundreds of `/** @internal */` lines across my codebase.

Similarly, everything in the subpackages should generally have the same category. All of the functions, interfaces, etc in the `@openmrs/esm-config` package (which is part of `@openmrs/esm-framework`) should have category "Config." Defining this at the module level would be ideal. I do not want to maintain hundreds of lines of `/** @category Foo bar **/ across my codebase.

Do those seem like reasonable needs to accommodate in TypeDoc?

**Comment by Gerrit0** [comment]
> What I'm saying is that there should be a way to mark everything a file with a category, or as internal.

I think this is better suited for a plugin. I'm not convinced I want to do this for everything. Projects may have more than one entry point, in which case it is convenient to be able to categorize *by file*, but redundant to categorize everything within that module.

```js
// typedoc --plugin path/to/this/file.js
const td = require("typedoc");

const paths = [
  { file: "class.ts", category: "Classes" },
  { file: "mdn.ts", category: "MDN" },
];

/** @param {td.Application} app */
exports.load = function (app) {
  /**
   * @param {td.Context} _ctx
   * @param {td.DeclarationReflection} refl
   * @param {td.TypeScript.Node | undefined} node
   */
  function applyCategories(_ctx, refl, node) {
    if (!node) return;

    for (const path of paths) {
      if (node.getSourceFile().fileName.endsWith(path.file)) {
        refl.comment = refl.comment || new td.Comment();
        refl.comment.tags.push(
          new td.CommentTag("category", undefined, path.category)
        );
      }
    }
  }

  app.converter.on(td.Converter.EVENT_CREATE_DECLARATION, applyCategories);
};
```

I don't think you need to do this for `@internal`, assuming you're running with `excludeInternal` since the [`--exclude`](https://typedoc.org/guides/options/#exclude) option provides a way to do this on a file-by-file basis.

---

In this particular case, I would probably slightly change how you document the `@openmrs/esm-framework` package. Instead of running TypeDoc with a single entry point, I would note in the readme that it is an aggregate package which exports everything from the contained package, and include documentation for each package individually. I can submit a PR to your repo if you want to see what this would look like.
