### ISSUE TITLE
How to create a single page site (theme or plugin)

### ISSUE THREAD

**Issue by Kivylius** [TypeStrong/typedoc#1824]
## Search terms

single page, spa, cra, custom theme, custom plugin, theme, docs, output, json, --json, out.json,

## Question

I want to create a custom theme or plugin or other (not sure) to make the output be a single page doc site, (id like to keep TypeDocs docs + my output), I was able to use the `out.json` that exported by TypeDocs (via `--json`) and using CRA, create a simple component that can render my output, screenshot: 

![Screenshot 2021-12-14 at 15 25 08](https://user-images.githubusercontent.com/1041335/146027436-1b7556f2-6a4c-4ecc-a15a-d529808724d5.png)

But now I want to use this in other repos (make is reusable) but not sure where to start (the docs are quite confusing for this type). Will this be possible with a theme? or a plugin? or my own custom setup only?

What I want to do:

Read the out.json or some other way and create a new single page website based of this. My app is looping the whole json and creating the above structure, I have only one interface per repo. (image a library with one component).

Any help on this be great.
Thanks

**Comment by krisztianb** [comment]
This should be doable with a plugin. I see two ways you could achieve this:

1. Your plugin is listening to the event that gets triggered when a reflection (eg. class) is being resolved. Your plugin adds that data to an internal structure or directly to another file (HTML).
2. Your plugin is listening to the end event of TypeDoc that is triggered when it basically finished resolving the entire project. Then your plugin traverses all reflections of the project (which should mostly be what you already have in your `out.json` file) and creates some other output from it.

Since you wrote that you already have an app that creates your desired output I think the second solution should be quite easy to implement. Basically you just have to trigger your output generator at a certain TypeDoc event instead of having to call it manually.

**Comment by Gerrit0** [comment]
https://github.com/Gerrit0/typedoc-custom-theme-demo/blob/main/src/index.tsx might also be helpful
