### ISSUE TITLE
addUnknownSymbolResolver to expose more than name

### ISSUE THREAD

**Issue by jpoehnelt** [TypeStrong/typedoc#1832]
## Problem

`addUnknownSymbolResolver` accepts a resolver that receives `ts.Symbol.name`, however the name is insufficient to identify the symbol in cases where the symbol is namespaced such as the following:

```ts
declare namespace foo.bar {
  class Baz {}
}
```

in the resolver this is only identified as `Baz` and not `foo.bar.Baz`

### 1. allow the resolver to access `ts.Symbol`

```ts
app.renderer.addUnknownSymbolResolver("my-package", (symbol: Symbol) => {
  // get namespace from Symbol.parent
   return '';
 });
```

This would be a breaking change and may expose a more complex interface than needed(?).

### 2. pass the namespaced name joining `ts.Symbol.parent` resulting in `foo.bar.Baz`. 
 
This option would not be a breaking change and is sufficient for my use case.

**Comment by Gerrit0** [comment]
`ts.Symbol.parent` is marked `@internal` for a reason, it's behavior isn't perfectly consistent in all cases (there's an issue about exposing it in Microsoft/TypeScript... somewhere where this was brought up)

I don't want to give resolvers access to the symbol since really they ought to be able to execute without access to the compiler (will be *required* if I ever get around to making it possible to generate docs from JSON, which is a rather important next step for making the packages entry point strategy usable for repos which don't release every package whenever one releases)

I've pushed a tentative fix for this, but want to look at it again this weekend before merging.

**Comment by jpoehnelt** [comment]
Thanks for the quick turnaround!
