### ISSUE TITLE
Indexed Access Types

### ISSUE THREAD

**Issue by MRWS** [TypeStrong/typedoc#1839]
## Search Terms

Indexed Access Types, Lookup Types, flat returns

## Question

We have some types generated and exported from [openapi-typescript](https://github.com/drwpow/openapi-typescript#using-in-typescript) with indexed access types according to there documentation
```ts
import { components } from './generated-types';

type Schemas = components['schemas'];

export type Individual = Schemas['Individual'];
export type Login = Schemas['Login'];
export type NetworkItem = Schemas['NetworkItem'];
```
Then the doc is generated like so :

![image](https://user-images.githubusercontent.com/7048445/148922518-3a0f0280-0490-4543-bec1-5d6f5eb505ed.png)

Is there a way to have "flat" types with indexed access types ? Like just having an `Individual` type instead of a link into `Schemas` who links into `components` ?

Another issue we have is when using these types as returns, this time they are not linked but "flatten", which is unreadable.
![image](https://user-images.githubusercontent.com/7048445/148924176-db2399c9-998c-4a64-8d31-13507c7174e0.png)
Is this a bug ? How can i have something like `getLoginByExternalId(externalId, context?): Promise<Login>` ?

**Comment by charlesdlrsa** [comment]
We are very interested in solving this bug with our team as well!

**Comment by Gerrit0** [comment]
Type aliases being displayed as written - this is working as intended. #1519 tracks adding some special cases to treat certain object types as interfaces, which would help this... 

The functions, unfortunately, is a design limitation. TypeScript will eagerly resolve indexed access types when working with types (the improvements for preserving type aliases introduced in [TypeScript 4.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html#smarter-type-alias-preservation) sadly don't apply here). So the type that TypeDoc receives is what is displayed.

You can get better results by telling TS that you *really* meant to create a name for the type by using an interface instead of a type alias.

```ts
type Foo = {
  a: { a: 1 }
}

// Needed to workaround TS requiring `extends` to be a an identifier with optional type arguments.
type Identity<T> = T

interface Bar extends Identity<Foo["a"]> {}
```

**Comment by Gerrit0** [comment]
Aside: Some have suggested that the design limitation can be "fixed" by relying on type nodes instead of inferred types if they are specified. This works, in this case, but will produce significantly worse results in other, equally common, cases.

```ts
class Generic<T> {
  method(): T extends string ? 123 : 456
}

// Child.method should be documented as returning 123, not 
// "T extends string ? 123 : 456" or "string extends string ? 123 : 456"
class Child extends Generic<string> {}
```
