### ISSUE TITLE
typedoc hangs indefinitely

### ISSUE THREAD

**Issue by vince-fugnitto** [TypeStrong/typedoc#1868]
## Question

Since upgrading `typedoc` from `0.20.36` to `0.22.11` (in order to support typescript v4.5), we have encountered issues using typedoc where it will hang indefinitely during CI. I've ultimately tried to keep the same behavior from `0.20` when using `0.22` since it was known to work (https://github.com/eclipse-theia/theia/commit/a552c066088723e61a72137b67f5997432f6a1b1)

The process was manually cancelled (resulted in a generation over 2 hours):

- [Example CI Run](https://github.com/eclipse-theia/theia/runs/5139114596?check_suite_focus=true)
- [Raw Log](https://pipelines.actions.githubusercontent.com/X4qF0EcEV6B8ivZmE3366xuawA0J2JI6DYpNyR88rPsIFvbNLl/_apis/pipelines/1/runs/7473/signedlogcontent/99?urlExpires=2022-02-10T12%3A47%3A57.5476165Z&urlSigningMethod=HMACV1&urlSignature=D8UX8EGr6KLk%2FBrCVsVQzGslPoiE%2B9UAcboLTe%2FIr%2FY%3D)

Locally I have tried to add the plugin [typedoc-plugin-missing-exports](https://github.com/Gerrit0/typedoc-plugin-missing-exports) but it would ultimately result in an out of memory error (despite `NODE_OPTIONS=--max-old-space-size=8192` being set).

Is there something that we are doing wrong, I'm not sure why typedoc would hang indefinitely without any clear error on how to proceed?

## Reproduction Steps

If interested, you can run the generation locally on the repo (the repo is likely one of the more complex projects):

- clone https://github.com/eclipse-theia/theia
- follow the [prerequisites](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites)
- perform `yarn`
- perform `yarn docs` (note you'll likely need to set `NODE_OPTIONS=--max-old-space-size=8192` beforehand)

## Additional Info:

- [typedoc.json](https://github.com/eclipse-theia/theia/blob/master/configs/typedoc.json)

**Comment by Gerrit0** [comment]
I'm actually surprised TypeDoc manages to  create all the programs... TypeDoc is creating 53 instances of the compiler concurrently in order to create a single documentation site....

Turning on `--logLevel Verbose` provides some insight:

```
Debug: Converting with 50 programs 2725 entry points
```

When running locally with `NODE_OPTIONS` set to bump up available memory, I *still* run out of memory. I put some more logging in:

```
There are 149247 reflections in the project
There are 6182 pages to render
```

... that's a lot of pages. This led me to suspect that your exclude settings weren't being applied in the same way. The resulting investigation eventually led to adding two lines to the release notes for 0.22.0.

-   Paths in config files will now be resolved relative to the config file instead of relative to the current working directory.
-   Exclude patterns are now checked against files instead of against each part of the path as traversed, #1399.
    This means that an exclude of `**/someDir` will **not** exclude files in that directory. To exclude files in a directory, specify `**/someDir/**`.

I've submitted a pull request with the appropriate changes to fix this in your project: https://github.com/eclipse-theia/theia/pull/10743

**Comment by vince-fugnitto** [comment]
Thank you for taking the time to help out and identify the issue :+1:
