### ISSUE TITLE
Support .d.ts entryPoints

### ISSUE THREAD

**Issue by xiaoxiangmoe** [TypeStrong/typedoc#1887]
## Search Terms

entryPoints

## Problem

Vue use [vue-tsc](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc) to convert `.vue` file to `.d.ts` declarations. But typedoc not support `.d.ts` file as entryPoints

## Suggested Solution

Support `.d.ts` files as entryPoints.

**Comment by Gerrit0** [comment]
TypeDoc already supports this - but your tsconfig must be set up so that the declaration files are included in the project. You might also try [vue-typedoc](https://github.com/thepaperpilot/vue-typedoc) which overrides TypeDoc's use of TypeScript in a similar way as vue-tsc does, not heavily battle tested, but...

**Comment by Gerrit0** [comment]
Closing as this seems to be resolved

**Comment by Gerrit0** [comment]
The vue-typedoc solution is the same method that vue-tsc uses (or maybe used I suspect TS 5.0 broke it. I don't work with it day to day, so am not aware of any improvements there)

I'm not aware of any further efforts to support .vue files natively, and I don't plan on spending time on it - there's enough with native TS support to keep me busy with the time I have for typedoc. If you have a tool that emits .d.TS declaration files, typedoc can handle those as input today if properly configured.

**Comment by runspired** [comment]
I don't think we need a way to support `.vue` or `.svelte` or `.gts` or `.astro` or `.mdx` files natively... what we need is a way to ensure that typedoc either consumes the output of a tool which does support it and/or invokes that tool. All of these ecosystems have some variant of a wrapper around tsc. In vue this is `vue-tsc`, in ember this is `glint` both of which use volar (a tsserver plugin) plus a wrapper to ensure that the file extension works.

**Comment by runspired** [comment]
> Closing as this seems to be resolved

I have found no mechanism by which to tell typedoc "please do not run tsc yourself, just use the existing d.ts files" without mega hacks. I'd love to know what you meant by this was already supported.

For instance, @nullvoxpopuli went so far as to create a wrapper that passes an entire fake project with a tsconfig generated to only consume the d.ts files in order to get it work with the `d.ts` files generated by glint and ignore the real project. This has ramifications on source code mappings and urls. https://github.com/universal-ember/kolay/blob/5a615301490fe42db8a6f57084777381645a01c3/src/build/plugins/api-docs/typedoc.js#L60-L91

**Comment by Gerrit0** [comment]
How is configuring TypeDoc to use declaration files with a tsconfig a "mega hack"? If given your normal tsconfig file, when TypeDoc calls the compiler API it will use your regular sources for type checking... the declaration files then are outputs, not inputs...

TypeDoc exposes a [Converter.convert](https://typedoc.org/api/classes/Converter.html#convert) function which accepts entry points with a user-provided `ts.Program` and `ts.SourceFile`. If you can satisfy that API with some TS plugins enabled, then you can use that without relying on TypeDoc's program creation.

**Comment by runspired** [comment]
I started trying to implement the virtual-tsconfig-just-for-typedoc hack and have found it won't work for monorepos, as it relies on the ability to change out the src directory. In a monorepo, we'd be changing out the root config containing all the references to the various composite projects, which would result in still resolving the real source files and not the built declarations

**Comment by runspired** [comment]
> TypeDoc exposes a [Converter.convert](https://typedoc.org/api/classes/Converter.html#convert) function which accepts entry points with a user-provided ts.Program and ts.SourceFile. If you can satisfy that API with some TS plugins enabled, then you can use that without relying on TypeDoc's program creation.

Sounds like I'll need to do this.
