### ISSUE TITLE
Allow to specify file name for html output

### ISSUE THREAD

**Issue by Smrtnyk** [TypeStrong/typedoc#1905]
## Search Terms

Output file name

## Problem

I have noticed that there is no option to specify output html file name.
We are serving the html file via an iframe and we cannot serve it as an index.html, so we rename it manually to page.html.
But then all the links in the html files are hardcoded to index.html, and then we need to traverse trough the html files to replace them.
This is very cumbersome.

## Suggested Solution
In the out option allow to specify the file name.
For example
```out: /doc/page.html```

**Comment by Gerrit0** [comment]
This is something that could be implemented with a custom theme pretty easily. Not something I want to include in the core:

```ts
// typedoc --plugin path/to/this/file.js --theme page
const td = require("typedoc")

class PageTheme extends td.DefaultTheme {
  override getUrls(project) {
    const mappings = super.getUrls();
    for (const mapping of mappings) {
      if (mapping.url === "index.html") {
        mapping.url = "page.html"
        break;
      }
    }
    return mappings;
  }
}


exports.load = function(app) {
  app.renderer.defineTheme("page", PageTheme);
}
```

This won't *quite* work since the header link is hardcoded to go to index.html, I'd accept a PR which updated that to go to a root project URL defined in the theme. You could also work around it by defining a new header template which changed that and providing a render context [as shown here](https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md)
