### ISSUE TITLE
Support README.adoc

### ISSUE THREAD

**Issue by raldone01** [TypeStrong/typedoc#1911]
## Search Terms
ascii-doctor adoc README

## Problem

An ascii-doc file as a README is not rendered correctly. Github supports README.adoc and renders them correctly.

## Suggested Solution

Add support for ascii-doc files.

**Comment by Gerrit0** [comment]
I did a bit of cursory research on this, and it looks like `.adoc` is a very niche format.

The [npm package](https://www.npmjs.com/package/asciidoctor) gets 11k downloads per week. (TypeDoc gets 590k) Searching for `README.adoc` on GitHub shows 34k code search results, in comparison with the 16M search results for `README.md`...

I don't think this is something that is suitable for inclusion in TypeDoc itself. A plugin could likely achieve this without requiring the >98% of users who don't use AsciiDoc to download additional dependencies.

**Comment by raldone01** [comment]
True. A plugin would be nice. If I were to write one could you point me in the right direction?
Should I create a theme or plugin?
And how should I hook into typedoc?

**Comment by Gerrit0** [comment]
> Typedoc does not automatically search for README.adoc files. It chooses the README.md of the parent folder. It may be ok to just accept any README.* file in the current project directory and let plugins to the trick. If a user wants the current behaviour to choose the parent README file they can use the readme config option.

This isn't an acceptable solution, because it would be really bad if TypeDoc tried to treat a `readme.pdf` as text. Your plugin could do something similar to TypeDoc's [PackagePlugin](https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/plugins/PackagePlugin.ts#L50) to add automatic discovery for readme.adoc as well.

> It appears [that the readme string is run through a markdown renderer no matter what](https://github.com/TypeStrong/typedoc/blob/d943dc6b0f66974d41f55d0206664aaf09960e1f/src/lib/output/themes/default/templates/index.tsx#L8). Which appears to be harmless but may break with some inputs.

Yeah... I don't think there's a good solution for this. The most popular TypeDoc plugin is typedoc-plugin-markdown, which causes TypeDoc to output markdown instead of HTML. Theoretically someone ought to be able to build an EPUB/PDF renderer too. Parsing as markdown before then isn't really ideal. In the realm of JS documentation, markdown has won. It's used for doc comments too... I really don't want to unnecessarily increase complexity

**Comment by raldone01** [comment]
I understand. Thank you for giving me all the necessary information and showing me the "bigger" picture.
