### ISSUE TITLE
Move under TypeStrong

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/typedoc#192]
Hey! I've been using this for a while personally and I wanted to reach out and ask if you'd be interested in maintaining the repository under https://github.com/TypeStrong? We've got a few TypeScript projects in there and we might be able to help each other along a little as we go.

**Comment by gdi2290** [comment]
+1

**Comment by tht13** [comment]
The owner does not seem to be active and while I would prefer to get explicit permission, the license does allow cloning and reuploading into the TypeStrong repo. I know this is bad practice but having this great tool stuck on TS1.6 is a real blocker for me.

**Comment by gdi2290** [comment]
fork as ts-doc

**Comment by tht13** [comment]
@blakeembrey As you are a member of TypeStrong, can you do this?

**Comment by sebastian-lenz** [comment]
Hi all, I'm very sorry for being so unresponsive lately. Both my professional and private situation has changed a few months ago and since then I've been pretty bad at managing my correspondence with the followers of this project. This should be no excuse, I should have been able to manage to drop you a few lines at least and I want to apologize for my behaviour.

I've been working on this project since early 2014 and tried to keep it updated over the years so I'm really dedicated to this work. I would be more than happy if someone want's to take a spin on this project now I am in a situation where I am not able to invest as much time as it would need to keep the project maintained. TypeStrong for sure would be a perfect place to put this project to so if you are still interested I would be happy to transfer the project over there.

**Comment by tht13** [comment]
@sebastian-lenz Thanks :smile: 
Hope all is well also!

**Comment by sebastian-lenz** [comment]
@tht13 Thank you. Nothing to worry about, everything is fine, it's really just missing time right now.

**Comment by christopherthielen** [comment]
@sebastian-lenz just wanted to thank you for work.  I've been using typedoc for the [new angular ui-router docs](http://angular-ui.github.io/ui-router/1.0.0-alpha.3/) and love it.  Writing api docs feels almost effortless!

+1 for @sebastian-lenz
+1 for moving to TypeStrong

**Comment by blakeembrey** [comment]
@sebastian-lenz You should be able to transfer it, I'll try to help maintain the issues and PRs with you :+1:

**Comment by sebastian-lenz** [comment]
Okay, TypeDoc has a new home!

**Comment by blakeembrey** [comment]
Thanks for all your work @sebastian-lenz! If you get the time, it'd be awesome to give some overview for others to get started helping out. I'll review the existing issues and PRs when I get a chance.

**Comment by jasongrout** [comment]
Yes, thank you very much for your work, @sebastian-lenz! Typedoc was an important factor in us deciding to use typescript.

**Comment by drinchev** [comment]
Just a big thank you @sebastian-lenz . If you have opportunity to meet in Berlin, just ping me. Typedoc has been an enormous help for me and the company I'm working for right now. Kudos for everything.
