### ISSUE TITLE
Provide type information for Enum members

### ISSUE THREAD

**Issue by vladfrangu** [TypeStrong/typedoc#1942]
## Search Terms

enum, enum members, missing type in enum members

## Problem

While generating documentation for enums, they never include the type of the variable in the enum (for instance a literal type object, so we have more clues), which can cause problems if you want to render that in a custom way. You can see this in the JSON linked below.

https://github.com/vladfrangu/typedoc-number-enum-lacks-type-information/blob/674a128da9d715023ebfeaedef6a34f5655e0bf4/out/doc.json#L16-L29

## Suggested Solution

Ideally, typedoc should either append type information for the enum members (otherwise we have to take a wild guess and just default it to literal which is less than ideal) or maybe it should add a flag instead. Would also help to know if the `defaultValue` is a number/string without having to check if `defaultValue[0] === '"'` or other detection methods

**Comment by Gerrit0** [comment]
Your provided link is private.

I'm guessing that the highlighted lines show that the type is a reference type - if you resolve said reference type, you should then have access to the enum it refers to. Setting the `type` property on the enum member reflection seems like a reasonable request to me, along with an update to the default theme so that it isn't rendered.

**Comment by vladfrangu** [comment]
Woops. Sorry about the private link, forgot to set the repo to public once I set it up 😅
