### ISSUE TITLE
Links point to wrong scope when linking from interface to external scope

### ISSUE THREAD

**Issue by ritave** [TypeStrong/typedoc#1949]
## Search terms

link

## Steps to reproduce the bug

```typescript
export interface MyInterface {
}
export interface Nested {
  // This will link to Nested.MyInterface in generated documentation
  // The behaviour is different from the Typescript Language Server, which links to interface MyInterface
  /** {@link MyInterface} */
  readonly MyInterface: new() => MyInterface;
}
```

Notice that this will work correctly

```typescript
export interface MyInterface {
}
export type Nested = {
  // Both Typedoc and TS Language Server will point to interface MyInterface
  /** {@link MyInterface} */
  readonly MyInterface: new() => MyInterface;
};
```

## Environment

-   Typedoc version: `TypeDoc 0.22.17`
-   TypeScript version: `Version 4.7.2`
-   Node.js version: `v16.15.0`
-   OS: `macOS Monterey Version 12.4`

**Comment by Gerrit0** [comment]
Oh TypeScript, why did you have to add support for `@link`... This is working [as documented](https://typedoc.org/guides/link-resolution/) today, though it would be nice to try to be consistent with TypeScript's behavior. If I remember right, the "correctly" working one is doing that because TypeDoc doesn't traverse into type literals for links (TypeScript *sometimes* does)

TypeScript how I despise you some days...

```ts
// TypeScript / TypeDoc

/** {@link abc} 1/1 */
type abc = 1

/** {@link abc} 2/2 */
namespace Foo {
    /** {@link abc} 2/2 */
    export type abc = 2

    /** {@link abc} 3/2 */
    export function asdf(){
        /** {@link abc} 3/not processed */
        type abc = 3
    }
}

/** {@link abc} 1/4 */
interface Bar {
    /** {@link abc} 1/4 */
    abc: 4
}

/** {@link abc} 1/5? maybe 1 */
type Baz = {
    /** {@link abc} 1/5 */
    abc: 5
}

/** {@link abc} 1/6 */
class Zip {
    /** {@link abc} 1/6 */
    abc?: 6
}

{
    /** {@link abc} */
    type abc = 7
}
```

... Namespaces create a new scope, so do other nodes with a body, but nothing else, well... okay...

One advantage to TypeDoc's resolution strategy is that links that TS resolves to 1 don't change what they are pointing to if you comment out `type abc = 1`... though I guess the opposite could be said if `Foo.abc` went away...
