### ISSUE TITLE
Feature: Add exclusions for cleanOutputDir=true

### ISSUE THREAD

**Issue by ilyub** [TypeStrong/typedoc#1954]
## Search Terms

cleanOutputDir

## Problem

My docs directory contains files that are not generated by typedoc, e.g.: _config.yml

I want to clear files generated with typedoc, but keep manually added files (_config.yml,  etc)

## Suggested Solution

Add clean exclusions option

**Comment by Gerrit0** [comment]
I'm not sure I want to do this... doing this would mean that TypeDoc has to have a lot more logic to only clean out what it's allowed to rather than a simple directory removal... further, this means you *still* have to maintain a list of files. It should be straightforward to instead copy these in from a versioned directory in a post-build step.

Related: #1123
