### ISSUE TITLE
{@link} not working to same name import that is both a class and a namespace

### ISSUE THREAD

**Issue by frank-weindel** [TypeStrong/typedoc#1999]
## Search terms

same name class namespace link

## Expected Behavior

Given `NamespaceClass.ts`:
```ts
declare namespace NamespaceClass {

}

/**
 * NamespaceClass documentation...
 */
class NamespaceClass {

}

/**
 * My docs
 */
export class UnambiguousClass {

}

export default NamespaceClass;

```

And `index.ts`:
```ts
import NamespaceClass from "./NamespaceClass";

/**
 * See {@link NamespaceClass}
 * See {@link NamespaceClass:class}
 */
export const MySymbol = new NamespaceClass();
```

## Actual Behavior

A warning occurs and the link is not created:
```
warning Failed to resolve {@link NamespaceClass} in MySymbol with declaration references. This link will break in v0.24.
warning Failed to resolve {@link NamespaceClass:class} in MySymbol with declaration references. This link will break in v0.24.
```

## Steps to reproduce the bug

See: https://github.com/TypeStrong/typedoc-repros/pull/14

## Environment

-   Typedoc version: 0.23.7
-   TypeScript version: 4.7.3
-   Node.js version: v16.14.0
-   OS: macOS 12.2.1

**Comment by Gerrit0** [comment]
There's a few things here:

1. `NamespaceClass` isn't exported from an entry point: https://github.com/frank-weindel/typedoc-repros/blob/namespace-class-link/typedoc.json#L3, so there's no way to link to either the class or the namespace since they aren't included in the documentation. If you add `export { NamespaceClass }` to index.ts, the links will resolve as expected
2. TypeDoc resolves links after creating reflections, using what's exported. It does *not* take into account what symbols you have in scope.

**Comment by frank-weindel** [comment]
Thanks! I'll give your advice a shot
