### ISSUE TITLE
Better documetation of  Overloading types

### ISSUE THREAD

**Issue by adamjosefus** [TypeStrong/typedoc#2002]
## Problem

If you are using overloading type in your functions/methods, the builder documentation is not really helpful in this task.

Code Example A:

```ts
type Entry =
    | [title: string, content: string, button: string]
    | [title: string, content: string, button: string, options: Options]
    | [title: string, content: string, primary: string, secondary: string, options: Options];

function myFunction(...entry: Entry): void {
    // Some code...
}
```
VS Code intellisense: 
<img width="400" alt="Snímek obrazovky 2022-07-13 v 19 53 52" src="https://user-images.githubusercontent.com/1031370/178799121-b2efce1a-54b9-445d-9d37-be0de40c1570.png">
<img width="400" alt="Snímek obrazovky 2022-07-13 v 19 53 52" src="https://user-images.githubusercontent.com/1031370/178799799-d4daca2b-dbae-4681-b4d5-e4ab9557c737.png">

Code Example B:

```ts
function myFunction(param1: string): void;
function myFunction(param1: number, param2: boolean): void;

function myFunction(param1: string | number, param2?: boolean): void {
    // Some code...
}
```

VS Code intellisense:
<img width="400" alt="Snímek obrazovky 2022-07-13 v 19 50 14" src="https://user-images.githubusercontent.com/1031370/178798421-4ee043c4-1233-4ec5-b179-5d895a7bbd3b.png">
<img width="400" alt="Snímek obrazovky 2022-07-13 v 19 50 22" src="https://user-images.githubusercontent.com/1031370/178798424-d4157021-dd9b-4ce7-9baf-87690400612c.png">

## Suggested Solution

- Detect type for overloading and include it next to the function.
- Render all argument possibilities

**Comment by Gerrit0** [comment]
This is going to be a tricky one I think... should be possible, but by no means trivial.

**Comment by Gerrit0** [comment]
The language service is entirely too magical... and inconsistent. When hovering over the function, it shows "real" overloads...

![image](https://user-images.githubusercontent.com/19329837/208279002-d51b6c20-f4ea-4662-a3f2-f7eda33f2403.png)

But when providing arguments, it instead shows "signatures"

![image](https://user-images.githubusercontent.com/19329837/208279028-4f1b0714-58f6-4d1f-827d-2d68d8161b0d.png)

I think I'm actually going to punt this to plugin-space. I'm really wary of including functionality in TypeDoc itself which significantly changes what you'd see if looking at the declaration file of a library, since it opens up holes for questions when there's now no reference to `Entry` in the docs for `myFunction`, or `myFunction` is rendered with `Entry` and then also with the expanded signatures (ew, makes it looks like there's an extra overload...)

I might consider this if someone builds a plugin which does this that solves these issues in the rendered docs, but I'm not seeing a clean way of doing it.

---

If looking to implement this without solving that issue, I'd recommend listening to `Converter.EVENT_CREATE_SIGNATURE` and replacing `sig.parent.signatures` with the appropriately expanded signatures. I've just updated the emit for that event to also include the signature, which will be necessary to easily resolve parameter types.
