### ISSUE TITLE
Q: Type is referenced but not included in the documentationm

### ISSUE THREAD

**Issue by glensc** [TypeStrong/typedoc#2021]
## Question

```json
// typedoc.json
{
  "entryPoints": ["src/index.ts"],
  "excludePrivate": true,
  "excludeProtected": true,
  "excludeInternal": true,
  "readme": "docs/USAGE.md",
  "out": "documentation"
}
```

```
➜ typedoc --out documentation
./src/Types.ts:11:0 - warning TagType is referenced by Logger.withTags.withTags.tags but not included in the documentation.

11    export type TagType = {

Documentation generated at ./documentation
```

I set up typedoc months ago, and now now trying to finish up my work. I don't remember anything about how it works. how I'm supposed to resolve this warning? I should add src/Types.ts to entryPoints? or...?

**Comment by Gerrit0** [comment]
This means that some function/variable exported from src/index.ts uses `TagType`, but there's no way for consumers of your library to import it from a declared entry point in order to use it. For example, given the following input:

```ts
// index.ts 
import { TagType } from "./types"

export function play(game: TagType): void
```

Some consumer could reasonably expect to be able to do something like this:

```ts
// user.js
import { TagType, play } from "your-lib"

const game: TagType = Math.random() > 0.5
  ? "standard"
  : "freeze"

play(game)
```

However, they can't do this since `TagType` isn't exported from the entry point of `your-lib`. 

The appropriate fix for this depends on what you'd like the user to do. If they should import from `your-lib/types`, that additional entry point should be given to TypeDoc. If they should only import from the library's root entry point, you should add an export to `src/index.ts` for that type.

**Comment by glensc** [comment]
Thanks. That solved it!
