### ISSUE TITLE
Restore Node 12 support?

### ISSUE THREAD

**Issue by shmax** [TypeStrong/typedoc#2049]
Hey there, me again. Say, is there any chance you could see your way to restoring support for Node 12 in your package.json? I sat down a few weeks ago to finally update our TypeDoc version so we could try out that search boost thing I submitted back in May, and it seems that between that time and my more recent fixes, you removed support for node 12 and locked to 14.

For a lot of folks it wouldn't be a problem, but our documentation building task is just one of many others that happens in a massively complex CI environment that is maintained by a collection of international teams, and well, long story short, we're not able to easily upgrade our Node.js version at this time without breaking other parts of our build.

What do you say? 🙏

**Comment by Gerrit0** [comment]
This is probably going to be a wontfix - every additional version of node that's supported is one more thing to think about when developing (lack of several convenient fs methods is annoying), one more thing that can break, and means that we can't depend on any tools which require updated node versions. In particular, the latest prettier, mocha versions require Node 14. (Could make an argument that we could support older versions in production only... but that makes testing on older versions really annoying)

**Comment by shmax** [comment]
> one more thing that can break

But something breaks without it. 😢 

Okay, so Prettier requires 14. That's more of a development concern for your end, isn't it? I mean, it doesn't have anything to do with our CI step, does it?  Is that what you meant about production-only? What would that look like?

**Comment by Gerrit0** [comment]
>  Is that what you meant about production-only? 

Yes

> What would that look like?

Well... It would mean we don't test TypeDoc on Node 12 since TypeDoc's CI can't be run on Node 12, which would mean that any testing there would have to be entirely manual. This would mean that releases go from taking <10 minutes to do to probably over an hour since I don't want to claim to support something without giving it at least a cursory check before release... which probably means I'll avoid making releases with bug fixes because it's annoying to do...

I double checked prettier - looks like it's only mocha right now that requires node 14, but they're planning on requiring it in the next release. Having to check to see if tools I want to use support an obsolete Node version is also an annoyance...

**Comment by shmax** [comment]
I'm going to close this, as our CI support team has managed to work through the kinks with upgrading to node 14. Thanks much.
