### ISSUE TITLE
Can't compile docs

### ISSUE THREAD

**Issue by born2net** [TypeStrong/typedoc#206]
I am running the command of:

```
typedoc --out ./docs/ ./src/
```
and getting:

```
Using TypeScript 1.6.2 from C:\Users\root\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\lib
Error: C:/msweb/studioDashboard/src/Lib.ts(82)
 '=' expected.
Error: C:/msweb/studioDashboard/src/comps/app1/dashboard/Dashboard.ts(24)
 Type expected.
Error: C:/msweb/studioDashboard/src/comps/app1/users/AddUser.ts(60)
 Type expected.
Error: C:/msweb/studioDashboard/src/comps/app1/users/AddUser.ts(60)
 ';' expected.
Error: C:/msweb/studioDashboard/src/comps/simplegrid/SimpleGridDataDropdown.ts(60)
 Type expected.
Error: C:/msweb/studioDashboard/src/stations/StationModel.ts(53)
 '=' expected.
root|studioDashboard>
```

it's just an Angular 2 TS project...
any help is appreciated,

Sean.

**Comment by born2net** [comment]
I ended up just adding ignoreCompilerErrors: true,

**Comment by StephanBijzitter** [comment]
I am also getting this now

**Comment by aciccarello** [comment]
@StephanBijzitter, this is likely due to TypeDoc using a different version of the TypeScript compiler than your project. TypeDoc is tightly bound to TypeScript versions because it depends on methods and symbols that frequently change from version to version.

Have you tried @born2net's suggestion of the `ignoreCompilerErrors` option? If it is minor enough, that will sometimes allow you to get past the error.

**Comment by StephanBijzitter** [comment]
ignoreCompilerErrors worked, as did using the local version of typescript, which was two minor versions newer than the global one on my system. 

Would it be okay if I open a pull request to append common mistakes (starting with this one) to the end of the readme?
