### ISSUE TITLE
Typedoc uses package.json entrypoint instead of typedoc.json entrypoints

### ISSUE THREAD

**Issue by Artrix9095** [TypeStrong/typedoc#2099]
## Expected Behavior

I expected typedoc to generate the docs for the mono repo

## Actual Behavior

Throws the following error

`error Entry point "/workspaces/Slythe.js/packages/core/dist/index.js" does not appear to be built by/included in the tsconfig found at "/workspaces/Slythe.js/packages/core/tsconfig.json"`

## Steps to reproduce the bug

https://github.com/Artrix9095/typedoc-repros

So if you run `./run.sh` you get the error shown above, i managed to fix this by changing the `main` of the `package.json` (in each monorepo) to an actual typescript file, but I specified in the folder a `typedoc.json` file that shows the entry point like said in the docs [here](https://typedoc.org/guides/monorepo/#typedoc-package-config) so its weird that is just looking straight at the package.json and not the typedoc.json. am I doing something wrong here?

## Environment

-   Typedoc version: 0.23.20
-   TypeScript version: ^4.8.3
-   Node.js version: v18.11.0
-   OS: github workspaces

**Comment by Artrix9095** [comment]
the root typedoc config is in the docusaurus config [here](https://github.com/Artrix9095/typedoc-repros/blob/main/apps/docs/docusaurus.config.js)

**Comment by Gerrit0** [comment]
packages mode *does not* use typedoc.json in the packages to be documented. This is something I'm looking at changing with 0.24, so that packages can be built with differing typedoc settings and then merged together, but it's expected behavior today. For now, I'd recommend setting `"typedoc": { "entryPoint": "src/index.ts" }`, or turning on source maps in your root tsconfig so that TypeDoc can locate the entry point by looking at the built JS file.

**Comment by Artrix9095** [comment]
Fixed by setting `"inlineSourceMap": true` in my base tsconfig
