### ISSUE TITLE
Impossible to differentiate between two unknown symbols exported with the same name from different locations in the same dep

### ISSUE THREAD

**Issue by achingbrain** [TypeStrong/typedoc#2125]
## Search terms

- unknown symbol resolver
- duplicate symbol names

## Question

If I have a dependency called `my-dep` with two files like:

```ts
// src/export-1.ts
export interface DuplicateInterfaceName {}
```

```ts
// src/export-2.ts
export interface DuplicateInterfaceName {}
```

...and I consume it from my project as:

```ts
import { DuplicateInterfaceName } from 'my-dep/src/export-1.js'
import { DuplicateInterfaceName as DuplicateInterfaceName2 } from 'my-dep/src/export-2.js'

export interface ExtendsBoth extends DuplicateInterfaceName, DuplicateInterfaceName2 {

}
```

I configure an unknown symbol resolver plugin like:

```ts
// my-plugin.ts
export function load (app: Application) {
  app.converter.addUnknownSymbolResolver((ref) => {
    console.info(JSON.stringify(ref, null, 2))
  }
}
```

I get:

```
{
  "resolutionStart": "global",
  "moduleSource": "my-dep",
  "symbolReference": {
    "path": [
      {
        "path": "DuplicateInterfaceName",
        "navigation": "."
      }
    ]
  }
}
{
  "resolutionStart": "global",
  "moduleSource": "my-dep",
  "symbolReference": {
    "path": [
      {
        "path": "DuplicateInterfaceName",
        "navigation": "."
      }
    ]
  }
}
```

That is, `DuplicateInterfaceName` is reported as unknown twice (as expected) but there's no way to differentiate between them.

Is there any way to have more in the `ref`, perhaps the name of the file in `my-dep` that the export resolved to?

**Comment by Gerrit0** [comment]
`ref` comes from the user specified [declaration reference](https://typedoc.org/guides/declaration-references/), so if you used `{@link my-dep/export-1!DuplicateInterfaceName}`, you'd get that parsed path.

**Comment by achingbrain** [comment]
I may be misunderstanding something here but there are no tsdoc comments involved, it's just the types from the source code.

**Comment by Gerrit0** [comment]
I must not have been fully awake quite yet... 

You're correct - there's no way to tell in this case. TypeDoc only tracks the package name for unknown symbols, not the full path to the file they're stored in, so when constructing an implied declaration reference, it can't give the whole path.

This could be considered a bug, but it's also one I'm pretty unlikely to getting around to fixing, since doing so would mean that every symbol resolver would have to handle parsing paths, while the vast majority of libraries assume one entry point...
