### ISSUE TITLE
typedoc can't export type by ```export default ...``` reference 

### ISSUE THREAD

**Issue by EricaLi123** [TypeStrong/typedoc#2159]
## Search terms
export default

#### entryPoints
```
//index.exportByWrapInDefault.ts
export * from "./utils/index";

import * as utils from "./utils"
export default { ...utils };
```
### typedoc actual result
The type of fn cann't be export.
![image](https://user-images.githubusercontent.com/58462179/216508619-ab7dfa58-4d5f-49dc-988f-dc6d71940905.png)

#### entryPoints
```
//index.export.ts
export * from "./utils/index";
```
#### typedoc actual result
![image](https://user-images.githubusercontent.com/58462179/216508364-5de0fa1c-474d-41cb-b238-80eb1e02c488.png)
![image](https://user-images.githubusercontent.com/58462179/216508425-357a7e1c-6dea-45c9-8a9f-d42ddddb7a7f.png)

## [Demo](https://github.com/EricaLi123/prac-typedoc.git)
- run case 1 ``` npm run doc-existDefaultExport```
- run case 2 ``` npm run doc-noDefaultExport```

## Environment

-   Typedoc version: 0.23.24
-   TypeScript version: 4.9.5
-   Node.js version: 14.18.1
-   OS: win 10

**Comment by Gerrit0** [comment]
This is an unfortunate interaction, but is working as designed. TypeDoc converts re-exports after exports since it produces better results for the majority of projects... however, because you introduced a default export, that's not a re-export and is converted first. If you `export default utils` instead of `export default { ...utils }` the result is better.

It might be worth experimenting with always converting default exports last...
