### ISSUE TITLE
Additional Exclude Options

### ISSUE THREAD

**Issue by Bernardo-Castilho** [TypeStrong/typedoc#217]
I just started using TypeDoc and I love it! I want to use it instead of our own home-grown documentation tool.

But I need a few additional options, which I think would be useful to a lot of people:

1) The ability to exclude anything that is private. This seems really obvious to me, maybe there is already an option for that but I can't find it in the docs.

2) The ability to exclude identifiers based on a regex. For example we use the convention that anything that starts with an underscore is not public. I know we could use @internal comments for that, but a regex would be much easier to use and less error-prone.

Thank you very much for this, it's an awesome tool.

**Comment by banzor** [comment]
Hey all, just jumping in to second Bernardo's request.

Wijmo (http://wijmo.com) is written in TypeScript, but we wrote our own doc tool years ago for it.

We are planning some major updates to our doc tool, but came across TypeDoc. You have created a really nice tool! We are considering adopting it in place of our homegrown solution, and honestly, I would prefer that option.

**Comment by kamranayub** [comment]
These should be options but in the meantime you can customize the template to do this--i.e. use custom helpers to hide/show documentation based on your needs. We added support for `@obsolete`, for example by doing this.

I commented on another issue with a way to add custom helpers. #154

**Comment by Bernardo-Castilho** [comment]
HI Kamran

It sounds like you have a great solution. Seems like adding "helpers" is easy, but I could not find any documentation. What exactly is a helper, and how is it supposed to operate?

Perhaps you could share your implementation of @obsolete so we could take a look and learn from it?

Thanks in advance!

**Comment by kamranayub** [comment]
Yup, here's the commit in our fork where I added the customizations. You can see I did a couple things:

- Added copying of *.js files when building the template
- Added a new directory `helpers` with my custom helpers
- Customized the Handlebars template and SASS to add some HTML/CSS changes

After you clone the `typedoc-default-themes` repository, you have to build it using Grunt before it can be used.

You can read more about Handlebars helpers here: http://handlebarsjs.com/block_helpers.html

I might issue a PR to update the documentation on the site on how to do this, since I had to look at Typedoc's source code to figure out how to add helpers--or the default themes repo should be updated to include an example helper.

**Comment by vekexasia** [comment]
I agree that it would be nice to be able to exclude every private or not exported "thing".

I read the discurssion by my knowledge of handlebars+typedoc is just not enough for me to understand how this could be accomplished with the current implementation of typedoc.

**Comment by Gerrit0** [comment]
Closing as all the mentioned features seem to exist now, I'm not sure what existed when the issue was made (expecting regex exclude, which seems like a bad idea, you should use the TypeScript visibility modifiers)

1. `--excludePrivate` and `--excludeProtected` options exist, this should meet the `_name` convention since that should be marked as private/protected in the first place.
1. You can add `@internal` to a doc comment if a necessarily public member should only be used internally, note that members with `@internal` follow the TypeScript convention of only being stripped if `--stripInternal` is passed.
1. `--excludeNotExported` exists
