### ISSUE TITLE
io-ts type aliases are expanded in an unhelpful way

### ISSUE THREAD

**Issue by russellrobinson** [TypeStrong/typedoc#2209]
## Search terms

parameter type alias expansion io-ts

## Expected Behavior

Function parameter types should be shown as is.

## Actual Behavior

Parameter static types generated via io-ts are expanded in the documentation in a way that is unhelpful and often unreadable.

## Steps to reproduce the bug

See https://github.com/russellrobinson/typedoc-repros

NOTE: github wouldn't let me upload a branch to do a PR, so I've created a fork instead.

## Environment

-   Typedoc version: latest
-   TypeScript version: 4.9.5
-   Node.js version: 14.17.6
-   OS: linux

**Comment by Gerrit0** [comment]
That's odd, TypeScript usually sets aliasSymbol on types like that, so we can get the referenced type.

TypeDoc replicates the result of hovering over a variable of that type.  [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM53gMyhEcDkwEAtDKvgNwBQVA9AglYnAOICmAdm1MjGynFQxewAMYYAnmH7IANsDRxsuAVACuHGKH4wpbAHRMEtKmwAekWJOlwAwrjDBZbACraXegDwAlDW5CuenDmfBwAJugw+h7SnsgcEgA0KAnJGgDWHBAA7hwAfHlwALwY0XoA8pg+fu56edSmFtDwohAcQnDeLgD6LmxCAIzFpbrSABQA3kyCMFAAXKVCUMAcAOaJ0xxqIAtRWyAARtxUAL4AlDTmlvCj-H2Dw1ExbJWetxCYnT33MAP1l00rLc4D8AEzDKZwGbzaErdabbYLfZHKCnGhhNiiWTIKD8VrtG79X4LH4Dai0WhQqnUqkAPQA-FQMVicXi2h0+EJQSSiaC6JSaYKGUA)

```ts
declare const test1: Test1;
//            ^? const test1: { str: string; num: number }
declare const test2: Test2
//            ^? const test2: Test2
```

TypeDoc uses the actual type of symbols when converting things rather than the type node to properly document code like this:

```ts
class Foo extends Array<string> {}
// foo.at() should return `string`, not `T`
```

I asked in the compiler API channel in the TS discord, and first impressions was that this might be a bug.

**Comment by Gerrit0** [comment]
There isn't much TypeDoc can do to work around this, I opened https://github.com/microsoft/TypeScript/issues/53496, hopefully the TS team decides a change is warranted there.

**Comment by russellrobinson** [comment]
OK, thanks, let's hope so!

**Comment by Gerrit0** [comment]
Ryan's first response was, somewhat expectedly, that this isn't a bug. Hopefully the `satisfies` use case will nudge that decision in the other direction.

In the meantime, you can force TS, and therefore TypeDoc, to preserve a name here by creating an interface instead.

```ts
export interface Test1 extends CompileTimeType<typeof RT_Test1> {}
```

**Comment by russellrobinson** [comment]
Thanks for your suggestions.

I like to use `interface` for interfaces (i.e. contracts) and `type` for types.

(I think the TS overlap between `interface` and `type` shows indecision in the designers.  They don't actually know what they want to do.)

I have scores of these issues and I don't want to have to change all of these to handle a non-coding issue (i.e. documentation).

**Comment by Gerrit0** [comment]
Without a resolution to https://github.com/microsoft/TypeScript/issues/53496, there isn't anything typedoc can reasonably do here that isn't a horrible and very fragile hack, so unfortunately marking this as a design limitation.
