### ISSUE TITLE
TypeScript v5 missing `typeArguments` with default generics

### ISSUE THREAD

**Issue by Shinigami92** [TypeStrong/typedoc#2213]
## Search terms

- typeArguments
- generics
- TypeScript v5

## Expected Behavior

We have defined a type:
```ts
// ./types.ts
export type LiteralUnion<T extends U, U = string> =
  | T
  | (U & { zz_IGNORE_ME?: never });

// ./index.ts
export type Test = LiteralUnion<'a' | 'b'>;
```

TypeScript v4.x produced
```
type.typeArguments[0] -> "'a' | 'b'"
type.typeArguments[1] -> "string"
```

<img width="300" alt="image" src="https://user-images.githubusercontent.com/7195563/227986432-b8d0a5c5-154e-4c7f-ac2b-a759f117bd2f.png">

## Actual Behavior

TypeScript v5.x produced
```
type.typeArguments[0] -> "'a' | 'b'"
```

## Steps to reproduce the bug

Repro: https://github.com/TypeStrong/typedoc-repros/pull/27

Relevant issue: https://github.com/faker-js/faker/pull/1953

## Environment

-   Typedoc version: 0.24.0-beta.7 | 0.23
-   TypeScript version: v5.0.2
-   Node.js version: 18
-   OS: mac

**Comment by Gerrit0** [comment]
TypeDoc is converting what we get from TypeScript correctly, and this is an intentional change in TypeScript 5.0 - https://github.com/microsoft/TypeScript/pull/51771.

TypeScript still has some work to do to be consistent about when defaulted type parameters are included (see Anders' follow up comment), but from some discussion with Jake Bailey, they're far more likely to move towards not eagerly expanding alias lists than revert this change (see also https://github.com/microsoft/TypeScript/issues/52670)
