### ISSUE TITLE
Typedoc should support complex @default values

### ISSUE THREAD

**Issue by ST-DDT** [TypeStrong/typedoc#2219]
## Search terms

`@default`, complex object, jsdoc tag

## Expected Behavior

Typedoc should support complex `@default` values.

## Actual Behavior

````txt
./index.ts:12:10 - warning Encountered an unescaped open brace without an inline tag

12       * uuid({ foo: "bar" })

./index.ts:12:23 - warning Unmatched closing brace

12       * uuid({ foo: "bar" })
````

It doesn't output the warning, when using an `@example` tag.
IMO `@default` refers to a value and thus should behave the same as `@example`.

## Steps to reproduce the bug

````ts
import type { ProjectReflection, TypeDocOptions } from "typedoc";
import { Application, TSConfigReader } from "typedoc";

/**
 * Foo.
 */
export function foo(options: {
  /**
   * @example uuid({ foo: "bar" })
   */
  bar: string;
}) {
  return options.bar;
}

function loadProject(
  options: Partial<TypeDocOptions> = {
    entryPoints: ["index.ts"],
    pretty: true,
    cleanOutputDir: true,
  }
): [Application, ProjectReflection] {
  const app = new Application();
  app.options.addReader(new TSConfigReader());
  app.bootstrap(options);
  const project = app.convert();
  app.generateJson(project, "output.json");

  return [app, project];
}

loadProject();
````

## Environment

-   Typedoc version: 0.23.28
-   TypeScript version: 5.0.3, 4.9.5 (doesn't really matter)
-   Node.js version: v18.15.0
-   OS: Win10

**Comment by Gerrit0** [comment]
The `@example` tag has this special casing because JSDoc made the (bad) decision to state that its contents should be highlighted as code, and it is used to frequently for TypeDoc to make the call that its contents should not be and force people to use the [TSDoc specification of the tag](https://tsdoc.org/pages/tags/example/) 

The TSDoc [`@defaultValue`](https://tsdoc.org/pages/tags/defaultvalue/) specification examples indicate that arbitrary text should be permitted, not just the value. JSDoc's [`@default`](https://jsdoc.app/tags-default.html) implies that it's just the value.... I think the TSDoc spec is better here. Wrapping stuff that's meant to be code in backticks to actually mark it as code is a good thing.

I really don't want to do this, but wow there are a lot of matches for `@default`/`@defaultValue` in DefinitelyTyped which assume the JSDoc interpretation... It's far from universal, but there are enough that I'm leaning towards unhappily agreeing with you. I'd like to move the `@example` hackery under an option flag as well, so this might be a good excuse to finally get around to doing that....

**Comment by ST-DDT** [comment]
> I'd like to move the `@example` hackery under an option flag as well, so this might be a good excuse to finally get around to doing that....

I'm not sure how exactly you have planned that, but it might be good to be some kind of list of tags that should be treated as code. That way, it is possible to define custom tags there as well.

**Comment by Gerrit0** [comment]
I'm not sure I agree with that. Doc comments are meant to be read/rendered with an editor too, and VSCode/other editors won't know that it should be a code block. VSCode doesn't render `@default` as a code block either (but does `@example` - sometimes). Adding features which encourage writing docs that don't show up nicely in editors isn't something I want to do.

**Comment by ST-DDT** [comment]
**Code block:**
![grafik](https://user-images.githubusercontent.com/1579362/230317099-68b547c7-94c6-452c-b28e-3960da350229.png)
This looks like code highlighting to me.

**Example block:**
![grafik](https://user-images.githubusercontent.com/1579362/230317269-a476eb9f-9011-46d3-a28a-0272d7b85917.png)
This also looks like code highlighting.

**Deprecation block:**
![grafik](https://user-images.githubusercontent.com/1579362/230317539-b1b0fc7e-895d-470b-affc-19ada6d99b25.png)
Just for reference, when it doesn't show up as code.

````ts
rangeToNumber(
    numberOrRange:
      | number
      | {
          /**
           * The minimum value for the range.
           */
          min: number;
          /**
           * The maximum value for the range.
           *
           * @deprecated
           * number({ min: 10 })
           */
          max: number;
        }
  ): number
````

**Comment by Gerrit0** [comment]
You're totally right, I was going off memory from when I fixed `@example`, didn't remember seeing `@default` in there.
