### ISSUE TITLE
Get ts error outside the entryPoints

### ISSUE THREAD

**Issue by linonetwo** [TypeStrong/typedoc#2239]
## Search terms

entryPoint packages monorepo pnpm workspaces

## Expected Behavior

Only parse entryPoint, no ts error from other folders.

## Actual Behavior

```
pnpm exec typedoc

[info] Converting project at ./plugins/memeloop-plugin
packages/memeloop-ui/src/editor/index.ts:3:38 - error TS1484: 'ReactArea2D' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.
```

Note that I only want to parse `./plugins/memeloop-plugin`, but it parse `packages/memeloop-ui/` too. And ts error block the generation of `./plugins/memeloop-plugin`.

## Steps to reproduce the bug

plugins/memeloop-plugin/typedoc.json

```
{
  "$schema": "https://typedoc.org/schema.json",
  "extends": ["../../typedoc.base.json"],
  "entryPoints": ["src/index.ts"]
}
```

typedoc.json

```
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": ["plugins/*"],
  "out": "docs",
  "name": "Memeloop Docs",
  "entryPointStrategy": "packages",
  "includeVersion": true
}
```

typedoc.base.json
```
{
  "$schema": "https://typedoc.org/schema.json",
  "includeVersion": true
}
```

pnpm-workspace.yaml

```
packages:
  # core packages
  - 'packages/*'
  # plugins, each can be use as needed
  - 'plugins/*'
```

## Environment

-   Typedoc version: 0.24.1
-   TypeScript version: 5.0.4
-   Node.js version: 18
-   OS: Mac

**Comment by Gerrit0** [comment]
This is working as intended. TypeDoc depends on the TypeScript compiler API in order to get the types to include in your documentation, and if there are compiler errors TypeScript does not always follow it's API contract. There is a [skipErrorChecking](https://typedoc.org/options/other/#skiperrorchecking) option to tell TypeDoc to not check for errors.

However, if you turn that option on, and TypeDoc crashes, this is considered _not a bug_ and will not be fixed.

**Comment by linonetwo** [comment]
I see, in `exclude`'s doc

> it cannot be used to exclude files from compilation

But I have some unfinished code in the `packages` folder, which causes error. I only want to generate doc for `plugins` folder.

**Comment by linonetwo** [comment]
Anyway, I will try typedoc again after I finish the code in `packages`
