### ISSUE TITLE
Why can't I use third-party dependent types or methods？

### ISSUE THREAD

**Issue by Gilbert5210** [TypeStrong/typedoc#2262]
## Search terms

An exception occurs when using third-party dependencies

## Expected Behavior

Generate md normally

## Actual Behavior

error message:

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/17983736/234533236-64b1ae83-ffad-435f-8afc-7baa3eec9261.png">

## Steps to reproduce the bug
1. test.ts
```typescript
import type { ComponentResolver, SideEffectsInfo } from 'unplugin-vue-components/types'

export const test = (options: ComponentResolver): SideEffectsInfo => { console.log('test')}
```

typedocs.json
```json
{
  "entryPoints": ["index.ts"],
  "exclude": [
    "node_modules",
    "test/**/*.ts"
  ],
  "out": "../../docs/utilModules",
  "includeVersion": true,
  "excludeExternals": true,
  "plugin": ["typedoc-plugin-markdown"]
}
```

2. typedoc --options typedoc.json

## Environment

-   Typedoc version: 0.24.6
-   TypeScript version: 4.9.5
-   Node.js version: 16.15.0
-   OS: 
-   typedoc-plugin-markdown: "^3.15.2",

@Gerrit0 
can you help me ?

**Comment by Gerrit0** [comment]
You don't have types installed for webpack, and `@rspack/core` so importing them (indirectly through your dependency's declaration file) rightly causes type errors.

Since it looks like you don't actually use exports which depend on those types, you can probably get away with setting `skipLibCheck` to true in your tsconfig.

Note: type errors like this come from typescript, not typedoc. You'll see the same errors if you run `npx tsc --noEmit`, if that reports errors, so will typedoc.
