### ISSUE TITLE
Is there a service for automatic TypeDoc generation like in Rust crates.io?

### ISSUE THREAD

**Issue by hydroper** [TypeStrong/typedoc#2265]
## Search terms

automatic

## Question

Is there a website that automatically builds TypeDoc API documentation from NPM packages, similiar to Cargo's crates.io? I think crates.io uses Docker.

**Comment by Gerrit0** [comment]
There is not, unfortunately doing this comes with a whole host of problems that rust (and to a lesser extent, deno) don't have. I'm unlikely to ever build something like this.

1. Most packages don't ship with types... but the compiler in JS mode can infer some types from them that ought to show up.
2. Packages without types might have an `@types` package that needs to be paired with the version of the package, and it's not always clear how to do that for anything but the latest version. (And there might be more type dependencies declared with `*` versions, since that what definitely typed uses), could be mitigated by only supporting the latest version..
3. What gets used as the entry point or entry points? #1937 will enable trying to figure this out from package.json, but we don't have that yet. It's tricky to map from JS output files back to the TS files, even trickier when considering libraries that bundle their output so there isn't a 1-1 mapping.
4. If building from declaration files, we can't link to source code for the declaration. Even if declaration source maps are published, they don't include all exports for some reason, so can't be relied on.
5. ESM/CJS is terrible, and a service like this should differentiate between them.
6. A service like this should really allow interconnected docs. This is more possible since 0.24, but it's still not something that'll come for free. I think this one is relatively easy to fix via a custom link resolution plugin.

... probably way more I haven't even thought of, and an unlikely to in the middle of the night.

**Comment by flying-sheep** [comment]
sadly no longer online!
