### ISSUE TITLE
How to use Reacts FunctionComponent type?

### ISSUE THREAD

**Issue by nehalist** [TypeStrong/typedoc#2267]
## Question

When declaring components like:

```
export const Foo: FunctionComponent<{ input: string }> = ({ input }) => <>{input}</>;
```

The resulting docs states

> Defined in node_modules/@types/react/ts5.0/index.d.ts:499

And it becomes impossible to describe params. The only way I've found to add param descriptions is to extract the generic type to an interface and export this interface, which seems kinda odd.

Do I miss something here?

**Comment by Gerrit0** [comment]
It's not really possible to have good docs for `FunctionComponent` because `FunctionComponent`, despite the name, *isn't* just a function.

I recommend not using it, more details in [this pr](https://github.com/facebook/create-react-app/pull/8177#issue-353062710) for some non-typedoc-specific reasons.

```ts
export const Foo = ({ input }: { input: string }) => <>{input}</>;
```

It's probably possible to create a plugin which rewrites reflections to make it look like FC exports are declared like this... but FC is really a bad thing to begin with.
