### ISSUE TITLE
Generate documentation of the entire Typescript code base

### ISSUE THREAD

**Issue by FabienLydoire** [TypeStrong/typedoc#2282]
## Search terms

Document private code, Doxygen

## Question

Some contexts like medical device development, automotive industry, aircrafts industry etc… are highly regulated and do require that code is properly documented.

The idea is to have something similar to [Doxygen](https://www.doxygen.nl/) or [Jazzy](https://github.com/realm/jazzy) (for iOS).

According to #1657 (Generate documentation also for indirect exported Types), only the items imported from the entry points are documented by TypeDoc.

I used the `typedoc-plugin-missing-exports` but it did not produce the documentation for the entire code base.

Is there a way to properly configure TypeDoc to generate documentation of the entire Typescript code base ?
If not, are you aware of any other solution to do so ?

Thanks !

**Comment by krisztianb** [comment]
I think you best bet is to specify all files (or at least all of which you want to include in your documentation) as entry points and then maybe use [this plugin](https://www.npmjs.com/package/typedoc-plugin-merge-modules) to make the documentation more readable.

**Comment by Gerrit0** [comment]
If everything you want to document is exported, krisztainb's suggestion is the way to go. (It probably is, because if you have doc comment requirements for everything, surely you have unit test requirements too, and therefore have to export everything to unit test it, right?) TypeDoc really is meant for documenting APIs, not applications...

If that's not the case, a relatively minor update to [typedoc-plugin-not-exported](https://github.com/Zamiell/typedoc-plugin-not-exported) to include everything wouldn't be too difficult to do (and update to support more recent typedoc versions, not sure if I've broken it with the past few minor versions)
