### ISSUE TITLE
The "defined in" points to node_modules type rather than to actual code

### ISSUE THREAD

**Issue by allista** [TypeStrong/typedoc#2307]
## Search terms

defined in
node_modules
react
functional component
FC

## Expected Behavior

The **Defined in** field in generated docs should refer to the actual file where the documented function is defined, rather than the library code where its type is defined.

## Actual Behavior

The doc entry for a react functional component declared in `my-package/src/MyComponent.tsx` as follows:

```tsx
/**
* Description
* 
* @constructor
*/
export const MyComponent: FC = () => (<div>A test</div>);
```

Contains this **Defined in** section:

```markdown
Defined in

node_modules/.pnpm/@[types+react@16.9.23](mailto:types+react@16.9.23)/node_modules/@types/react/index.d.ts:519
```

It is the same for any component defined in any module this way.

## Steps to reproduce the bug

The typedoc config in `tsconfig.json`:

```json
  "typedocOptions": {
    "entryPoints": ["src/index.ts"],
    "out": "docs",
    "entryDocument": "index.md"
  }
```

Run as `typedoc --plugin typedoc-plugin-markdown`

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 4.6.4
-   Node.js version: 16
-   OS: Ubuntu
-   typedoc-plugin-markdown: 3.15.3

**Comment by Gerrit0** [comment]
Yet [another](https://github.com/facebook/create-react-app/pull/8177#issue-353062710) reason to not use `FC`... 

This happens because the signature declaration takes display priority, and the signature for that variable is defined in the types. TypeDoc should probably check [here](https://github.com/TypeStrong/typedoc/blob/master/src/lib/converter/plugins/SourcePlugin.ts#L151) if the reflection is a signature and does not share a source declaration location with its parent, in which case it should replace its source declaration with that defined on the parent.

**Comment by lukeshiru** [comment]
I notice that it also points to the wrong place when using currying, which might be related (if not I can create a new issue):

```ts
// times.ts
const times = b => a => a * b;

// double.ts
const double = times(2);
```

In previous versions of TypeDoc this generated "defined in double.ts" for `double.ts`, but now it generates "defined in times.ts".

**Comment by Gerrit0** [comment]
The fix I described above should handle both of these cases

**Comment by Gerrit0** [comment]
... well, it would, if it that didn't break in this case:
```ts
export const all: {
    <T>(fn: (item: T) => boolean, iterator: Iterable<T>): boolean;
    <T>(fn: (item: T) => boolean): (iterator: Iterable<T>) => boolean;
} = () => false as any;
```

This is trickier than I thought..
