### ISSUE TITLE
jsconfig.json support

### ISSUE THREAD

**Issue by goldingdamien** [TypeStrong/typedoc#2344]
Please, could you provide information regarding jsconfig.json support.
I was unable to find other than a few vague references.

- Is jsconfig.json supported? And if so what, if any, extra config is required to use?
- If not supported, what would I need to do to still use jsconfig.json and allow typedoc to work?
- If not supported, why? They are very similar, would be nice if it worked. Please consider as a feature.

Regards.

**Comment by Gerrit0** [comment]
Theoretically, since I believe it is the same format as a tsconfig.json, it is supported, just without autodiscovery. If you use `--tsconfig ./jsconfig.json`, I suspect everything will work as expected. If it does, we should probably consider adding automatic discovery for it to typedoc so that it isn't necessary.
