### ISSUE TITLE
Failing to resolve links after update

### ISSUE THREAD

**Issue by weboko** [TypeStrong/typedoc#2403]
## Search terms
monorepo
failed to resolve links
resolve

## Question

I am migrating from `typedoc: 0.23.26` + `typedoc-plugin-resolve-crossmodule-references: 0.3.3` to `typedoc: 0.25.1` 
And it seems I hit some interesting case when links are failing to get resolved 

![image](https://github.com/TypeStrong/typedoc/assets/118575614/0e4265c9-98ac-4e28-9b2c-464df4d2e8eb)

It is a monorepo and has the following package structure:
```
packages
├── build-utils
├── core
├── dns-discovery
├── enr
├── interfaces
├── message-encryption
├── message-hash
├── peer-exchange
├── proto
├── relay
├── sdk
├── tests
└── utils
```

Here is `typedoc.cjs` I am using - [link](https://github.com/waku-org/js-waku/pull/1528/commits/87d49cc2334eb026459588190aa28a53a9df64e3#diff-1b089057ae38172db00d02a111401121e6d1cdb97cf9554c362c7f95dcff12b9)
To me it seems a bit similar to https://github.com/TypeStrong/typedoc/issues/2360

I am wondering if it can be realted to how plugin + `legacy-packages` were working together before or due to my bad with configuring `typedoc`. 

Appreciate you help!

**Comment by Gerrit0** [comment]
Those warnings are supposed to be disabled until the final merging converted projects step... not entirely sure why I did the override before reading options instead of after.

https://github.com/TypeStrong/typedoc/blob/f2d2abe054feca91b89c00c33e1d726bbda85dcb/src/lib/application.ts#L597-L599

Assuming you didn't get warnings in the merge step, the links aren't actually broken, they're just broken in the intermediate step before all packages have been converted.

**Comment by weboko** [comment]
@Gerrit0 thank you for giving it a look
