### ISSUE TITLE
Monorepo - Cross reference to other package not resolved

### ISSUE THREAD

**Issue by theovanderdonk** [TypeStrong/typedoc#2416]
## Search terms

Cross reference other package not resolved

## Expected Behavior

When I have a monorepo with multpple packages, and I create typedoc via "packages", I expect that types defined in one package but used in another package are properly linked from the other package to the one package.

## Actual Behavior

These types do not become links, but they are plain text.

## Steps to reproduce the bug

See https://github.com/TypeStrong/typedoc-repros/pull/32
The readme contains repro steps + some additional observations.

## Environment

-   Typedoc version: 25
-   TypeScript version: 4.9.5
-   Node.js version: 18.13.0
-   OS: Windows

**Comment by Gerrit0** [comment]
The code for inherited links predates all of the work for packages mode, and it looks like I missed it when implementing that feature... I'm not seeing an immediately obvious reason why I can't switch it to use symbol references now and just see it work.

Method parameters, property types, etc. should all just work.

**Comment by theovanderdonk** [comment]
Thank you for your reply. I do not quite understand your wording. Do you mean you will investigate and try to switch to symboil references for my use cases? Or can/should I do that locally?

For method parameters, that also does not work. I have updated the example. So it appears that (at least for me) they do not 'just work'.

By the way -- compliments for the many improvements of TypeDoc over the last year or so. It is really looking much better, and monorepo also works very nice. It's just these little things I observe now :D

**Comment by theovanderdonk** [comment]
Duplicate of / closely related to new issue https://github.com/TypeStrong/typedoc/issues/2420

**Comment by personalizedrefrigerator** [comment]
For me, cross-project links work if packages have `"types"` point to a `.ts` file and not to a `.d.ts` file. See [sample project](https://github.com/personalizedrefrigerator/bug-report/tree/typedoc/broken-cross-project-links).

**Comment by personalizedrefrigerator** [comment]
I'm currently [working around this with a custom `unknownSymbolResolver`](https://github.com/personalizedrefrigerator/js-draw/blob/main/packages/typedoc-extensions/src/index.ts). It's very fragile, but it mostly works.

**Comment by Gerrit0** [comment]
Short story: You can get the behavior you want by turning on the `declarationMap` compiler option, and recompiling. In 0.25.3, you shouldn't need this compiler option anymore.

Looking at all three of #2428, #2420, #2416 when _not_ on antihistamine makes me really concerned with anything I did last week... TypeDoc already correctly creates inheritance links with cross-references as it should, so my previous statement was just flat wrong.

To determine how to link files between packages, TypeDoc needs to be able to determine what file they'll be defined in. In 0.25.2, this is completely reliant on the existence of declaration maps, which seems to only be documented in a passing mention in the beta release issue for v0.24... However, when running in packages mode, there's really no reason that TypeDoc shouldn't be able to tell where files come from for the converted packages, since we have the compiler options and the file names which will be compiled.

I'm making an update to TypeDoc which will use this to derive source file names. I was hopeful that doing this would remove the requirement to build all the packages before running TypeDoc on them, but unfortunately this isn't *quite* enough since TypeScript (at least with a references based monorepo) requires that sub-projects be built. If `emit` is set to `both` when converting earlier projects, and projects are passed to TypeDoc in the order that they need to be built, TypeDoc's emit can be used rather than a pre-build, but it's easier to tell people to just build with tsc first, particularly since TypeDoc doesn't do any project dependency tracking.

> I'm currently [working around this with a custom unknownSymbolResolver](https://github.com/personalizedrefrigerator/js-draw/blob/main/packages/typedoc-extensions/src/index.ts). It's very fragile, but it mostly works.

I am surprised that works at all, TypeDoc was *supposed* to handle escaping, but it looks like I mistakenly assumed that `\\"` wouldn't close an attribute... I'm going to fix that now...

**Comment by Gerrit0** [comment]
I suspect the declarationMap issue not working is because I forgot to test on Windows, and paths are annoying... 

The inheritance hierarchy is interesting, the way that's built today has always felt fragile to me... I'm going to look at improving it in a way which should also solve the cross-package inheritance issue.

**Comment by Gerrit0** [comment]
I've decided to pull smarter hierarchy detection out into #2467 to avoid having to read through this issue every month or so when I forget what the actual remaining work for it is. I believe this is the only open problem still.

**Comment by peabnuts123** [comment]
FWIW, even though this issue and the changelog both say `declarationMap` isn't required any more, I am still finding it doesn't work without it. However, enabling it does seem to resolve the issue 🤷‍♀️

**Comment by Gerrit0** [comment]
Please open a new issue with a reproduction
