### ISSUE TITLE
`{@link target}` syntax doesn't work within included markdown files

### ISSUE THREAD

**Issue by personalizedrefrigerator** [TypeStrong/typedoc#2419]
## Search terms

 `[[include:]]`, include, markdown, included markdown, `.md`, links, `@link`.

## Expected Behavior

Links to symbols created with `{@link symbolName}` should be rendered in included markdown files.

## Actual Behavior

`{@link ...}`s are rendered without formatting. For example,
![screenshot: link not rendered properly](https://github.com/TypeStrong/typedoc/assets/46334387/c6fe5be0-8ac6-4002-9280-8a0ba1da2a74)

## Steps to reproduce the bug

[Sample repository](https://github.com/personalizedrefrigerator/bug-report/tree/typedoc/link-in-included).

Steps:
1. Create a markdown file in a project's [markdown include directory](https://typedoc.org/options/comments/#includes)
2. Include the markdown file in the README or a documentation comment with `[[include:markdown-file-name-here.md]]`.
3. Link to a symbol using the `{@link symbolName}` in the included markdown file.
4. Link to the same symbol in a documentation comment

## Environment

-   Typedoc version: 0.25.2
-   TypeScript version: 5.2.2
-   Node.js version: v18.13.0
-   OS: Ubuntu 23.10

**Comment by Gerrit0** [comment]
Because of when include resolution happens, it isn't possible for links to be resolved. Include resolution would have to happen during conversion rather than during rendering for this to work.

I'm not entirely sure why include resolution was done there, that option was added before I started maintaining typedoc... it seems to me like it ought to happen during `Converter.EVENT_RESOLVE`, which would allow links to work. It also seems like this ought to take into account the source location of the file rather than using a hardcoded include directory... (maybe allowing the configuration of a baseUrl for non-relative imports like how node does...)

Changing any of this is breaking and would have to wait for 0.26, but an `{@include ./file.md}` could be implemented without a breaking change...

**Comment by dpthinh910** [comment]
> Because of when include resolution happens, it isn't possible for links to be resolved. Include resolution would have to happen during conversion rather than during rendering for this to work.
> 
> I'm not entirely sure why include resolution was done there, that option was added before I started maintaining typedoc... it seems to me like it ought to happen during `Converter.EVENT_RESOLVE`, which would allow links to work. It also seems like this ought to take into account the source location of the file rather than using a hardcoded include directory... (maybe allowing the configuration of a baseUrl for non-relative imports like how node does...)
> 
> Changing any of this is breaking and would have to wait for 0.26, but an `{@include ./file.md}` could be implemented without a breaking change...

Hi @Gerrit0 , do you have any ETA for this feature? I have just upgraded my project to `typedoc@0.25.4` and `typescript@5` and there's no way I can use the `@link` tag inside the included markdown content

**Comment by Gerrit0** [comment]
No, I avoid ETAs as they're a great way to disappoint people. The include option has also always felt like a bad hack to me as the content of those markdown files will not appear in VSCode.

**Comment by dpthinh910** [comment]
Thanks for sharing your opinion, a/w do you have any idea to achieve this feat? Before this upgrade i was using 0.17 and everything works fine with the monorepo-links plugin

**Comment by Gerrit0** [comment]
In 0.26, the `--includes` option has been replaced with a `@document` tag to add additional markdown pages to the generated site, and `@link` works there,
