### ISSUE TITLE
cross-package re-export fails to resolve definition

### ISSUE THREAD

**Issue by teidesu** [TypeStrong/typedoc#2428]
## Search terms

When using `"entryPointStrategy": "packages"` in a monorepo where one package re-exports something from another one, links to definition are not correctly resolved:
<img width="329" alt="image" src="https://github.com/TypeStrong/typedoc/assets/86301490/a115953f-2e33-4097-bbcc-d3600956929f">

Additionally, the `extends` clause links to the re-exported definition instead of the imported one (idk if this is expected, though):
<img width="666" alt="image" src="https://github.com/TypeStrong/typedoc/assets/86301490/908c601e-0d65-4530-b0c4-b01ad931385f">

## Expected Behavior

Links to definition are correctly resolved, and `extends` links to the original definition

## Actual Behavior

Links to definition are not correctly resolved, and `extends` links to re-exported definition

## Steps to reproduce the bug
https://github.com/TypeStrong/typedoc-repros/pull/33

## Environment

-   Typedoc version: 0.25.2
-   TypeScript version: 5.2.2
-   Node.js version: 18.12.1
-   OS: macOS 13.5

**Comment by Gerrit0** [comment]
Thanks for the repro! This appears to be the same issue as #2416 for your first issue, so I'm going to track that over there.

The cross-package re-export issue unfortunately I do consider to be working as intended. There isn't a good way for TypeDoc to track that a symbol has been exported from another package, particularly since packages mode is really designed to be a thin wrapper around rendering each package to JSON and then merging the packages.

I'd recommend changing the configuration for `packages/outer` to be:

```json
{
  "entryPoints": ["./index.ts"],
  "excludeExternals": true,
  "externalPattern": ["**/dist/**"]
}
```

And then, once #2416 is fixed, that should link between packages as expected.
