### ISSUE TITLE
How to link to certain item from external website?

### ISSUE THREAD

**Issue by theovanderdonk** [TypeStrong/typedoc#2432]
## Search terms

External link stable url

## Question

I want to link from my regular website to one specific class/interface/type from my generated typedoc documentation.
I do not like the cryptic URL's like `mydocumentationsite.com/classes/_my_package_name.MyClassName.html`

One reason for that is that these names may change over time (when typedoc chooses a different file name structure).

Is there a way to use "stable URLs" that remain the same over time?
For example: `mydocumentationsite.com?item=MyClassName

Perhaps I can use the search functionality for that (but I find no way to set the "search value" via the link as part of the anchor or as a search param)?

Is this functionality available?

**Comment by Gerrit0** [comment]
Generic "stable" urls I guess could be done by fully specifying the path and type, but just specifying "MyClassName" isn't necessarily enough...
- The class could be merged with a namespace, so TypeDoc would have to pick one
- There could be multiple items with the specified name under different modules/namespaces. `item=constructor` would do... what?

Setting the search would work for some items, but there isn't always a way to get every item as the first search result. If I wanted to link to https://typedoc.org/api/classes/Application.html#entryPointStrategy for example, searching `entryPointStrategy` shows the enum sharing that name first, and including "dotted names" in search doesn't work due to them not being in the search index (adding it would likely at least double the size of that output, which can already get big for large projects).

My goal for link generation is that file names / anchors should not change in patch versions, only during major bumps, so it is generally safe to link to that url, and if it will be broken, that will be called out in the release notes.
