### ISSUE TITLE
@example tag titles cannot be derived from CommentTag type

### ISSUE THREAD

**Issue by achingbrain** [TypeStrong/typedoc#2440]
## Search terms

- example tag
- title

## Actual Behavior

The tsdoc website [says](https://tsdoc.org/pages/tags/example/):

> Any subsequent text that appears on the same line as the `@example` tag should be interpreted as a title for the example.

The example is parsed as a [CommentTag](https://typedoc.org/api/classes/Models.CommentTag.html) which has `content` and `tag` fields and an optional `name` field.

Any text on the same line as the `@example` tag appears in the `content` list along with any other text.

E.g.

```
/**
 * @example This is how to do a thing
 *
 * Here is some more explantation.
*/
```

Becomes:

```js
{
  tag: "@example",
  content: [{
    kind: "text",
    text: "This is how to do a thing\n\n"
  }, {
    kind: "text",
    text: "Here is some more explantation.\n\n"
  }]
}
```

So it's impossible to tell if there was a title for the example.

## Expected Behavior

The [CommentTag.name](https://typedoc.org/api/classes/Models.CommentTag.html#name) field docs say:

> Some tags, (`@typedef`, `@param`, `@property`, etc.) may have a user defined identifier associated with them. If this tag is one of those, it will be parsed out and included here.

So if present, the example title should probably be in the `name` field?

```js
{
  tag: "@example",
  name: "This is how to do a thing",
  content: [{
    kind: "text",
    text: "Here is some more explantation.\n\n"
  }]
}
```

## Environment

-   Typedoc version: 0.25.3
-   TypeScript version: 5.2.2
-   Node.js version: 20.8.0
-   OS:  Mac OS X 13.5.1

**Comment by Gerrit0** [comment]
This seems like a reasonable way to handle things :+1: JSDoc `<caption>`s should be put there too.

**Comment by Gerrit0** [comment]
Hmm... and what happens if there's a `{@link}` in the first line? `name` is a string, so can't support complex content.

VSCode doesn't support this idea as a thing, just rendering it on the next line after the block.

![image](https://github.com/TypeStrong/typedoc/assets/19329837/52553563-5edc-46f8-8206-f7d324cd2810)

Since TS doesn't even parse `@link` tags in `@example` blocks, it's *probably* reasonable to assert that they just can't appear there, and will be treated as regular text, but that feels ugly. The alternative is a new `heading?: CommentDisplayPart[]` attribute on `CommentTag`... which feels ugly. I'm leaning towards `name` right now, and emitting a warning if the heading contains rich content. Going to let this one sit for a while before deciding...

If you toss an `@example` block with a heading into https://tsdoc.org/play/, the official parser's AST doesn't place it somewhere you can tell either. It [looks like](https://github.com/microsoft/tsdoc/issues/20#issuecomment-1752117491) I'm not the first to notice this. API extractor (the "official" tsdoc documentation generator written by the microsoft people who wanted TSDoc to begin with) [doesn't mention](https://api-extractor.com/pages/tsdoc/tag_example/) this feature in their docs either, so I suspect don't support it

**Comment by achingbrain** [comment]
>  I'm leaning towards name right now, and emitting a warning if the heading contains rich content.

This seems reasonable to me.  I guess any more might need a change to the tsdoc specs?
