### ISSUE TITLE
Use flexsearch instead of lunr

### ISSUE THREAD

**Issue by gaurishhs** [TypeStrong/typedoc#2441]
## Search Terms

Using [`FlexSearch`](https://github.com/nextapps-de/flexsearch) instead of lunr.js

## Problem

TypeDoc uses lunr which is actually slow when there are a lot of documents. 
Flexsearch is the fastest available local-search option for Javascript ecosystem.

## Suggested Solution

Migrating to flexsearch

**Comment by Gerrit0** [comment]
Do you have an example of a project where this is actually a problem? I've never noticed issues with lunr... as an experiment, I just ran TypeDoc on `@types/node`, with search in comments turned on, which results in a gzipped search index of 1.7mb containing ~10k items. With this, search is so fast as to appear instantaneous to me.

**Comment by gaurishhs** [comment]
I think it was because i was using typedoc with a local server (recompile
on file change) so it kept saying search index loading. If you look at the
benchmarks (https://nextapps-de.github.io/flexsearch/bench) though
flexsearch performs the best and consumes way less memory

**Comment by Gerrit0** [comment]
Unless flexsearch has a significantly smaller serialized index, switching wouldn't help there. That shows up when search.js containing the index hasn't loaded yet.

I looked at flexsearch's api, and it's feature set is also missing some things which typedoc uses in lunr. There doesn't appear to be any way to boost individual documents so that they show up first in search results. This is important for the searchCategoryBoosts and searchGroupBoosts options.

**Comment by gaurishhs** [comment]
> There doesn't appear to be any way to boost individual documents so that they show up first in search results

There is the boost function in [IndexOptions](https://github.com/nextapps-de/flexsearch#index-options)

**Comment by Gerrit0** [comment]
That's different than boosting documents
