### ISSUE TITLE
Strange re-export behavior with @namespace

### ISSUE THREAD

**Issue by jpolo** [TypeStrong/typedoc#2444]
## Expected Behavior

Expectation 1 :
When a namespace extends some type, I expect two possible behaviors : the documentation is copied OR the documentation forwards to the parent class / type / interface.

Expectation 2:
In my case, the namespace is a specialisation of the type (i.e. a generic type bound to a specified type parameter)
Simply re exporting would lose the type information, which can lead to an unclear generated doc.

## Actual Behavior

The doc of a given namespace  (repro "Number") re exports another namespace (repro : "Boolean") instead of the parent namespace (repro : "Comparable"). 

Also, it should not "lose" type parameters. (= Re export link might not be sufficient)

## Steps to reproduce the bug
The doc 

https://w5s.github.io/std/api/core/namespace/Number#==

The repo 

https://github.com/w5s/std

## Environment

-   Typedoc version: 0.25.3
-   TypeScript version: 5.x
-   Node.js version: 20.x
-   OS: macOS

Thanks again for your great project 👍

**Comment by Gerrit0** [comment]
Huh, that's weird, those symbols ought to be different, and not be caught by the reference creating code...

**Comment by Gerrit0** [comment]
Shoot... it is different, but the code I added in 0.24 to support resolving references across compiler instances works by checking declarations, and all instances share the declaration and therefore get treated as the same. I *think* the fix for this is to check `symbol.flags & ts.SymbolFlags.Transient` and do something special in that case... maybe...
