### ISSUE TITLE
Reflection w/ Empty Signatures Array Outputs as Deprecated

### ISSUE THREAD

**Issue by nruffing** [TypeStrong/typedoc#2448]
## Search terms

declaration signatures
deprecated

## Expected Behavior

I have a local plugin that is parsing comments off of type declarations for a Vue single file component. The plugin currently is always adding an array to a reflections signatures property even if its empty.

I would expect that the signatures array being undefined or an empty array would result in the same behavior and not treat the reflection as deprecated.

## Actual Behavior

Currently the [`Reflection.isDeprecated`](https://github.com/TypeStrong/typedoc/blob/aba0ef85a9b57ff9bc8e7fa2f4c19b48bdb3c0ca/src/lib/models/reflections/abstract.ts#L486C30-L487C30) implementation uses `every` and so will tag the reflection as deprecated if the signatures array is empty.

I am going to set it back to undefined when empty in my plugin but that does seem like a bug.

Do we know if this was designed to work this way? If not, I am happy to put up a pull request with a fix.

## Environment

-   Typedoc version: 0.25.3
-   TypeScript version: 5.2.2
-   Node.js version: 18.18.0
-   OS: macOS 14.1.1

**Comment by Gerrit0** [comment]
I'm certainly not opposed to this change, but... there is quite a lot of code in TypeDoc which assumes that if a possibly-undefined array exists, it isn't empty. If changing it in this place, I'd really want it to be consistent everywhere.

**Comment by nruffing** [comment]
If it has always worked this way and is consistent that may be the reason to leave it as-is. It was just unexpected and took a little bit of debugging to figure out why I was getting deprecated properties after updating to the latest prerelease of `typedoc-plugin-markdown` which just added deprecated rendering support.

If you do decide to make this change I am happy to help and it be an excuse to more about how typedoc works. Otherwise, I think we can close this as-designed.

**Comment by Gerrit0** [comment]
It's semi-consistent, there's a fair number of places in TypeDoc that always have an array. I'd honestly prefer if everything worked that way, as the extra null checks are frequently annoying...

**Comment by Gerrit0** [comment]
That's definitely what I was looking for, but the test results are making me nervous, primarily because this is the type of change which isn't caught by the compiler (maybe some ESLint rule could help?) It's unfortunate, but this would likely also cause silent breakages in many plugins... 

I think I'd want to keep the empty/nullable properties in the JSON output, at least for the first pass at this, as ideally I'd like to avoid breaking changes to that for anyone who uses `--entryPointStrategy merge`.

**Comment by Gerrit0** [comment]
I think it's still worth pursuing this, particularly since the silent breakages I'm concerned about are [already present](https://github.com/TypeStrong/typedoc/blob/master/src/lib/models/reflections/project.ts#L118C14-L118C14) due to TypeDoc itself not being consistent with how it handles empty/undefined arrays.

**Comment by Gerrit0** [comment]
I looked at integrating your changes into TypeDoc, and have decided that it doesn't make sense to generally make this change. There are places in TypeDoc where it really makes more conceptual sense to model an empty array as not present. The most obvious place is groups/categories. In this case, a reflection will *never* have both of these properties, so it seems silly for both to be set to empty arrays to me...

I'm still going to make the change to isDeprecated, and also make changes to removeReflection to properly clean up empty collections.
