### ISSUE TITLE
How to suppress the output of certain things

### ISSUE THREAD

**Issue by iiian** [TypeStrong/typedoc#2462]
I'm trying to use `typedoc` to generate configuration docs for less-than-technical people who mostly just manage configuration files. 

My generation command is pretty simple:

```bash
> typedoc src/helper/types.ts
```

Having stuff like 

> Defined in types.ts:135

scattered throughout the documentation actually potentially serves as a distraction and a stumbling block for people who are scared to death of anything that looks remotely technical (yes it is stupid you're absolutely right, trust me, but such is reality for these people without CS degrees). I'd like to omit these `defined in` receipts from my generated docs. Is this possible with `type-doc`?

Similarly, I've tried using both `interface` and `type`, and have found some odd discrepancies that I can't seem to answer myself based on the way the typedoc.org documentation is organized.

1) The header of my `interface` page looks like:

> # Interface MyConfigProps
> ```typescript
> interface MyConfigProps {
>   prop1: string;
>   prop2: OtherDomainConfigProps;
> }
> ```

I'd love this to look more like:

> # MyConfig
> ```yaml
> # a yaml example
> prop1: string;
> prop2: OtherDomainConfigProps;
> ```

or if that's not possible, perhaps just suppress this stuff altogether and take the `@example` annotation my code has in combination with the list of properties.

2. Finally, I **really** like the UI that gets presented for `interface`s, but cannot understand why the doc UI looks different when I change those same `interface`s to `type`s. Is there a way that I can get the `interface` documentation UI look & feel with a `type` and if not, why? I'd really like my developer preference for using `type` over `interface` not carry visual consequences on my documentation's look & feel.

Thanks

**Comment by Gerrit0** [comment]
> Defined in types.ts:135

[`--disableSources`](https://typedoc.org/options/input/#disablesources)

> I'd love this to look more like:

Possible via a [custom theme](https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md) which overrides the [reflectionPreview](https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/themes/default/DefaultThemeRenderContext.ts#L121-L129) hook, not something I'm going to add an option for, it'd be easy to override that hook to do nothing as well.

> cannot understand why the doc UI looks different when I change those same interfaces to types.

Because types are **not** the same as interfaces. The renderer for `type` pages has to be sufficiently flexible to handle every possible type, including conditional types, indexed access types, intersections, unions.... adding special casing to make it "look like" an interface in some cases isn't worth the time, since experience has shown me that nobody agrees completely in what "looks like" an interface means. I tried a few times, before ending up with the [`@interface`](https://typedoc.org/tags/interface/) tag, which will make TypeDoc convert a type as if it was an interface.
