### ISSUE TITLE
Mixins, 2024 Version

### ISSUE THREAD

**Issue by BrucePerens** [TypeStrong/typedoc#2465]
It's almost 2024, and the examples in https://www.bryntum.com/blog/the-mixin-pattern-in-typescript-all-you-need-to-know-part-2/ don't work any longer, and the GitHub site the article refers to is gone. There are any number of mixin patterns. Is there one that is actually _documented_ to work with Typedoc?

This is what I'm doing, and I _don't_ get documentation of the class methods.
``` JavaScript
type MixinConstructorArguments = any[]; // To limit the appearance of `any` in my code to this one place.

class CustomElement {
  constructor(...args: MixinConstructorArguments) {
      super(...args);
   }
};

type Constructor<T = {}> = new (...args: MixinConstructorArguments) => T;
type CustomElementConstructor = Constructor<CustomElement>;

function BBox<Parent extends CustomElementConstructor>(parent: Parent) {
  return class extends parent {
    constructor(...args: MixinConstructorArguments) {
      super(...args);
    }
}
```

**Comment by Gerrit0** [comment]
Mixins 2024: Still as completely and utterly awful as mixins, anytime. They are the single worst pattern to deal with in the compiler API, break things in the most unique and unexpected ways, and that hasn't changed.

Despite this, because TypeDoc uses the compiler API to extract types and get members of classes, you *will* get method documentation on subclasses which use the mixin. `class Foo extends BBox(CustomElement) {}` gives you a class which will have documentation for methods declared on both the CustomElement class and the mixin class in Bbox. This should be the case no matter what mixin implementation you decide to use.

**Comment by BrucePerens** [comment]
Thanks for explaining! In a perfect world, it would have documented the mixin separately and provided a link to it in the documentation for the derived class. 

Count my vote for a `mixiin` keyword. Making it first-class might be the best way to fix it.
