### ISSUE TITLE
SourcePlugin fails to get command line arguments when using entryPointStrategy packages

### ISSUE THREAD

**Issue by doitian** [TypeStrong/typedoc#2477]
## Search terms

entryPointStrategy, packages, workspace

## Expected Behavior

Typedoc should report error when only `--disableGit` is provided and entryPointStrategy is set to `packages`.

## Actual Behavior

The command succeeds as `--disableGit` has not been set.

The problem does not occur when removing typedoc.json or using entryPointStrategy other than `packages`.

## Steps to reproduce the bug

The repo for reproducing the bug: <https://github.com/doitian/typedoc-source-plugin-issue>

```
pnpm install
pnpm typedoc --disableGit
```

## Environment

-   Typedoc version: 0.25.6
-   TypeScript version: 5.2.2
-   Node.js version: 21.5.0
-   OS: macOS 14.2.1

**Comment by Gerrit0** [comment]
This is working as expected -- packages mode works by effectively running TypeDoc in each of your packages with the typedoc configuration in that package, and then merging the results together. This is so that each package can have custom options.

CLI arguments are not read by each package because configuration like `--out` or `--json` are commonly provided on the command line, and only apply to the final generation.

**Comment by doitian** [comment]
## More Context

I attempted to run typedoc in Vercel but could not get the source link work. However, I discovered that the git directory and git command are still accessible in the Vercel build environment. Unfortunately, Vercel does not automatically add the git remote for the repository. To resolve this, I can set the appropriate git remote for Vercel. For instance, I can do this in the typedoc.config.js file.

```javascript
if (process.env.VERCEL !== undefined) {
  const { execSync } = require("node:child_process");
  const remote = `https://github.com/${process.env.VERCEL_GIT_REPO_OWNER}/${process.env.VERCEL_GIT_REPO_SLUG}.git`;
  execSync(`git remote add origin ${remote}`);
}
```
