### ISSUE TITLE
issues about #2479

### ISSUE THREAD

**Issue by steve02081504** [TypeStrong/typedoc#2503]
## Search terms

marge

## Behavior

I tried updating the d.ts file of jsstp to try the new features added in 0.25.8 about #2479, and it looks like there are still some details that may need to be fixed
https://ukatech.github.io/jsstp-lib/doc/EN/classes/ghost_events_queryer_t.html

1. Duplicate constructors
  Somehow there are two constructor declarations for this type, even though they have exactly the same content
  https://ukatech.github.io/jsstp-lib/doc/EN/classes/ghost_events_queryer_t.html#constructor
2. The [call operator](https://github.com/ukatech/jsstp-lib/blob/b94087b/src/.decls/cn/types/ghost_events_queryer_t.d.ts#L70) is not recorded on the page
  It looks like when there is a variable and a type with the same name that both is marked as class, Typedoc will only use the variable to generate the page, and I prefer it to reference the type or both.
3. Inherited members are not marked as Inherited
  Members inherited from the `ExtensibleFunction` type are not marked as inherited.

## Steps to reproduce the bug

code: https://github.com/ukatech/jsstp-lib/tree/b94087beefedae3f52d46644718bbd12eb1aba10/src/.decls/en

## Environment

-   Typedoc version: `^0.25.8`
-   TypeScript version: idk
-   Node.js version: `latest`
-   OS: `ubuntu-latest`

**Comment by Gerrit0** [comment]
Please provide minimal reproductions of problems. I don't have time to spend hunting through your project to extract them and get rid of the unnecessary noise.

**Comment by steve02081504** [comment]
> Please provide minimal reproductions of problems. I don't have time to spend hunting through your project to extract them and get rid of the unnecessary noise.

```ts
declare class base{
	int a;
}

declare class class_impl extends base {
	constructor(a: int);
}
type call_signature = {
	(a: int): int;
}
type constructor_impl = {
	new(a: int): my_class;
}
/**
 * @class
 */
declare const my_class: typeof class_impl & constructor_impl;
/**
 * @class
 */
type my_class= class_impl & call_signature & {
	constructor: typeof my_class;
}
```

this may work

**Comment by Gerrit0** [comment]
1. Duplicate constructors - This is working as intended. TypeDoc is accurately representing that your class type *does* have two construct signatures. If you want to hide one of them, you can do this with `/** @hidden */` on either the constructor declaration, or the `constructor_impl`'s `new` declaration.

2. Call signature - This is a design limitation. TypeDoc uses the *first* constructor signature to determine what the type of the class is. Because you declared `my_class` as `typeof class_impl & ...`, the constructor signature on your implementation class was used, which does *not* have a call signature. If you swapped the order of the intersection, TypeDoc would include the call signature. (Note: Using `@hidden` on the class's constructor doesn't prevent TypeDoc from using it to determine the type here)

3. Inheritance only works for real classes. If you look at the docs for `class_impl`, you'll see that inheritance works as expected there. With `my_class`, there is no `extends` clause to look at to determine what the base classes are. I'm going to consider this a design limitation as well.

> Typedoc will only use the variable to generate the page, and I prefer it to reference the type or both.

Yes, that's correct. I very intentionally decided to use the variable here, because that's what users will deal with. If that type isn't correct, they're going to have a bad time trying to use your types to work with real values. I have no plans to change this.

With the example you've provided, I'd strongly recommend using a real class declaration with declaration merging in your types instead of this jumble of intersections.

```ts
export interface my_class {
    constructor: typeof my_class;
    (a: number): number;
}
export declare class my_class extends base {
    constructor(a: number);
}
```

(Also, sidenote, don't use `Number` as a type. That refers to an instance of the `Number` class, as in `new Number(123)` rather than a number literal [TS docs](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#number-string-boolean-symbol-and-object))

**Comment by Gerrit0** [comment]
I copied your "code 1" into a new file, added an empty `class base {}`, and ran typedoc, the signature is displayed at the top of the class's page (before the index)

In "code 2" -- TypeDoc doesn't use `type`s when converting a variable as a class, you need to swap the order in the variable declaration.

```ts
declare const my_class: constructor_impl & typeof class_impl;
```

**Comment by steve02081504** [comment]
Sorry it looks like I misread it before.
Thanks for clearing that up and have a nice day!
