### ISSUE TITLE
How to apply `@inheritDoc` tag to all classes without inheriting the `@deprecated` tag from parents

### ISSUE THREAD

**Issue by bracesproul** [TypeStrong/typedoc#2526]
## Search terms

inherit doc inheritdoc custom plugin

## Question
How can I add the `inheritDoc` jsdoc comment inside a custom plugin, unless the class is already marked as deprecated? Additionally, I don't want to inherit `@deprecated` tags from parent classes because sometimes we deprecate a specific class/interface, however it's children are not deprecated. I currently have this code inside `application.converter.on(Converter.EVENT_CREATE_DECLARATION)` and even though it logs that it's adding `@inheritDoc` to classes, when I actually build the app none of the classes it said it added to are inheriting.

```typescript
if (reflection.kind === ReflectionKind.Class) {
  const commentTag = new CommentTag("@inheritDoc", []);
  if (reflection.comment) {
    const isDeprecated = reflection.comment.blockTags.find(
      (tag) => tag.tag === "@deprecated"
    );
    const parent = reflection.parent;
    if (parent && checkParentIsDeprecated(parent)) {
      // no-op
    } else if (!isDeprecated) {
      console.log("Adding comment tag for", reflection.name);
      reflection.comment.blockTags.push(commentTag);
    }
  } else {
    const parent = reflection.parent;
    if (!parent || !checkParentIsDeprecated(parent)) {
      // No comment already existed, add a new comment with `@inheritDoc` tag
      reflection = new DeclarationReflection(
        reflection.name,
        ReflectionKind.Class,
        reflection.parent
      ).comment = new Comment(undefined, [commentTag]);
    }
  }
}
```

This is in reference to an open source project, you can find the PR trying to implement this [here](https://github.com/langchain-ai/langchainjs/pull/4795/files)

**Comment by Gerrit0** [comment]
TypeDoc has a [`Reflection.isDeprecated`](https://typedoc.org/api/classes/Models.Reflection.html#isDeprecated) method to check if a reflection or any of its parents are deprecated. (note: The `.parent` does *not* refer to parent classes. It refers to the reflection containing this class, which will be some module/namespace, if you want to check parent class you want the `.extendedTypes`)

Your PR title "Inherit class properties from parent classes" is confusing, as TypeDoc will do that without `@inheritDoc`...

```ts
reflection = new DeclarationReflection(
        reflection.name,
        ReflectionKind.Class,
        reflection.parent
      ).comment = new Comment(undefined, [commentTag]);
```
This is going to do very bad things. Creating a new reflection requires that the reflection be registered with the project so that it can be linked to. You also don't actually want to do this here, the reflection already exists.

A few things to consider:

1. Doing this check at `EVENT_CREATE_DECLARATION` is too early. The parent class might not have been converted yet if the child is exported from a module in such a way that it is processed first. You should instead perform this check on `EVENT_RESOLVE_BEGIN` with a high priority so that it happens before `@inheritDoc` resolution.
2. If the parent class is deprecated, and the child class doesn't have a comment, you need to add a comment so that TypeDoc doesn't implicitly inherit the comment from the parent class, thereby marking the child class deprecated.
3. TypeDoc has an [`isDeprecated`](https://typedoc.org/api/classes/Models.DeclarationReflection.html#isDeprecated) method which checks for `@deprecated` on the class + its parents (`.parent`)
4. `@inheritDoc` is kind of an ugly method because what it does depends how it is formatted in an attempt by TypeDoc to support both TSDoc and JSDoc style comments... if you know what you want, it might be better to copy the comment (or pieces of the comment) rather than telling TypeDoc to do it.

With this in mind, I think something like the following does what you want:

```ts
// @ts-check
import td from "typedoc";

/** @param {td.Application} app */
export function load(app) {
    app.converter.on(td.Converter.EVENT_RESOLVE_BEGIN, addInheritDoc, null, 1000);
    app.converter.on(td.Converter.EVENT_RESOLVE_BEGIN, () => {
        // In case we're running in watch mode, we should clear these to avoid leaking memory.
        isDeprecated.clear();
        visited.clear();
    });

    /** @type {Set<td.Reflection>} */
    const visited = new Set();

    /** @type {Set<td.Reflection | undefined>} */
    const isDeprecated = new Set();

    /** @param {td.DeclarationReflection} refl */
    function getParentClass(refl) {
        for (const type of refl.extendedTypes || []) {
            const ref = type.visit({
                reference(ref) {
                    return ref.reflection;
                },
            });
            if (ref) return ref;
        }
        return undefined;
    }

    /** @param {td.DeclarationReflection} refl */
    function needsVisit(refl) {
        if (visited.has(refl)) return false;
        for (const type of refl.extendedTypes || []) {
            if (
                type.visit({
                    reference(ref) {
                        return ref.reflection?.kindOf(td.ReflectionKind.Class) && !visited.has(ref.reflection);
                    },
                })
            ) {
                return false;
            }
        }
        return true;
    }

    /** @param {td.Context} context */
    function addInheritDoc(context) {
        const allClasses = /** @type {td.DeclarationReflection[]} */ (
            context.project.getReflectionsByKind(td.ReflectionKind.Class)
        );
        let queue = allClasses.filter(needsVisit);

        // There's probably some smarter way to do this iteration so that we
        // visit parent classes before child classes... but this works.
        while (queue.length) {
            for (const refl of queue) {
                visited.add(refl);
                if (refl.isDeprecated()) isDeprecated.add(refl);

                const parentClass = getParentClass(refl);
                if (!parentClass) continue;

                if (isDeprecated.has(parentClass)) {
                    // Ensure this class has a visible comment so TypeDoc doesn't automatically
                    // inherit the comment. TypeDoc considers a comment to be "visible" if it
                    // has any text or block tags.
                    if (!refl.comment?.hasVisibleComponent()) {
                        refl.comment ||= new td.Comment();
                        refl.comment.summary = [{ kind: "text", text: " " }];
                    }
                    continue;
                }

                // Use @inheritDoc to copy the comment from the parent class:
                refl.comment ||= new td.Comment();
                refl.comment.blockTags.push(new td.CommentTag("@inheritDoc", []));

                // Or copy whatever you're interested in from the parent class's comment
                // You may want to do this instead of adding an @inheritDoc tag so that
                // you can copy only part of the comment if desired.
                // refl.comment.summary = parentClass.comment.summary
                // refl.comment = parentClass?.comment?.clone();
            }

            queue = allClasses.filter(needsVisit);
        }
    }
}
```

**Comment by bracesproul** [comment]
Thanks for your in depth reply @Gerrit0! One quick question though, you say classes by default inherit their parent methods. However that doesn't seem to be the case for our project's typedoc build. For example we have [this class](https://api.js.langchain.com/classes/langchain_mongodb.MongoDBAtlasVectorSearch.html) which extends `VectorStore`, however it doesn't show any of the methods which are present on `VectorStore` but that are not implemented on the class I linked. Any idea why this might be?

**Comment by Gerrit0** [comment]
Given that the hierarchy at the top of the page links to a page which is just `Toolkit: any`... I suspect that's your issue. However `Toolkit` is defined when TypeDoc is run doesn't have types.
