### ISSUE TITLE
Can typedoc collect comments in a function body?

### ISSUE THREAD

**Issue by zhangyuinfinite** [TypeStrong/typedoc#2540]
## Question

Can typedoc collect comments in a function body? For example, the source code is as follows:
```
 /** Here's an example */
  function demoFunc(x, y) {

     const sum = x + y;
    // If sum > 0 function returns sum, otherwise the function returns -1
    if (sum>0) {
        return sum;
    } else {
        return -1;
    }
 }
```

I want typedoc to collect comments that contain ` If sum > 0 function returns sum, otherwise the function returns -1 `;
If typedoc is not currently supported, can I implement it by developing a typedoc plugin?

**Comment by Gerrit0** [comment]
Not supported by TypeDoc, you could write a plugin to do this, however. Doing so is going to be rather annoying because TypeScript doesn't have any API to do this, so you'd have to do it yourself.

For the TypeDoc part of this, listen to [`Converter.EVENT_CREATE_SIGNATURE`](https://typedoc.org/api/classes/Converter.html#EVENT_CREATE_SIGNATURE)

For the TypeScript comment collection, you'll probably need `node.forEachChild` to recurse through the function's body, if you care, this will also need to recurse... this should get you started:

```ts
node.body.forEachChild(node => console.log(ts.getLeadingCommentRanges(sourceFile.text, node.pos)))
```

I highly recommend [ts-ast-viewer](https://ts-ast-viewer.com/#code/AQegVGwBIKYE4wOQGdgEMB2wYA80FsAHAGxmDBAChhgAzAVwwGMAXASwHssATGfDgGKMmAChwAaYAE8AlMADelajRpMuyFsGT18wALzAcwANTSA3MpogQwAJK0tO4AD5gABjrD2XYAhb04DFRtfEkOFgALeAB3NmQySLIGZm8sPwCg4ABaAEZLYDYHERDnNzlFFUrfGH9Ax3wLSoBfbGJ4hXzK9LrcxpUm6iagA) for experimenting with what's available on a node.

**Comment by Gerrit0** [comment]
https://www.npmjs.com/package/typedoc-comments I ran across this today, looks like it might do what you're after
