### ISSUE TITLE
Suggestion: Custom footer string

### ISSUE THREAD

**Issue by nicfv** [TypeStrong/typedoc#2559]
## Search Terms

custom, footer, string, hide, generator

## Problem

By using the `--hideGenerator` option, the message "created by TypeDoc" is removed, but the footer is still there. It might be nice to include an option to customize what is written in the footer instead.

## Suggested Solution

`--footer "<span class="...">should support html</span>"`

**Comment by Gerrit0** [comment]
Sure, seems like an easy customization to allow

**Comment by Aryakoste** [comment]
Hello @Gerrit0. I would like to work on this issue.

**Comment by Gerrit0** [comment]
Go for it!

**Comment by xuhdev** [comment]
There's already a plugin for this: https://typedoc-extra-footer.8hob.io/

**Comment by mayank1513** [comment]
> There's already a plugin for this: https://typedoc-extra-footer.8hob.io/

Please don't avoid adding any features because there is a plugin. Plugins don't work with all versions of Typedoc

**Comment by xuhdev** [comment]
I don't oppose adding this feature to typedoc, (although architecture-wise I think typedoc should leave these kinds of specialized theme customization options to plugins, even as builtin ones.)

However, as the author, I think the behavior defined in the plugin above is better designed. Specifically,

- If the custom footer and `--hideGenerator` are both specified, don't hide the custom footer. Instead, add the custom footer after the generator text.
- Add a default style if the customer footer is plain text. This permits users with not much HTML and CSS knowledge to use without struggling making the footer look reasonable.

What do you think?

**Comment by mayank1513** [comment]
I am more interested in adding markdown pages to the documentation.

As of now, I just employed a quick hack - https://react18-tools.github.io/react18-global-store/

But, I believe that this is a very important part of documentation and should be supported by the library.

**Comment by Gerrit0** [comment]
In general, I agree with @xuhdev, the more specialized functionality I can push to plugins, the easier to maintain TypeDoc itself stays, which makes it easier to maintain. I also mostly agree with the builtin plugin approach, though unfortunately it is messier than I'd like due to other constraints (options are all declared in one place for TypeDoc so that http://typedoc.org/schema.json can be easily generated, in 0.26 option descriptions are translated, and I'd really like to not spread the translatable strings all over the place to make it easier for translators)

That said, having worked places where getting plugins for approved software was a nightmare, I think it's important that it be easy to customize TypeDoc without requiring a plugin for everything. This is why the `--customCss` option exists, despite being easily implemented with a plugin.

I don't love making one option's behavior dependent on another option, as is done in typedoc-plugin-extra-footer, but can't argue with the improved user experience regarding adding the `<p>` wrapper... 

---

@mayank1513 see #2567

**Comment by Gerrit0** [comment]
Included in TypeDoc 0.26, which is releasing 2024/06/21

**Comment by mayank1513** [comment]
Can you also explain how to use this feature.

**Comment by Gerrit0** [comment]
Exactly as proposed in your original post, with the option name `customFooterHtml`
