### ISSUE TITLE
Any way to get packages strategy to work with merge module plugin?

### ISSUE THREAD

**Issue by ben-polinsky** [TypeStrong/typedoc#2578]
Hi,

I'm attempting to use the the packages entry strategy along with typedoc-plugin-merge-modules. However, as the docs state, plugins do not run on individual packages, only in the global typedoc config. I'm attempting to merge at the module level with custom @module tags.

If I run each project's docs individually and output to json, and then merge manually, the plugin works - however cross-package links are not resolved. 

Perhaps this is an issue for the plugin repo, but I suppose my question here is: are there plans for using plugins on sub-projects? Or should plugins applied globally work on each sub-project? 

Thanks

**Comment by Gerrit0** [comment]
Those docs should probably be refined a bit -- plugins **can** affect child packages, but they won't be loaded for every single child. They'll be loaded once at the root level, then each child will be converted with that same application instance (though there will be a different `Options` instance for each package). However the merge module plugin is set up apparently doesn't work with this... I'm not familiar with its implementation, but I can't think of any reason it wouldn't work out of the box right now.

**Comment by Gerrit0** [comment]
It looks like it is set up to only listen to one of the events for conversion, rather than merging when converters are finished, and when merging is finished.

https://github.com/krisztianb/typedoc-plugin-merge-modules/blob/master/src/plugin.ts#L55-L66

The comment there is wrong, as TypeDoc won't create a new `Converter` instance, but it looks like this is intentional..

**Comment by ben-polinsky** [comment]
Appreciate the investigation! I'll take a closer look when I have a chance.
