### ISSUE TITLE
Show source button

### ISSUE THREAD

**Issue by Evgenus** [TypeStrong/typedoc#26]
Maybe it is not common case but I'd like to have ability of switching from documentation to source. Like this project do http://www.xperiments.io/TSDoc/docs/index.html

**Comment by Spiralis** [comment]
Is there a way to force the documentation links to use i.e. master instead of the commit-id? The thing is that this means that for every github commit-change I have to include the docs in the commit too, even if all the docs are otherwise identical.

For example, this link: https://github.com/IntelliSearch/search-client/blob/f912698/src/AllCategories/AllCategories.ts#L19
depends on that commit to have been executed. Now, if I was hosting live docs for *every* version, then that would be fine. But, I am only hosting live docs for the latest version. Meaning that if the link instead was to master (which is my, and probably others' main branch too), then it would work and regenerating docs for newer commits could have the same results.

Actually, right now, the above `blob/f912698/` link doesn't work as I dropped updating the source, since there were no changes. I since then realised that doing so meant that the links will not work. 

But, this link using master works fine: https://github.com/IntelliSearch/search-client/blob/master/src/AllCategories/AllCategories.ts#L19

So, all I am asking is if there is a way to tell the typedoc generator to use the branch name instead of the commit when generating the paths?
