### ISSUE TITLE
`tests` file is not ignored while docs generation

### ISSUE THREAD

**Issue by amit-ksh** [TypeStrong/typedoc#2612]
## Search terms
error, tests, ignore directories

## Question
How i can ignore all the files inside the `tests` directory

### Project Structure
- /src
- /tests

### Build command
```bash 
typedoc
```

### Typedoc.json
```json
"name": "Documentation",
  "entryPoints": ["src"],
  "exclude": ["tests"],
  "out": "docs",
  "customCss": "./typedoc/style.css",
```

### Error
```js
tests/env/typescript-browser/src/index.ts:1:29 - error TS2307: Cannot find module '../../../../' or its corresponding type declarations.
```

**Comment by Gerrit0** [comment]
This error is coming from TypeScript, which TypeDoc relies on in order to retrieve type information. You'll see the same errors if you run `npx tsc --noEmit`

To avoid this, you need to adjust your tsconfig.json file so that the tests directory is ignored, using [TypeScript's exclude option](https://www.typescriptlang.org/tsconfig/#exclude)
