### ISSUE TITLE
How to link a documentation?

### ISSUE THREAD

**Issue by bladerunner2020** [TypeStrong/typedoc#2641]
## Search terms

link, readme, documentation

## Question

I have a documentation as a number of markdown files. In this files I can use standard markdown links using relative paths. For example, `[see doc-a](./dir/doc-a.md)`. But how can I insert a link to a document from a TypeDoc comment? Should I use `{@link}` or markdown notation? Some example would be very useful in the TypeDoc documentation....

**Comment by Gerrit0** [comment]
Yes, `@link` will work, it's mentioned as the last line of text on the [external documents](https://typedoc.org/guides/documents/) docs page

**Comment by bladerunner2020** [comment]
> Yes, `@link` will work, it's mentioned as the last line of text on the [external documents](https://typedoc.org/guides/documents/) docs page

I read it a few times before asking. I understand how to link from a document to a code, but when I need to link from a code comment a document. 

This seems not working:

```ts
/**
 * See {@link README.md} for more information.
 * /
 export function hello() {
// ...
}
```

**Comment by Gerrit0** [comment]
My apologies! I read your question exactly backwards.

You can link to a document using a relative path with a regular markdown link. This is what I'd recommend as it'll also make the links work within VSCode. You *can* use a `@link` tag, but it will need to reference the document title, not the path, for <https://typedoc.org/example/documents/External_Markdown.html>, it would be `{@link !"External Markdown"}`

**Comment by bladerunner2020** [comment]
> it would be `{@link !"External Markdown"}`

Thanks this works, but I found out that it is necessary to remove the `.md` extension. So to link `doc1.md` one should write {@link !doc1} and to link a document in a subfolder, say `subdir/doc2.md` - `{@link !subdir/doc2}`. I think it would be worth adding this to the documentation.

However, I still cannot figure out how to link README.md - `{@link !README}` doesn't work.

Thanks, this works, but I found out that it is necessary to remove the .md extension. So to link doc1.md, one should write {@link !doc1}, and to link a document in a subfolder, say subdir/doc2.md, use {@link !subdir/doc2}. I think it would be worth adding this to the documentation.

**Comment by bladerunner2020** [comment]
and related question - is it possible to use anchor links? For example, `[some text](./document#some-anchor)`. I tried but it seems doesn't work.

**Comment by Gerrit0** [comment]
The readme file, unfortunately, is *special*. It isn't a separate reflection like all the other documents, so it doesn't have a link target... in fact, generating a link to the project which contains it would take you to the modules page as the project reflection is rendered twice. I don't have a good solution for this other than a manual http link.

Anchors - currently no. It wouldn't be terribly difficult to ignore anchors... it's more work to validate that they'll work.

**Comment by bladerunner2020** [comment]
> I don't have a good solution for this other than a manual http link.

But I have - just discovered! If you add `README.md` in `projectDocuments` then the standard links work - `{@link !README}`.

**Comment by Gerrit0** [comment]
Unfortunately that'll end up rendering the readme twice, unless you also pass `--readme none`... you'll end up with the readme rendered in `index.html` and also in `documents/readme.html`

**Comment by y-polonsk** [comment]
@Gerrit0 I have couple of questions about this:

1) I couldn't get the above solution ({\@link !"Document Title"}) to work for child documents, that is documents declared as child documents in YAML frontmatter. If I do something like {\@link !"Parent Title / Child Title"} the link still only opens parent document. If I do {\@link "Child Title"} then the link doesn't work at all. Is this supported?
2) If I place a document at root level and create a link like {\@link !"Document Title"}, then the link works, however, the link text displays literally "Document Title", including double quotes.  Is there a way to get rid of double quotes in the link text?
3) This solution seems kind of inconvenient if the document title is long, because then it has to be duplicated every time to place a link (and if the document title later changes, we would have to change all the links to it).  In the older typedoc-plugin-pages, it was possible to identify a page by its source id and then use \@page tag without having to retype doc title.  Is there any plans to implement something like this?
4) The markdown-style links do work for classes (inside class comments) but not for interfaces.  If i put such link inside interface comments, in the resulting html docs it still has link to .md file (which of course doesn't work) instead of to .html file.  Is there a workaround for this?

**Comment by Gerrit0** [comment]
1. You want `{@link !"Parent Title"."Child Title"}`, though I'd still prefer linking with `[text](./path/to/child.md)`, which also supports linking to headers within the document.
2. Links support text after it, `{@link "Child Title" | Link text}` or `{@link "Child Title" Link text}`
3. There's no feature for this currently, though that's an interesting idea... It's a shame that the TSDoc people decided to define [`@label`](https://typedoc.org/documents/Tags.__label_.html) to mean something different than this...
4. [needs-repro] -- please open a new issue

**Comment by GaddMaster** [comment]
Can I chime in here and ask how does one remove all the .md from of all links ?
module.md = ./module
my-link.md = ./my-link
This is using me a lot of issue to try figure out ? 
Using typedoc-plugin-markdown !
