### ISSUE TITLE
Undocumented void return value produces warning

### ISSUE THREAD

**Issue by jpikl** [TypeStrong/typedoc#2644]
## Search terms

notDocumented, void, return warning

## Expected Behavior

Typedoc should not produce warning for undocumented void return value of arrow functions.

## Actual Behavior

Typedocs warns about void return value not being documented.

## Steps to reproduce the bug

**index.ts**

```ts
/**
 * This one is OK.
 *
 * @param value - Value.
 */
export function voidFunction(value: unknown): void {
    // ...
}

/**
 * This one produces the following warning:
 * 
 * > [warning] voidLambda (CallSignature), defined in ./index.ts, does not have any documentation
 *
 * @param value - Value.
 */
export const voidLambda = (value: unknown): void => {
    // ...
};

/**
 * This one does not produce warning.
 *
 * @param value - Value.
 * @returns Workaround (return docs which should not be necessary here).
 */
export const voidLambdaFixed = (value: unknown): void => {
    // ...
};
```

**tsconfig.json**

```json
{
    "compilerOptions": {
      "target": "ESNext",
      "module": "ESNext",
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true,
      "strict": true,
      "skipLibCheck": true
    }
  }
```

**typedoc.json**

```json
{
    "entryPoints": ["index.ts"],
    "validation": {
        "notDocumented": true
    }
}
```

## Environment

-   Typedoc version: 0.26.4
-   TypeScript version: 5.5.3
-   Node.js version: 20.13.0
-   OS: Linux

**Comment by Gerrit0** [comment]
This happens because TypeDoc's model for const-functions is slightly different than regular functions. For const-functions, TypeDoc attaches the comment to the `ReflectionKind.Function` reflection, while for regular functions, TypeDoc attaches it to `ReflectionKind.Signature`.

The `@returns` block works around this because it gets copied down to the signature.

What TypeDoc should be doing is not marking the signature as non-documented in this case because the owning reflection contains a comment.
