### ISSUE TITLE
Namespaces do not fully populate the  "on this page" section in the right-hand navbar

### ISSUE THREAD

**Issue by Oblarg** [TypeStrong/typedoc#2645]
When generating a documentation page for an explicit namespace (i.e. declared with `namespace`), code entity categories are not all represented on the right-hand "on this page" navbar.

In particular, the following categories are missing:

* Interfaces
* Type aliases
* Enumerations
* Classes
* Namespaces

The following category *does* appear:

* References

When a namespace contains only elements from missing categories, the "on this page" navbar does not render at all.

**Comment by Gerrit0** [comment]
This is working as expected -- those categories are *not* on that page. They're listed in the index, but they are rendered on their own pages.

(You could argue they shouldn't be listed in the index, but keeping them in the index is important so that people without JS enabled can still browse through the documentation. The sidebar requires JS to load, but the index does not)

**Comment by Oblarg** [comment]
There's a navigability issue now with particularly-large namespaces that results from this; could you reclassify this as a feature request, asking for the following:

* The "on this page" sidebar should reflect the index, rather than the page contents
* The index subcategories should be collapsible

**Comment by Gerrit0** [comment]
> The "on this page" sidebar should reflect the index, rather than the page contents

Definitely a `wontfix`. "on this page" includes what is on that page, not that page + extra stuff.

> The index subcategories should be collapsible

Seems reasonable -- I want a different issue for this though, issues are cheap, repurposing them can just lead to more time spent when trying to revisit them 6 months later to see why a change was made.

**Comment by Oblarg** [comment]
@Gerrit0 I understand your objection, but I think the distinction between what is actually "on the page" is too blurry right now for this to make sense.  Consider:

* A sub-namespace is not represented in the "on this page" sidebar of its parent namespace, but does appear in the page index
* If that *same* sub-namespace is re-exported by a different namespace, it *does* appear in "on this page", but only as a "reference"
  * The bit that appears on the page, however, is just a link - no different in substance than the index entry which did *didn't* appear.
  
I think, from a user perspective, the "page" includes every documented property belonging to the code entity in question.  Right now, it seems as if a large number of index elements "disappear" when you try to find them in the right-hand bar, with no way to recover them.

Put another way: users need to navigate types about as often as they need to navigate concrete members.  Why is type navigation second-class?

**Comment by Gerrit0** [comment]
> however, is just a link

Only if it doesn't have any additional documentation. If it has an associated doc comment, that will also be rendered.

I am planning to change how module pages are rendered in 0.27 in a way which will incidentally also resolve this issue.

All links under "on this page" must stay on the current page -- that's my current criteria for it. No navigation to another page. Including the index within "on this page" would be horrendously confusing because then either:

1. References show up twice - once for their entry in the index, and once where they are rendered on the page
2. One of the places references show up is rendered, potentially resulting in the navigation order not matching the actual page order depending on the user's specified `sort` option.
