### ISSUE TITLE
Is there a way to format the documentation of a constant object in the same way as an interface

### ISSUE THREAD

**Issue by aayla-secura** [TypeStrong/typedoc#2697]
## Search terms

Object properties, abstract static class, module, namespace

## Question

Not sure if I'm "doing it wrong" as I'm new to TypeScript, but what I'm used to seeing/doing in module pattern design JavaScript is have a plain object that holds functions, rather than defining a dummy class that only has static methods.

However in typedoc, the formatting for plain constant objects is somewhat bleak. An interface documentation is much better.

My current solution is to define the interface and document it, and then define a hidden constant with type = the interface. But it seems redundant. The interface is not needed for anything else, doesn't need to be exported, it's the "module" (the actual object) that's needed.

Is there better a way to achieve what I want, or is this actually the correct way to define static module-like variables?

Here's what I mean

```javascript
// This is documented nicely but I think it's pointless in my use case and I don't use that interfaces anywhere else
export interface Module {
  /**
   * Property of the module
   */
  prop: number

  /**
   * Some function doing something.
   *
   * @param {} n  Some number
   */
  someFunc: (n: number) => number;
}

/**
  * @ignore
  */
export const Module : Module = {
  prop: 1,
  someFunc: (n: number) => {
    return n;
  },
};
```

```javascript
// What I want is just this, but the doc looks boring
export const Module = {
  /**
   * Property of the module
   */
  prop: 1,

  /**
   * Some function doing something.
   *
   * @param {} n  Some number
   */
  someFunc: (n: number) => {
    return n;
  },
};
```

**Comment by Gerrit0** [comment]
You're probably after the [`@namespace`](https://typedoc.org/tags/namespace/) tag

**Comment by aayla-secura** [comment]
Thanks for replying. I tried but it doesn't look like I want it, still quite basic and unlike an interface. It creates separate pages for each property rather than displaying them on a single page. Also, it doesn't seem to parse categories properly. `someFunc` is listed under category `catB` in both cases, but only parsed correctly for the interface.

![Screenshot 2024-09-04 092808](https://github.com/user-attachments/assets/9b0236c6-0cf2-4f25-b35c-4b40b5cb83c6)

![Screenshot 2024-09-04 092817](https://github.com/user-attachments/assets/9ae2a0c2-6fb1-4d8a-b812-4d7070ee79e6)

**Comment by Oblarg** [comment]
Try putting `@interface` on a typedef equal to the `typeof` the constant.

**Comment by Gerrit0** [comment]
My apologies, I replied without reading closely enough, all the requests I've seen for something like this have gone the other direction.

TypeDoc does support the `@class` annotation on variables (ugh, apparently I forgot to document this on the site when releasing v0.25.8) which would result in your module being documented as a class with a bunch of static properties -- mostly giving you what you're after. It will also kick out a warning every time you use it for namespaces like this as they won't have a construct signature defined.

TypeDoc does *not* currently have any option to render object variables like classes/interfaces. I'm not sure that it should either. Grouping a bunch of functions together in an object is a style much more reminiscent of the days before bundlers were common, so `_.find`, `_.sortBy`, etc. were more common. Today, I'd put those functions together in a module and `import * as Module from "./module.js"` if I wanted a grouped constant.

Handling this case in TypeDoc would also be rather annoying because variable properties aren't "real" properties of the variable reflection, they're nested under the type declaration reflection owned by the variable. Signatures have that same problem and are bad enough today, I'd hate to extend that problem! ... though that said, #2524 can't be fixed without at least partially handling it, so maybe it should do special things here... but then there's nested-nested objects... when does it end?

This rendering could be done with a custom theme which overwrote the [memberDeclaration](https://github.com/TypeStrong/typedoc/blob/master/src/lib/output/themes/default/partials/member.declaration.tsx) property on the context object, checked `props.type.type == "reflection"`, and looped over the type members instead...

> @Gerrit0 You mentioned in a reply to one of my issues that there was an update coming to namespace rendering in general - is there any chance that would also address this as a side-effect?

No, the namespace/module rendering only affects those types. With the `@namespace` tag applied, it would result in the following, which is nicer, but continues to give each member its own page for details... I really need to get the last few partially-broken things fixed on that branch so I can start the beta process for 0.27.

![image](https://github.com/user-attachments/assets/574cb402-c4bd-40b0-b33f-3c4448f69507)
