### ISSUE TITLE
Domain typedoc.io not reachable, has status pendingDelete

### ISSUE THREAD

**Issue by mrbigbunbury** [TypeStrong/typedoc#270]
All links to typedoc.io are leading nowhere, because the domain is on status pendingDelete.

See `whois typedoc.io`:

```
Domain : typedoc.io
Status : pendingDelete
Expiry : 2016-08-04
Delete : 2016-11-03 00:30
```

**Comment by Edward-Lombe** [comment]
Where is the API documented elsewhere I wonder...

**Comment by aciccarello** [comment]
@Edward-Lombe you can build the documentation from the project source if you need. But I do think the website should be brought back.

**Comment by BurtHarris** [comment]
I too discovered the DNS entry for `typedoc.io` is expired.   Similarly, the domain `typestrong.org` looks unattended.   

Custom domains cost money, is there some reason these aren't hosted on https://pages.github.com/ ?

**Comment by johan-gorter** [comment]
Another free option is http://typescript.js.org

**Comment by BurtHarris** [comment]
@sebastian-lenz and @blakeembrey seem to be the key contributors to this project, perhaps we can attract their attention by mentioning their names.

**Comment by blakeembrey** [comment]
Thanks. Someone had reached out on Twitter. I never had control over the websites, so if people are interested we can re-create the site under @TypeStrong.

**Comment by BurtHarris** [comment]
I think it would be a good idea to host it under TypeStrong.   I don’t know what was there before, so I’m curious.

**Comment by blakeembrey** [comment]
I believe this is the existing content: https://github.com/TypeDoc.

**Comment by aciccarello** [comment]
Yeah, I think you are right. Should those get pulled into one repo and updated?

**Comment by blakeembrey** [comment]
Sure @aciccarello! Would you be interested in helping out with that?

**Comment by blakeembrey** [comment]
If someone is interested in setting that up (I can create an repo and add you to it), then I can purchase the domain and we can put things back how it was before.

**Comment by aciccarello** [comment]
@blakeembrey, I would like to but am in the process of moving and won't have any time soon 😢.

**Comment by ShadowManu** [comment]
Hi. I''ve just recently came across the typedoc project but my team may be interested in integrating typedoc in our projects. I could contribute a piece of my daily time next week to fix this and also see how it works for us. I'll confirm tomorrow.

**Comment by ShadowManu** [comment]
Btw, typestrong.org site looks having domain issues too.

**Comment by d-asensio** [comment]
I can help also, all we need to re-create the website is generate the docs with grunt, check the content of https://github.com/TypeDoc/typedoc.github.io and tie them toghether?

**Comment by blakeembrey** [comment]
@ShadowManu To be honest, I'm not even sure what the `typestrong.org` site held. Do you know?

@d-asensio Sounds good. If you want to replicate the content with `gh-pages` support, I can point a new domain there.

**Comment by ShadowManu** [comment]
@blakeembrey no idea

**Comment by d-asensio** [comment]
Okay @blakeembrey I will try to do tomorrow ;)

**Comment by felixfbecker** [comment]
I like to use http://surge.sh/ in my projects. It is extremely simple, you just `npm i -g surge` and run the `surge` command inside a folder with a static site. You pick a custom subdomain and have your site online. Even better, Travis has native support for deploying to surge so you can update the site with every push (it can be built from the source inside CI).

**Comment by ShadowManu** [comment]
Sounds promising that surge thingy. @d-asensio you can contact me if yo want a dev partna' ;)

**Comment by WasabiFan** [comment]
@ShadowManu For the sake of maintainability, _please_ don't use 3rd-party tools like that. I would highly recommend sticking to known-good tools that are supported by GitHub.

Optimally, you should just move the existing code into the new repo which @blakeembrey has said he can give you -- which would be named appropriately for GitHub pages -- and then clean up the code and update the docs. Using GitHub Pages means that publish permissions are simple, and because it uses Jekyll, you can separate out common headers and structure into layouts to keep it clean and understandable. No CI build or other custom infrastructure is required, and there's a high likelihood that prospective contributors would already know how to work with Pages and Jekyll.

**Comment by blakeembrey** [comment]
Thanks @WasabiFan. Although I believe it's easy enough to go either way with the correct setup ( there's a different set of benefits), in most cases it's unnecessary with GitHub pages. I won't be committing to anything extra here either since we don't need any other benefits. @d-asensio has already been very helpful moving the existing site into http://github.com/TypeStrong/typedoc-site. The domain is set up, but I believe there's some extra work to be done yet.

For an application server that isn't directly related to an open source project that wants contributor ownership, you probably shouldn't be using GitHub pages and should look into tools like Surge (personally been using Stout + S3 + Cloudfront). But that discussion isn't relevant here, let's stick with ease of accessibility (and access for current and future maintainers, had a number of issues where something out of my control has gone offline - like this domain, for instance!).

**Comment by d-asensio** [comment]
I'm agree with you @WasabiFan and because of that I have migrated the templates from http://docpad.org/ (which is used by https://github.com/TypeDoc/typedoc.github.io) to Jekyll.

@ShadowManu as @blakeembrey said there's some extra work to be done, so you can help me to generate the API documentation if you want 😄 .

**Comment by stocksr** [comment]
package.json also has the .io domain

**Comment by aciccarello** [comment]
I believe all related issues have been address.

**Comment by ca98am79** [comment]
Hi, we (at park.io) got typedoc.io if you guys want to use it.
