### ISSUE TITLE
TypeScript 5.6 support

### ISSUE THREAD

**Issue by KDean-Dolphin** [TypeStrong/typedoc#2711]
## Search terms

5.6 Iterator

## Question

Officially, TypeDoc supports up to TypeScript 5.5. I'm using the new `Iterator.from()` pattern and so running TypeDoc generates the following:

`TS2693: 'Iterator' only refers to a type, but is being used as a value here.`

It seems that TypeDoc is overriding the tsconfig.json in each package to use its preferred version of TypeScript.

When will full TypeScript 5.6 support be available?

My `typedoc.json` is below. I haven't posted the upgrades to TypeScript 5.6 yet but all the repositories are under https://github.com/aidc-toolkit.

```
{
  "$schema": "https://typedoc.org/schema.json",
  "plugin": [
    "typedoc-plugin-mdn-links",
    "typedoc-github-theme"
  ],
  "name": "AIDC Toolkit",
  "entryPoints": [
    "../core",
    "../utility",
    "../gs1"
  ],
  "entryPointStrategy": "packages",
  "includeVersion": true,
  "out": "api",
  "theme": "typedoc-github-theme",
  "sourceLinkExternal": true,
  "titleLink": "https://github.com/aidc-toolkit"
}
```

**Comment by Gerrit0** [comment]
TypeDoc supports TS 5.6 since v0.26.7, though it was a transparent update and will work, just printing out a warning, with older versions.

You are getting those errors from TypeScript. TypeDoc will use whatever version of TypeScript you have instructed it to by what you've installed locally in your project. Whatever package.json you have typedoc's version specified in likely also needs an update to specify a more recent version of TS.

**Comment by KDean-Dolphin** [comment]
TypeScript wasn't installed in the documentation project; I assumed (erroneously) that TypeDoc would pickup the TypeScript configuration in the packages listed in `entryPoints`. Once I added TypeScript to the documentation project, the errors went away.

Thanks.
