### ISSUE TITLE
The document's name appears as ____

### ISSUE THREAD

**Issue by eu81273** [TypeStrong/typedoc#2714]
## Search terms

title, underbars, url

## Question

<img width="908" alt="스크린샷 2024-09-24 오전 11 26 58" src="https://github.com/user-attachments/assets/26c99de9-40fb-4fd2-b08d-679c3600a9bf">

If document's title is not English, then it's name appears like this "____". The screenshot attached shows this issue.

I found this issue related the abstract.ts file.
https://github.com/TypeStrong/typedoc/blob/3723b582ad6013c6e2d30090a80960ddfd52e488/src/lib/models/reflections/abstract.ts#L392

Is there any way to solve this problem?

**Comment by Gerrit0** [comment]
This is caused by TypeDoc trying to ensure that documents are generated with valid file names according to [rfc3986](https://www.ietf.org/rfc/rfc3986.txt)

> 2.3.  Unreserved Characters
>
>   Characters that are allowed in a URI but do not have a reserved
>   purpose are called unreserved.  These include uppercase and lowercase
>   letters, decimal digits, hyphen, period, underscore, and tilde.
>
>      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"

https://stackoverflow.com/a/25570039/7186598 implies that TypeDoc probably could have looser restrictions here... definitely something that needs more experimentation to prove out though, and something that'll have to wait for 0.27 as it will break existing URLs.

**Comment by eu81273** [comment]
@Gerrit0 
Thanks for your quick reply.
If intended to non-word replaces to "_", it seems the Regex below works as intended.

```javascript
this.name.replace(/[^\p{L}]/gu, "_")
```

### `\W` Pattern

<img width="410" alt="스크린샷 2024-09-24 오후 1 03 02" src="https://github.com/user-attachments/assets/96883aca-6212-4a93-97d5-6bb457d33920">

### `[^\p{L}]` Pattern with unicode flag
<img width="408" alt="스크린샷 2024-09-24 오후 1 03 16" src="https://github.com/user-attachments/assets/3cd2dcf0-f5a9-425e-9d60-edf6f4ea7411">
