### ISSUE TITLE
Treat base README as a document

### ISSUE THREAD

**Issue by nicfv** [TypeStrong/typedoc#2743]
## Search Terms

readme, document, base, parent, child, external, documentation, projectDocuments, #2740 

## Problem

`README.md` does not support yaml [document content](https://typedoc.org/guides/documents/#document-content).

## Suggested Solution

Support document content in base README.md file.

**Comment by Gerrit0** [comment]
I considered just converting the readme file as a document when implementing the documents feature, but decided against it for a few reasons.

1. It complicates the rendering code. Currently, the renderer can simply recurse over the reflection tree, and produce output files. There are just 2 checks for whether or not a project has a readme (and it was just 1 for a *really* long time)

    If the base readme is treated as a document, then we have three options. (1) Add the readme as a child of the project. (2) Use the readme as the root reflection. (3) Treat a child document named "readme" specially

    If (1) is chosen, then the rendering code now has to have special logic to determine that this child is special and ought to be rendered as index.html, replacing the project's ownership of that URL. The converter code also has to have special logic to handle adding children of the readme document not to the readme, but to the project (or even hackier handling in the rendering code)

    If (2) is chosen, then a large simplifying assumption that was made when building documents no longer holds. TypeDoc currently does not allow documents to hold children which are non-documents. It also means that we end up with two variants of the ProjectReflection class, which is already a special case that has 8 permutations of possible states when rendering. (Single/Multi module, Readme/no readme, comment/no comment)

    If (3) is chosen, the renderer doesn't have to change, but magic handling of names isn't good, TypeDoc's `--readme` option is somewhat frequently used to reference files not named `readme`, so I guess this could be changed to be "child document which matches the file specified by `--readme`".. but that's ugly too!

2. Other options make it not necessary.

    If the project specifies a single entry point, that entry point may specify a [module comment](https://typedoc.org/tags/packageDocumentation/), which can include `@document` tags.

    If the project specifies more than one entry point, the [projectDocuments](https://typedoc.org/options/input/#projectdocuments) option can be used. TypeDoc options can be specified in an options file, tsconfig.json, or even in package.json

3. Providing too many ways to configure a behavior tends to lead to confusion, if not for users then at least for me when looking at some bug report due to one of those ways happening to not work. TypeDoc *could* recognize frontmatter in the readme file, but there are already 2 other ways to add project documents.
