### ISSUE TITLE
Expandable Hierarchy Section

### ISSUE THREAD

**Issue by mrfigg** [TypeStrong/typedoc#2744]
## Search Terms
hierarchy

## Problem

Having to go to a separate page (`hierarchy.html`) to view the full hierarchy of a declaration is inconvenient, and frankly the fact that `hierarchy.html` does not cleanly fit into the site navigation just gets under my skin (in a pet peeve sense).

## Suggested Solution

Make the hierarchy section on a declaration page expandable.

Here's a working example of how to do this with only html & css: [Codepen](https://codepen.io/mrfigg/pen/NWQbpjY)

**Comment by Gerrit0** [comment]
Once the integration of the DMT lands (#2335) there will be a button in the navigation which shows the full hierarchy

I don't think including the entire hierarchy for a given class in every rendered page is a good idea - depending on the class hierarchy of the project this could reintroduce issues where the rendered size of the documentation balloons to >10x what it is today (previously caused by including the navigation on each page).

I could see saving the hierarchy to another assets file so that it the view full link could be replaced/augmented with an expand option dynamically if the user has JS enabled, but am unlikely to spend what time I have for typedoc on this anytime soon.

**Comment by mrfigg** [comment]
Ah shoot, I didn't think about the file size. I was almost done with a PR with a strait forward implementation of this. I'll look into mimicking the approach that the search/navigation takes.
