### ISSUE TITLE
output dir error

### ISSUE THREAD

**Issue by jbaron** [TypeStrong/typedoc#28]
When I try to run typeof on OSX I get the following error:

Error: The output directory "/Users/peter/Development/cats/api_doc" exists but does not seem to be a documentation generated by TypeDoc.
Make sure this is the right target directory, delete the folder and rerun TypeDoc.
Documentation generated at /Users/peter/Development/cats/api_doc

The directory stays empty and I tried removing the directory before running typed, but made no difference. I used the following command:

```
    ./node_modules/.bin/typedoc --target es5 --out api_doc/ src/
```

**Comment by PanayotCankov** [comment]
I want to create a "github.io" API ref page that is added as a submodule in my main repo. The main repo has grunt script generating the api ref. The problem is that I hit this issue. I clean all but the .git files from the submodule before running the typedoc. Is it possible to add a switch to disable this error? Ofc. I can rearrange thing to make it work.

**Comment by sebastian-lenz** [comment]
Hi Panayot, please see issue #132 describing the same issue. Next version should contain the command line switch <code>--disableOutputCheck</code> that allows you to bypass the cleaning of the output directory.

**Comment by PanayotCankov** [comment]
That's exactly what I was looking for. Thanks! :heart_eyes:
