### ISSUE TITLE
opt-in doc tag

### ISSUE THREAD

**Issue by mikehaas763** [TypeStrong/typedoc#331]
I love typedoc, it's amazing.

I think it'd be nice to have an opt-in mode where no documentation is generated except for when a specific doc tag is in a comment. The specific doc tag *could* be configurable. This feature would help with documenting only modules/classes that are meant to be publicly consumable/exposed.

For a comparison, the dgeni documentation generator (with typical configuration/setup) will only generated documentation when there is a `@ngdoc` jsdoc tag in the comment.

Do you see this being viable?

**Comment by aciccarello** [comment]
@mikehaas763 That would be a good feature. I think there currently is an opt-out tag that you could use.

I imagine this would be a pretty simple feature for someone to implement. Currently this project is run entirely on PRs from the community.

**Comment by Gerrit0** [comment]
I'm adding a plugin tag + wontfix for this since TypeDoc already provides equally powerful methods for controlling exported symbols and this adds more complexity that doesn't seem to be 

1. You can use `@internal` (along with `--stripInternal`) to hide internal symbols that must be exported. You should already be using this if you need to export internal symbols as it has first class support by TypeScript.
1. You can use `@ignore` or `@hidden` to hide symbols
1. You can use `--excludeNotExported` to remove all non-exported symbols.
1. With #995 it will be possible to exclude non-documented symbols
1. With #639, you will be able to further restrict docs by an entry point.
