### ISSUE TITLE
Getting Error "Experimental support for decorators is a feature that is subject to change in a future release."

### ISSUE THREAD

**Issue by TSGames** [TypeStrong/typedoc#400]
When I try to run typedoc on my angular-cli project, it ends with an error:

`Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.`

My tsconfig.json is already containing the line
   `"experimentalDecorators": true,`

and the project itself compiles just fine

I call typedoc like this:
`typedoc --out ./docs --target ES6 --module commonjs ./src/`

Any ideas?

Thanks
Torsten

**Comment by gjungb** [comment]
The Angular dependency injection requires that you set `"experimentalDecorators": true`, just as you did. Unfortunately the TypeScript compiler complains about this with the message you posted.

In order to ignore this warning when using `typedoc`, try adding `--ignoreCompilerErrors` like so:
`typedoc --out ./docs --target ES6 --module commonjs --ignoreCompilerErrors ./src/`
