### ISSUE TITLE
0.5.6 version pulling in extra files

### ISSUE THREAD

**Issue by gregvanl** [TypeStrong/typedoc#421]
When running typedoc with a single file, the 0.5.6 version is now pulling in all .d.ts files in the project. This was not the behavior in 0.5.5 and might be due to the recent change around the --exclude switch https://github.com/TypeStrong/typedoc/commit/6ddb7f59766aa0929a94f170dd9165921925036b.

**Comment by aciccarello** [comment]
Yes, there was a bug in #387 which makes the exclude option required. As was noted on 6ddb7f5, you can workaround this by adding a dummy `--exclude xx`. Thanks for submitting an issue for this. PRs are welcome.

**Comment by jason0x43** [comment]
When you say 0.5.6 is pulling in all the .d.ts files, do you mean that docs are being generated for .d.ts files?

**Comment by gregvanl** [comment]
Yes, our .json file which included generated types for one TypeScript .d.ts file went from 713K to 13M when all the node_modules TypeScript .d.ts files where pulled in. No change in the project, just an upgrade from TypeDoc 0.5.5 to 0.5.6.

**Comment by jason0x43** [comment]
Hmmm...at a guess I'd say the issue is probably due to the addition of `directoryExists` to TypeDoc's CompilerHost class. This allows the TypeScript compiler's automatic type discovery to work, which will find types in `node_modules/@types` by default. If you're using `--includeDeclarations`, that could cause all the discovered types to be documented.

Try using a combination of `--externalPattern` and `--excludeExternals` to prevent docs being generated for those files while still allowing them to be used by the TS compiler during the generation process. I've been doing something like `--externalPattern '**/+(node_modules|tests|typings)/**/*.ts' --excludeExternals`.
