### ISSUE TITLE
Namespace/Type & Namespace/Interface declaration merging

### ISSUE THREAD

**Issue by m1gu3l** [TypeStrong/typedoc#472]
It's valid in TypeScript to merge type (or interface) with namespace.
```
// declare
type A = 1;
type B = 2;
type C = 3;
export type Letter = A | B | C;
export namespace Letter {
 export function random(): Letter { return <Letter> Math.ceil(Math.random() * 3); }
}
```
```
// then use as both type and module
const letter: Letter = Letter.random();
```

TypeDoc ignores type/interface and prints documentation only for module. I understand it's not very common pattern, but since it's legal it should be handled.

**Comment by aciccarello** [comment]
Agreed that this should be handled better. We need to determine if this is an issue with the parser or with the theme output.

**Comment by makana** [comment]
I think, the type is sometimes generated as type/interface, sometimes as module. I encountered both. Maybe it is some kind of internal what-is-processed-first-and-what-is-merged-to-the-other.

There should be a better way to deal with those types. Maybe expanding a module kind child node below the real type/interface is best.

That would probably resolve some more odd issues here as well. Having a class that acts as a namespace as well and defining variables/functions within that namespace outputs them as static properties/methods of the class (which is not really true but kind of i-can-deal-with-that), that inherit the exported state of the class (which is clearly not true since you have to export variables/functions explicitely).

See related #615

**Comment by aciccarello** [comment]
According to the TypeScript [Declaration Merging documentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html), merging namespaces with enums and classes is an intentional pattern to augement the enum or class. IMO these should continue to come through as enums and classes.

As far as merging namespaces with types and interfaces, I'm not sure what the desired functionality is. [TypeScript seems to only want to use the type](http://www.typescriptlang.org/play/index.html#src=type%20A%20%3D%201%3B%0D%0Atype%20B%20%3D%202%3B%0D%0Atype%20C%20%3D%203%3B%0D%0Aexport%20type%20Letter%20%3D%20A%20%7C%20B%20%7C%20C%3B%0D%0Aexport%20namespace%20Letter%20%7B%0D%0A%20export%20function%20random()%3A%20Letter%20%7B%20return%20%3CLetter%3E%20Math.ceil(Math.random()%20*%203)%3B%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20variable%3A%20Letter%3B%0D%0Avariable.random()%3B).

**Comment by makana** [comment]
It does not matter what the desired functionality is as far as it compiles.

```typescript
type A = 1;
type B = 2;
type C = 3;
export type Letter = A | B | C;
export namespace Letter {
 export function random(): Letter { return <Letter> Math.ceil(Math.random() * 3); }
}

let variable: Letter;
//variable.random();
variable = Letter.random();
```
Not the type itself is augmented (i.e. variables of a type does not have additional methods) but the object with the name ``Letter`` that is - intended or not - the same name as the type.

**Comment by aciccarello** [comment]
Ah, I misunderstood the desired usage. So the solution should be that interfaces and type aliases shouldn't be merged with values or namespaces though interfaces can be merged with other interfaces.

**Comment by christianbradley** [comment]
I'm also having issues with name conflicts/merging. For me it's types or interfaces + functions of the same name, ie: 

```ts
type Foo = { foo: string }
const Foo = (foo: string): Foo => ({ foo })
```

This is a pretty common (and legal) practice for Types/Type Factories.

**Comment by VitorLuizC** [comment]
Same happens if you export a function and a type with same name.

**Comment by lwolle** [comment]
It's a very common pattern for React + TS users to name a component's props type just `Props` as they are usually not exported. The following example leads to a merging of the types in the generated documentation (it doesn't make a difference if an `interface` or `type` alias is used to declare the props). Surprisingly, the generated documentation references both source files but only outputs the type as declared in `App.tsx`.
```
 // App.tsx
 interface Props {
    foo: string;
}
 const App: React.FC<Props> = (props) => 'App';

 // Child.tsx
 interface Props {
    bar: string;
}
 const Child: React.FC<Props> = (props) => 'Child';
```
![image](https://user-images.githubusercontent.com/20285765/67563652-68752580-f721-11e9-89d2-8120170def13.png)
![image](https://user-images.githubusercontent.com/20285765/67563571-44194900-f721-11e9-8f0c-09901c16f8a1.png)
![image](https://user-images.githubusercontent.com/20285765/67563678-762aab00-f721-11e9-8ecb-c4824db78ca0.png)

**Comment by Gerrit0** [comment]
TypeDoc currently just uses the names of nodes to determine their documented location. If you outputted the JSON for that code, the `Props` interface would likely show up twice, but one would always end up being used... definitely a bug.

**Comment by lwolle** [comment]
Would it generally be feasible to taken the location of a symbol into account?

**Comment by Gerrit0** [comment]
Location isn't enough unfortunately, namespaces can be merged across files.

What we really need to do is stop determining what needs to be documented with nodes and start using TypeScript's symbol APIs (`getSymbolsInScope`/`getExportedSymbols`) to iterate over items. One of many things to do.

**Comment by Gerrit0** [comment]
Closing in favor of #1244.
