### ISSUE TITLE
installing typedoc is forcing the use of 'dom' in `tsconfig.json.compilerOptions.lib`

### ISSUE THREAD

**Issue by zam6ak** [TypeStrong/typedoc#529]
I have a "pure" Node lib for which I wanted to use typedoc to generate documentation...
After installing it and running it I started getting this error:

`node_modules/@types/highlight.js/index.d.ts(19,40): error TS2304: Cannot find name 'Node'.`

After some googling I found [this issue](https://github.com/Microsoft/TypeScript/issues/12391) explaining that one of typedoc dependencies (highlight.js) requires  'dom' being in the list of `libs` for typescript compiler...

Is there a way for me to use typedoc on a pure node library without having to resort to including 'dom' in typescript?

**Comment by lddubeau** [comment]
I've added a typedoc execution to the gulpfile of a [library of mine](https://github.com/mangalam-research/salve) just yesterday. The library does not depend on the DOM being present and can run in Node or the browser so it does not list `dom` in its `lib`. I can run typedoc just fine. I never ran into the issue you report, nor did I have to take special care to avoid it in the first place.

Providing a MCVE/SSCCE/MWE, would help zero in on the problem you actually ran into.

**Comment by mnpenner** [comment]
I'm encountering this issue too. @lddubeau Did you install `typedoc` as a dev dependency? If you do that, it adds `node_modules/@types/highlight.js` which seems to cause `tsc` to always use it, which breaks my compile.

**Comment by blakeembrey** [comment]
Yeah, this is really unfortunate. Also unfortunately, the TypeScript team has been specific about not supporting multiple type definitions for browser vs node.js. This is the use-case I had with Typings that has since gone away with adopting NPM `@types` (at least until TypeScript implements something new). You can bring it up here: https://github.com/Microsoft/TypeScript/issues/7753. There's also some other potential solutions available such as compiler controlled regions in the issues proposed by various people, but I don't think there's any solution available today.

**Comment by mnpenner** [comment]
@blakeembrey Just found a solution actually. There's a [compiler option](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) called "types" which lets you be explicit about which type definitions to include, instead of including everything under `node_modules/@types` as it does by default. It's unfortunate that we have to explicitly list them out, but I can at least compile my project again!

**Comment by blakeembrey** [comment]
@mnpenner That makes sense! It only works so long as TypeDoc never accidentally exports a type from one of these packages though. Right now the imports are elided from the `.d.ts` files when they aren't used, but in the case where they aren't - it'll be a real issue with no hack around it.

**Comment by lddubeau** [comment]
@mnpenner I have `typedoc` installed as a dev dependency, but looking again at my configuration I found why I'm not getting the error. I have `skipLibCheck: true`. If I remove it, then I get the error.

**Comment by mnpenner** [comment]
Actually I can get my project compiling now, but I can't can't get typedoc working now. It's just spewing out dozens of random errors. I think I'm going to give up on it.

**Comment by JoshuaKGoldberg** [comment]
Simpler solution: how about highlightjs just provide a stub `interface Node { }`?

**Comment by aciccarello** [comment]
@JoshuaKGoldberg The `@types` system has some flaws but we need to put them in the dependencies for the reasons specified in many other issues (see #408 #335 #350 #384 #418 and #434). As far as stubbing the node definition, I'm not sure that's a pattern the DefinitelyTyped repo wants to follow.

**Comment by nikeee** [comment]
Maintainer of the highlight.js definition here.
I think it's not the best solution to patch the definitions of highlight.js. I came up with a solution on the library user's side:
https://gist.github.com/nikeee/5a46d1ff4ea7bbb088817740f7376009

Would this work for you?

**Comment by JoshuaKGoldberg** [comment]
@nikeee that sounds good! I'll send a PR to highlightjs thanks!

**Comment by retorquere** [comment]
I have `"lib": [ "es2017", "dom" ]` in my compilerOptions and I'm still getting the error.

**Comment by retorquere** [comment]
would it be sufficient to add a directory to `typeRoots` and drop [highlight.js.ts](https://gist.github.com/nikeee/5a46d1ff4ea7bbb088817740f7376009#file-highlight-js-ts) there?

**Comment by Gerrit0** [comment]
This appears to be fixed now, I can generate documentation without dom included in the lib, please open a new issue if you are still having problems.
