### ISSUE TITLE
Refactoring out code introspection library

### ISSUE THREAD

**Issue by yang** [TypeStrong/typedoc#672]
This project is fantastic, even for just its code introspection capabilities alone—it gives you many things the TS compiler API doesn't (e.g. inherited members with concrete types, not to mention a more usable data structure). It would be amazing to have this available as a standalone library (a la ts-simple-ast). Just a thought—thanks for the great tool!

**Comment by mootari** [comment]
Linking #595.

@yang For now you can probably create an Application instance and call .convert() instead of .generateDocs() to get the ProjectReflection and its children. You might also want to remove some of the [default components](https://gist.github.com/mootari/d39895574c8deacc57d0fc04eb0d21ca) after instancing.
