### ISSUE TITLE
TypeScript dependency should be a version range

### ISSUE THREAD

**Issue by adidahiya** [TypeStrong/typedoc#720]
the typescript dependency of this package should be:

```
"typescript": "~2.7.2"
```

this allows patch versions, which downstream libraries should be allowed to pick up. I don't want multiple copies of `typescript` in my node_modules unnecessarily. this would fix #718.

have you had issues with allowing such a version range in the past?

**Comment by aciccarello** [comment]
Hello @adidahiya, currently TypeDoc is not able to support version ranges for typescript because it uses internal apis that could break even on patch versions. I am considering using a peer dependency on typescript in the future but that wouldn't be anytime soon. I'd have to go through and try and limit the api surface area to avoid unnecessary errors.

It might be worth checking out https://github.com/TypeStrong/typedoc/blob/master/UPDATING.md for updating your own projects.

**Comment by adidahiya** [comment]
Thanks for the response and link to the docs.

> I am considering using a peer dependency on typescript in the future but that wouldn't be anytime soon. I'd have to go through and try and limit the api surface area to avoid unnecessary errors.

I would appreciate a change to make typescript a `peerDependency`. This could be coupled with a warning in the docs suggesting to users that there might be breaks depending on the version of the typescript compiler used at runtime, but at least this gives people more options. Consumers of typedoc ought to be fairly technical so I think you could get away with this.

You should also consider testing with multiple versions of typescript in CI, like we do in [tslint's .circleci/config.yml](https://github.com/palantir/tslint/blob/235561e411c58ecbd4d96844fae28e998f0ccbda/.circleci/config.yml#L66).
