### ISSUE TITLE
Issues with calculated property values and calculated static class fields

### ISSUE THREAD

**Issue by mcjazzyfunky** [TypeStrong/typedoc#764]
#### Bug description (at least I would consider it as a bug):
If you feed TypeDoc with the following TypeScript code then those "someLocalFunction('...')" expressions will be shown in the TypeDoc output. That's surely not intended, is it?
Wouldn't it be better to show the corresponding values only in case they are literals (string literals, number literals, boolean literals) and hide them in case of expressions?

TypeScript source code:
```javascript
export const SomeObject = {
    a: someLocalFunction('a'),
    b: someLocalFunction('b')
};

export class SomeClass {
    static readonly a: string = someLocalFunction('a')
    static readonly b: string = someLocalFunction('b')
}

function someLocalFunction(arg: string): string {
    return 'CONST_VALUE_' + arg.toUpperCase(); // just for demo purposes
}
```

TypeDoc output:
```
[...]
a: string = someLocalFunction('a')
[...]
b: string = someLocalFunction('b')
[...]
````

Thanks a lot in advance.

(Tested with TypeDoc 0.11.1, TypeScript 2.7.2 on Windows 10)

**Comment by Gerrit0** [comment]
This was intended behavior, but I agree - it wasn't good. 0.20.1 will now render values only if they are determined to be "simple", and otherwise render `...` to indicate that there was something there, but was too complex for rendering.

Thanks for the solution for this! It didn't click until I saw this issue.
