### ISSUE TITLE
Handle duplicate private classes

### ISSUE THREAD

**Issue by dtgriscom** [TypeStrong/typedoc#783]
I have three `*.ts` files, each of which exports a single class but also has a non-exported utility class (`TestScreen`). The utility classes all have the same constructor signature and inherit from the same (exported) class (`Screen`), but perform different functions and have different documentation comments.

TypeDoc has trouble handling this:

- The `Screen` documentation shows three different `TestScreen` subclass links, but they all go to the same `testscreen.html` page
- The single `testscreen.html` page seems to merge all three classes' attributes and documentation comments

I would expect TypeDoc to create three separate `*.html` pages for the three private classes.

Confirmed with TypeDoc version 0.9.0 with TypeScript 2.4.1, and TypeDoc version 0.11.1 with TypeScript version 2.7.2. Workaround is to give each private class a different name.

**Comment by Gerrit0** [comment]
It sounds like you are generating with `--mode file`, this mode pretends every module is in the global scope and will get very confused since you have multiple conflicting definitions. If you are using modules you should be using `--mode modules` The library mode (soon... #639) will provide an alternative that I expect will be better for most projects.
