### ISSUE TITLE
Markdown formatting, linebreaks

### ISSUE THREAD

**Issue by casperno** [TypeStrong/typedoc#795]
With markdown, you should force a line-break by adding three spaces before  newline. 

This behaviour is not reflected in the output by ts-doc, I suspect it's because output from the markdown parser is not converted to html, thus whitespace is removed.

Example raw html from ts-doc:
<p>Manager for TextStyles as used in Flow and TextLayout.
						Use <code>textStyleManager.addParagraphStyle()</code> to add a style.
						Use <code>textStyleManager.setLink()</code> to create a link (that can be changed in runtime) to another style.
</p>

Should perhaps be:
<p>Manager for TextStyles as used in Flow and TextLayout.&lt;br&gt;
						Use <code>textStyleManager.addParagraphStyle()</code> to add a style.&lt;br&gt;
						Use <code>textStyleManager.setLink()</code> to create a link (that can be changed in runtime) to another style.
</p>

**Comment by Amourspirit** [comment]
I thought markdown only required two spaces for a newline; however, I am having the same issue and I find it has an impact on readability.

If I use two or three spaces before or after a line it is completely ignored. Will this be implemented? Should I write my comments to expect two or three spaces? Before or after line or both?

**Comment by Amourspirit** [comment]
I found a hack for newline for the time being. I figured out that typedoc respects some other html tags such as blockquote, code, div
Maybe include spaces before &lt;div&gt; or after &lt;/div&gt; just in case the div tags get stripped with a later version.

Div is the tag you can use to simulate a line break.
Where ever you want a line break wrap the line in a div tag.
> \* &lt;div&gt;Options can be added to the BUILD_INCLUDE statement by using []&lt;/div&gt;   
> \* &lt;div&gt;after the initial statement.&lt;/div&gt;   
> \* For example: // BUILD_INCLUDE(../mydir/myfile.js)[asjsstring]

**Formats as:**
Options can be added to the BUILD_INCLUDE statement by using []
after the initial statement.
For example: // BUILD_INCLUDE(../mydir/myfile.js)[asjsstring]

**Comment by Gerrit0** [comment]
TypeDoc uses [Marked](https://www.npmjs.com/package/marked) to render markdown. We use the default settings (with the exception of a custom syntax highlighter). This means that Marked does not sanitize the HTML, which is expected behavior.

Regarding spaces at the end of a line - leading and trailing whitespace is stripped when parsing [here](https://github.com/TypeStrong/typedoc/blob/26202da4eeed8cae80e167a46e0dad9a4543799d/src/lib/converter/factories/comment.ts#L181-L182) and has been done for at least 4 years. The same behavior (ignoring trailing whitespace) is preserved by TSDoc ([playground](https://microsoft.github.io/tsdoc)), which we want to start using eventually.

I think including a blank line in the comment is the most intuitive way to create a new paragraph, especially since some editors will strip trailing whitespace on save and whitespace is easy to miss when reading the code. If you just want to include a newline, `<br>` is the best way to do it.

> \* Options can be added to the BUILD_INCLUDE statement by using []&lt;br>
> \* after the initial statement.&lt;br>
> \* For example: // BUILD_INCLUDE(../mydir/myfile.js)[asjsstring]

**Comment by aciccarello** [comment]
I agree with @Gerrit0's answer. The whitespace in a line should not be considered significant and a blank line or `<br>` should be used to create a new paragraph.

Thanks for raising an issue to discuss though.

**Comment by mhofman** [comment]
Would it be possible to at least support the [backslash style of GFM line breaks](https://github.github.com/gfm/#example-655)?

```markdown
A line\
Another line
```

renders as 2 lines on most Markdown parsers but for some reason doesn't with typedoc.

**Comment by Gerrit0** [comment]
That sounds like a reasonable request, I'd expect it to already work, as far as I remember we don't remove trailing backslashes. There may be an option we need to pass to `marked` to enable this behavior.

**Comment by aciccarello** [comment]
@Gerrit0 @mhofman Sounds like this is related to #899 which talks about different markdown flavors
