### ISSUE TITLE
New release on NPM

### ISSUE THREAD

**Issue by hassankhan** [TypeStrong/typedoc#822]
Hi, 

Love the project, just having a minor issue with regards to the Typescript version. Could we get a new release which at the very least updates Typescript? It seems there are a fair few issues (and PRs) that address the problem but there hasn't seemed to be any traction.

**Comment by ibezkrovnyi** [comment]
TypeScript@3.0.1 released: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html

**Comment by cedx** [comment]
TypeDoc should try to use the local TypeScript package (i.e. declared in `package.json` file), if any one is already installed. This would free us from having to wait for TypeDoc updates to document bits of code using the latest TypeScript features.

**Comment by hiebj** [comment]
@cedx it's quite a bit more complicated than just "using the version available". There would need to be a **lot** of work to build an abstraction layer on top of the TypeScript API, which changes regularly, which would then also need to be maintained.

A language reflection and generation tool like TypeDoc uses a lot of highly specific and frequently undocumented parts of the TS API, and while this project is used heavily by the community, it is maintained almost entirely by three people at any given time. supporting multiple versions at once would probably increase the complexity of the codebase considerably.

It might be reasonable to map the version of this library to the version of TS in some way, so that we don't have to check the dependencies to see what version of TypeScript a given version of TypeDoc supports (in a similar way to how React fixes its versions together for `react`, `react-dom` and `@types/react`). For example, version `1.3.1` of TypeDoc would support version `3.1.x` of TypeScript, etc.

I'm sure the team would be happy to review PRs or well-defined proposals for solutions to the TS versioning problem, it's something they're aware of. there are at least six pull requests related to updating TypeScript on this project already, and at least as many issues.

https://github.com/TypeStrong/typedoc/pull/832 has been merged, updating the TS version to 3.1. a release is coming.

**Comment by aciccarello** [comment]
Thanks for writing all that out @hiebj. TypeDoc uses apis that are technically internal to TS and could be changed even on patch versions. There is a high risk of breaking changes between version. I'm open to using a peer dependency in the future for those who want to try a different version.

The new 0.12.0 release should support TypeScript 3.0. I still need to ensure things are working as expected so if you notice any bugs please open an issue.
