### ISSUE TITLE
An error occurs when using "typedoc-plugin-external-module-name" to prompt "Error: The component `s'has been added."

### ISSUE THREAD

**Issue by Houfeng** [TypeStrong/typedoc#846]
An error occurs when using "typedoc-plugin-external-module-name" to prompt "Error: The component `s'has been added."

![image](https://user-images.githubusercontent.com/1432335/44721739-728b9c00-aafd-11e8-89d7-1cbf9d9db59b.png)

**Comment by aciccarello** [comment]
Could you share how you are getting this error. I'm curious why it thinks it has been added twice.

**Comment by justrhysism** [comment]
@aciccarello I experience this when using _gulp watch_ to rebuild the docs (using [gulp-typedoc](https://github.com/rogierschouten/gulp-typedoc)).

The error isn't thrown on the initial build, but on subsequent builds. *gulp-typedoc* creates a [new instance](https://github.com/rogierschouten/gulp-typedoc/blob/master/index.js#L50), so one would assume that everything internally is "fresh".

*typedoc-plugin-external-module-name* simply just adds itself [via `addComponent`](https://github.com/christopherthielen/typedoc-plugin-external-module-name/blob/master/index.js#L4).

It appears as though the typedoc application lifecycle isn't ending. I'm not an expert on the application side of things, but I feel like it _shouldn't_ end and restart all the time, so if this decision _was_ deliberate and it's _by design_, that makes sense - however if this _is the case_, I don't believe that it should be up to plugin authors to check to see if their plugin/component has already been added.

**Comment by aciccarello** [comment]
@justrhysism This sounds like it could be a gup-typedoc specific issue. Typedoc currently isn't set up for multiple builds.

**Comment by justrhysism** [comment]
> gup-typedoc specific issue

Is it, though? I don't know for sure, but my gut feel is that it's simply _exposed_ by usage with gulp. Maybe someone with a better idea of the inner workings of gulp pipes may be in a better position to suggest otherwise, but the instance instantiation:

```
const app = new typedocModule.Application(options);
```

is encapsulated in a function, so once that function ends, `app` is discarded, and with it, I would assume, the `Application`.

> Typedoc currently isn't set up for multiple builds.

Maybe not concurrent builds, but in my particular use-case which exposed this issue, builds were only being triggered in a serial fashion (i.e. no more than one build occurring at any one time).

---

Specifics aside, what is the _design decision_ behind throwing an error when attempting to add the same plugin twice? What, if any, would be the negative impact of simply ignoring any later attempts to add an existing plugin?

**Comment by justrhysism** [comment]
Okay, trying to dig into the underlying issue - I don't really understand the codebase, but setting loads of breakpoints and exploring, I have learnt a few things:

1. When TypeDoc is first run (before Application instantiation), [each component is added](https://github.com/TypeStrong/typedoc/blob/8384a950275995a5891ea74fdedc45dadc740bb7/src/lib/utils/component.ts#L58) to `host._defaultComponents`
1. When the Application is instantiated, all default components are initialised
1. Plugins are discovered and added
    1. I'm not sure what the standard method for plugins adding themselves is, but _typedoc-plugin-external-module-name_ adds itself as a component via `app.converter.addComponent`
    1. This in turn adds itself to the `_defaultComponents` (which has a longer lifecycle than the Application)
1. If another Application is instantiated, steps 1-3 are run again - however since _typedoc-plugin-external-module-name_ is in the `_defaultComponents` list, it's already added to `_componentChildren` by the time the plugins are discovered and added.

Digging around further, I can see why it's been architected this way - single "pipeline" of converters regardless of how they arrived into the pipeline - I think attempting to change how any of the component systems work to "resolve" this is just a very deep and unnecessary rabbit-hole.

Through this discovery, I can't see any reason why an error would need to be thrown if a component of the same name added twice - except maybe during development.

**Comment by aciccarello** [comment]
Closed via #847 as the simple fix since a comprehensive solution will be messy. Left a TODO note to indicate that the return is not ideal.
