### ISSUE TITLE
TypeDoc does not escape html entities from tag content

### ISSUE THREAD

**Issue by voodooattack** [TypeStrong/typedoc#859]
Typedoc version: 0.12.0
Node versions: 10.10.0, 8.12.0 LTS

Issue: voodooattack/when-ts#2

Problem: typedoc does not escape html entities from generic types inside a `@type` clause.

[Example from my project:](https://github.com/voodooattack/when-ts/blob/555f5665650d1f8f0dca9498439fd3a5f73226f5/src/stateMachine.ts#L74)
```ts
  /**
   *
   * @type {HistoryManager<S extends MachineState>}
   * @private
   */
  private _history: HistoryManager<S>;
```
Output:

```html
<div class="tsd-comment tsd-typography">
  <dl class="tsd-comment-tags">
    <dt>type</dt>
    <dd><p>{HistoryManager<S extends MachineState>}</p>
    </dd>
  </dl>
</div>
```
This causes browsers to think there's a malformed strikethrough `<S>` tag, and it gets applied to the rest of the page. [See here for an example.](https://voodooattack.github.io/when-ts/classes/statemachine.html#_history)

**Comment by Gerrit0** [comment]
I spent some time looking into this and determined that it is (mostly) intended behavior, though certainly unintuitive. The issue isn't the `_history: HistoryManager<S>` line, it is the comment above it.

TypeDoc renders the content of tags as markdown, and markdown supports arbitrary HTML content, so we render `{HistoryManager<S extends MachineState>}` exactly as we see it, which leads to this issue. Now, arguably we should be stripping types from the comment before rendering it, but this is kind of tricky since for some comments `{}` has no special meaning, while for others it describes a type.

**Comment by Gerrit0** [comment]
With #1198's resolution, `@type` tags are now stripped, which fixes this issue.
