### ISSUE TITLE
Suggestion: Category improvements

### ISSUE THREAD

**Issue by rbuckton** [TypeStrong/typedoc#866]
When categorization was added in #566, there was nothing added to the built-in templates to make categories useful. The suggestion in https://github.com/TypeStrong/typedoc/pull/566#issuecomment-332204971 provides some guidance, but overall the solution has some issues:

- There is no category for uncategorized reflections.
- Uncategorized reflections are lost using the suggested template.
- Categories override groups with this approach.

As such, I would like to suggest the following improvements to categories:

1. Add categories to groups. This would let the built-in template organize by group and then category.
1. Support an "Other" category (possibly configurable). This would be the category to place uncategorized reflections when there are other reflections that have a category.
1. Support category sorting via configuration/options.
1. Consider supporting _multiple_ categories for an item (nice to have, but not strictly necessary).

I ended up implementing (1), (2), and (3) in a custom plugin I wrote for my project to work around a number of other issues:

- Add an "Other" category when needed:
  - https://github.com/rbuckton/iterable-query/blob/24f9010f33135008c57d8bd391d518057bef06d3/src/typedoc-plugin-custom/plugin.ts#L33 
- Add categories to groups:
  - https://github.com/rbuckton/iterable-query/blob/refactor/src/typedoc-plugin-custom/plugin.ts#L356
  - https://github.com/rbuckton/iterable-query/blob/refactor/src/typedoc-plugin-custom/plugin.ts#L400
- Index by group and category in theme:
  - https://github.com/rbuckton/iterable-query/blob/refactor/src/typedoc-plugin-custom/theme/partials/index.hbs#L8

Here's an example:
![categories](https://user-images.githubusercontent.com/3902892/46624363-61af4c80-cae5-11e8-9d70-a284e4b5ab97.png)

**Comment by jonchardy** [comment]
Since I worked on the original categories, I'm willing to help out here. It would be nice to get an idea of where people want to see this go.

I can see different methods of categorization (and this is why I didn't implement anything on the theme side, since at the time I knew people would want to do different things with categories):
1) Lump categories, which include reflections from different groups. This is something we do in our index, where we have broad categories that include both classes and interfaces. I think this is most useful at the project level, as lump categories don't make as much sense once you're dealing with methods vs properties.
2) Group categories, as shown by @rbuckton . This would allow classes, methods, etc. to be categorized _within_ their groups. Within a group, I imagine if all categories fall into the default category, we would just output the default group title, rather than including category information.

I certainly agree we can add more configuration options to specify category weights and a default category. And we should probably force users to pick either group categorization or lump categorization, which we could then turn into another option.

**Comment by jonchardy** [comment]
How should uncategorized reflections work when the default category is in use?

Say I have some category, "Foo," and I categorize some classes under it. If I set my default category to "Foo," I'd expect any uncategorized reflections to fall into that category. At that point, the category can't really be considered uncategorized since some classes were explicitly put there.

**Comment by jonchardy** [comment]
https://github.com/TypeStrong/typedoc/pull/938
