### ISSUE TITLE
Options from plugins not processed in `Application#bootstrap`

### ISSUE THREAD

**Issue by rbuckton** [TypeStrong/typedoc#875]
In https://github.com/TypeStrong/typedoc/pull/610 a [change was made](https://github.com/TypeStrong/typedoc/commit/3e609d99ea1a2416a02f1edc6c503eee1271346d#diff-a35ab9fff8766e90a05df25b72668203R125) to `Application#bootstrap`. In this change, the argument to `this.options.read` was changed from `options` to `this.options.getRawValues()`, however `getRawValues` only returns the options that were already successfully parsed. At the point those options were parsed, plugins had not yet been loaded (since they depend on `Prefetch`), so custom options added by plugins are ignored if they are passed as part of the `options` object.

While this doesn't negatively impact parsing CLI arguments, it means that custom options passed to `gulp-typescript` are not parsed correctly.

**Comment by Nek80** [comment]
I agree, this is a regression for plugins that work with gulp-typedoc and should be fixed. I am afraid it is not easy though as the fix for the CLI case should be kept but find a workaround to make this work gulp-typedoc too. Maybe if the setValue() of Options, added the values regardless if they were declared or not, so the getRawValues() will return all passed-in values and on the second call will be able to retrieve the values of the declared options from plugins?

**Comment by Gerrit0** [comment]
This has now been fixed, see #1016. Will be released in v0.16.0
