### ISSUE TITLE
Suggestion: Allow customization of TypeScript version

### ISSUE THREAD

**Issue by rbuckton** [TypeStrong/typedoc#880]
While TypeDoc might not be able to process some AST nodes in newer versions of TypeScript, if a project is using features of a newer version of TypeScript, TypeDoc will fail to generate documentation because it is unable to compile the project.

One option would be to allow TypeDoc API users (such as gulp-typedoc) the ability to customize the version of TypeScript to use.

**Comment by Gerrit0** [comment]
TypeDoc can break even on minor updates from TypeScript as it uses internal API features, #720. It would be neat to have an option to easily test switching to a different version though.

**Comment by aciccarello** [comment]
Yeah, historically we've bundled TypeScript to avoid TypeScripts breaking changes. Since TypeDoc uses some private TypeScript apis it could theoretically break on any version. I'd like TypeDoc to move to the public apis but it isn't ready for that yet. Eventually, I think that TypeDoc should move to a peer dependency.

**Comment by xaviergonz** [comment]
+1 I just removed typescript from typedocs node modules (since I needed it to use 3.6) and it correctly picked up my higher typescript version from a levels above
