### ISSUE TITLE
Do not generate methods of parent class

### ISSUE THREAD

**Issue by amaurymartiny** [TypeStrong/typedoc#883]
```javascript
 import EventEmitter from 'eventemitter3'; 

class A extends EventEmitter {
  myOwnMethod() {/*...*/}
}
```

In the generated docs of `A`, I have all methods/properties of `EventEmitter`. Is it possible to silent them?

**Comment by jonchardy** [comment]
There's a toggle that lets you hide inherited members.

In our case, we wanted to remove them completely since they left us with lots of extra generated HTML. In the simplest case, you can just add the following to createDeclaration in /src/lib/converter/factories/declaration.ts:
```ts
if (context.isInherit) {
    return null;
}
```

There could potentially be a config flag, excludeInherited, that would control whether to output inherited members. I'd be willing to create a PR for this if people are interested.

**Comment by aciccarello** [comment]
Would you want to exclude all inherited? It might make sense for this to be a doc tag on the class. This sounds like a good use case for a plugin.

```typescript
/**
 * My custom event emitter
 * @noInheritDoc
 */
class A extends EventEmitter {
  myOwnMethod() {/*...*/}
}
```

**Comment by jonchardy** [comment]
Just finished up a plugin which should accomplish this: https://github.com/jonchardy/typedoc-plugin-no-inherit

Let me know if it works how you're expecting.

**Comment by aciccarello** [comment]
@jonchardy Thanks for sharing! Would you like to add that plugin to the [readme](https://github.com/TypeStrong/typedoc#plugins)?

We also should add a link to the [full list of plugins on npm](https://www.npmjs.com/search?q=keywords:typedocplugin).

**Comment by jonchardy** [comment]
Yea, I think updating the README with just a link to all published plugins would be good.

**Comment by jonchardy** [comment]
https://github.com/TypeStrong/typedoc/pull/909, minor readme changes.

**Comment by aciccarello** [comment]
@jonchardy Thanks for creating a solution, sharing it, and updating the readme!

**Comment by janat08** [comment]
I think this should be made default

**Comment by aciccarello** [comment]
@janat08 I don't think so. That fact that a method is inherited rather than set locally is an implementation detail. The documentation should document the visible api. Sometimes it does help to know that a method is inherited so it's good to still communicate that and/or group the inherited methods.

**Comment by vdegenne** [comment]
How do I exclude inherited from the command line ?

I have a project that uses `LitElement` for webcomponents, I just want the doc of my code but because most of my elements inherit from LitElement I have all the properties and functions which is an HTMLElement at core, so I let you picture the size of my doc (not to mention it's unreadable and I can't find the overridden methods).

I am generating from command line so is there an argument I can use ?

**Comment by Gerrit0** [comment]
You probably want typedoc-plugin-no-inherit.

**Comment by laukerkillian** [comment]
You can rewrite documentation on the child like this :
`
class OkWidget extends HTMLElement {
    /**
     * @hidden
     */
    public readonly ATTRIBUTE_NODE: number;
    /**
     * @hidden
     */
    public className: string;
    /**
     * @ignore extends
     */
    constructor() {
        super();
    }
}

export {OkWidget}
`

**Comment by dustinlacewell** [comment]
FYI to people coming here: `typedoc-plugin-no-inherit` does not work on versions of typedoc > 0.19 (due to https://github.com/jonchardy/typedoc-plugin-no-inherit/issues/20 )which means you're limited to TypeScript 4.0.x

I recommend reopening it.

**Comment by Gerrit0** [comment]
That plugin should work now, there has been an update to TypeDoc which should have fixed the thing that broke it. This is the right kind of feature to be in a plugin, I don't plan to bring it into TypeDoc itself.

**Comment by arashagp** [comment]
> Would you want to exclude all inherited? It might make sense for this to be a doc tag on the class. This sounds like a good use case for a plugin.
> 
> ```ts
> /**
>  * My custom event emitter
>  * @noInheritDoc
>  */
> class A extends EventEmitter {
>   myOwnMethod() {/*...*/}
> }
> ```

that's not work for me and gave to me an Warning
```sh
[warning] Encountered an unknown block tag @noInheritDoc

13     * @noInheritDoc
```
