### ISSUE TITLE
Support "build" mode (multi project) Typescript

### ISSUE THREAD

**Issue by dardino** [TypeStrong/typedoc#923]
Can we have a support for this?
https://github.com/Microsoft/TypeScript/issues/3469#issuecomment-400439520

**Comment by aciccarello** [comment]
It'd be great to support that but there could be some potential complications. I'll add this to our list of potential enhancements.

For reference, here is that information on the TypeScript website: https://www.typescriptlang.org/docs/handbook/project-references.html

**Comment by Gerrit0** [comment]
I want to support this - but in order to move forward with it, I will need at least one example project using it... closing as unactionable for now. If someone has a project using this that isn't horrible to install, please open a new issue about this so that we can work through any remaining issues.
