### ISSUE TITLE
plugin breaks in 0.14

### ISSUE THREAD

**Issue by Roaders** [TypeStrong/typedoc#943]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Expected Behavior
Should continue to work with typedoc-plugin-sourcefile-url plugin in 0.14

## Actual Behavior
When trying to run:

```
Error: The plugin ...typedoc-plugin-sourcefile-url could not be loaded.

TypeError: Class constructor ConverterComponent cannot be invoked without 'new'
```

## Steps to reproduce the bug
```
npm install typedoc-plugin-sourefile-url

typedoc --sourcefile-url-prefix: \"my-url-prefix\"
```

## Environment
  - Typedoc version: 0.14
  - Node.js version: 8.11.1
  - OS: windows

**Comment by aciccarello** [comment]
Hello @Roaders, thanks for raising this as an issue and sorry for the inconvenience. This was an unanticipated breaking change that was identified following release. I added a comment to the [release notes](https://github.com/TypeStrong/typedoc/releases/tag/v0.14.0) noting that plugins extending classes will need to output `es2015` to match TypeDoc's output format because of semanitc changes to ES6 classes.

Please let us know if this does not fix your issue or are unable to change output version.

**Comment by thetutlage** [comment]
Still breaks with `0.14.2`.  Here's a screenshot

<img width="1015" alt="screenshot 2019-01-19 at 12 13 49 pm" src="https://user-images.githubusercontent.com/1706381/51423279-b59cf780-1be3-11e9-850d-a8d43dbc8c62.png">

```json
{
   "typedoc": "^0.14.2",
    "typedoc-plugin-external-module-name": "^2.0.0"
}
```

**Comment by Gerrit0** [comment]
This requires an update in typedoc-plugin-external-module-name to resolve. Typedoc is now targeting a more recent JS version, which needs to be reflected by plugins in order to maintain compatibility.

**Comment by sirisak1985** [comment]
issue

**Comment by ColinCollins** [comment]
I can't understand, I already update the module-name plugin, but I still got the error.
![image](https://user-images.githubusercontent.com/35832931/52948242-e5dae000-33b3-11e9-8d77-d5bae078e63a.png)

**Comment by Gerrit0** [comment]
The module-name plugin isn't the issue, the typedoc-plugin-sourcefile-url plugin hasn't been updated to support v0.14. There is [an issue](https://github.com/gdelmas/typedoc-plugin-sourcefile-url/issues/5) open to update, but the author hasn't responded to it yet.
