### ISSUE TITLE
how to insert media to show image in documentation? 

### ISSUE THREAD

**Issue by StanislavVoronov** [TypeStrong/typedoc#951]
- [x] I have checked [issues with bug label](https://github.com/TypeStrong/typedoc/labels/bug) and found no duplicates

## Environment
  - Typedoc version: 0.14.2

**Comment by StanislavVoronov** [comment]
/**
 * media://avatar.png
 */

**Comment by Gerrit0** [comment]
It would help a lot if you filled out the issue template so that we can see exactly what the issue is.

My best guess right now is that you expected `media://avatar.png` to turn into an image link automatically - it won't. TypeDoc will just replace the `media://avatar.png` with the URL of the file. If you want to include the image you will need to use markdown (`![alt text](media://avatar.png)`) or html (`<img src="media://avatar.png" alt="alt text">`)

**Comment by StanislavVoronov** [comment]
Yes (<img src="media://avatar.png" alt="alt text">), it worked as I wanted. 
Thanks a lot and good day.

**Comment by aciccarello** [comment]
Great, glad you were able to find something that worked. I'm going to leave this open until we add some information to the docs.

**Comment by Gerrit0** [comment]
The media option is now documented on TypeDoc's site - http://typedoc.org/guides/options/#media
