### ISSUE TITLE
Add support for decorators

### ISSUE THREAD

**Issue by sebastian-lenz** [TypeStrong/typedoc#97]

**Comment by PWKad** [comment]
@sebastian-lenz I see the test cases for decorators but what indicator is being used to specify that the decorator decorates something?  [This](https://github.com/sebastian-lenz/typedoc/blob/master/test/converter/decorators/specs.json#L95-L107 shows that the decoratorAtom decorates because it was used but what if the author wanted to do something like this -

```
/**
 * A decorator for making classes fancy
 *
 * @decorator Class
 */
export function fancyDecorator () {
  // fancy stuff
}
```

**Comment by sebastian-lenz** [comment]
Hi Patrick, we've prepared the decorator support but it is not fully implemented. But I think the <code>@decorator</code> seems reasonable.

**Comment by aciccarello** [comment]
Please include decorator support in comment code blocks. I think they are not displaying correctly. The @DecoratorName causes the block to not be parsed as code and adds some typedoc styling. For example,

```javascript
/**
 * ### Example:
 * 
 * ```
 * @Component({ selector: 'myCustomComponent' })
 * @View({ template: '<h2>This is my custom component</h2>' })
 * class CustomComponentController {
 *  // ...
 * }
 * ```
*/
```

gets displayed as

![image](https://cloud.githubusercontent.com/assets/11273838/10101759/935f44fc-6368-11e5-9bc0-db7d0c6f2736.png)

instead of 

![image](https://cloud.githubusercontent.com/assets/11273838/10101807/e78dcd96-6368-11e5-8b82-139daaa3e343.png)

**Comment by dpopescu** [comment]
As a workaround you could just put a space before the `@` notation. I've noticed that doing this will keep the syntax highlighter working.

**Comment by DanielSchaffer** [comment]
`@decorator` is nice, but I think it would also be good to automatically assume that any function whose return type is `ClassDecorator`, `MethodDecorator`, `PropertyDecorator`, or `ParamDecorator`, is a decorator as well.

**Comment by DanielSchaffer** [comment]
@aciccarello Some thoughts on further implementation for this:

From what I can tell, what's currently implemented is limited to finding decorators that have been applied to a target - so, functions that have been used as a decorator will have their targets listed under the reflection's `decorates` property, and targets that have been decorated will have the decorating functions listed under the reflection's `decorators` property.

What appears to be missing are test cases for param and property decorators - from what I can tell, param and property decorators should still get picked up by the existing logic, but it'd be good to add tests for them regardless.

The current implementation _won't_ pick up decorators that are defined, but not applied to any targets, since they wouldn't ever be included in any typescript node as a decorator, so that's where the rest of the implementation is needed.

This is my first time really looking at the typedoc source code, but from what I can tell, here's what could work:

**Adding a `Decorator` value to `ReflectionKind`** - I'm a little mixed on this as I'm not sure that decorators are really in the same class/level of concept as the rest of the things in there. In other words, everything already in that enum corresponds to a specific language token or pattern, but decorators are really only technically differentiated from functions by their usage. That said, it doesn't seem appropriate to add a property for it on `DeclarationReflection`

If I go with adding to the enum, I think it'd make sense to add `Decorator` as `16777216` (or whatever the next value is by the time I get in there), and also add `DecoratorFunction = Decorator | Function` - in practice, decorators would all use the `DecoratorFunction` value.

Setting the kind correctly seems like it would require an update in `FunctionConverter.convert`, which would check if `node.type` is any of `ClassDecorator`, `MethodDecorator`, `ParamDecorator`, or `PropertyDecorator`.

Another update in `CommentPlugin.applyModifiers` would be required to check for the `@decorator` tsdoc tag.

Alternatively, all of that work could be done in `DecoratorPlugin` if that makes more sense.

To include all this in the output, it looks like all that needs to happen is to add an entry for `Decorator` and `DecoratorFunction` to `MAPPINGS` in `DefaultTheme.

Thoughts? Anything missing?
